import {api,connect,login,logout,upload,money,date,esc,$,label,formValues,message,busy} from './shop-client.js?v=manual-20260908-2';
async function tasks(){const rows=await api('courierTasks');$('#content').innerHTML=`<div class="order-head"><h1>Pengantaran saya</h1><button id="refresh">Segarkan</button></div>${rows.map(o=>`<article class="panel"><div class="order-head"><strong>${esc(o.invoiceNo)}</strong><span class="badge">${esc(o.detailStatus)}</span></div><p>${o.slot?date(o.slot.startAt)+' – '+date(o.slot.endAt):'Jadwal belum ditentukan'}</p><h2>${esc(o.customerName)}</h2><p>${esc(o.addressData.text)}<br><a href="tel:${esc(o.phone.replace(/[^+0-9]/g,''))}">${esc(o.phone)}</a></p><a class="button" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${Number(o.addressData.lat)},${Number(o.addressData.lng)}">Navigasi ke penerima ↗</a><ul>${o.items.map(i=>`<li>${esc(i.productName)} · ${esc(i.variant)} · ${i.qty} unit (${i.pcs} pcs)</li>`).join('')}</ul><p>${esc(o.note)}</p><p>Tagihan tunai: <strong>${money(o.amountToCollect)}</strong><br>${esc(label(o.cashStatus))}</p>${!['selesai','dibatalkan'].includes(o.status)?`<div class="actions">${o.status==='diproses'?`<p>Admin perlu mengonfirmasi penyerahan paket melalui Tandai dikirim.</p>`:`<button data-action="travel" data-id="${o.id}">Dalam perjalanan</button>`}</div>${o.status==='dikirim'?`<form data-deliver="${o.id}"><label class="field">Nama penerima dan catatan serah terima<input name="receiptNote" maxlength="1000" required></label><p>Foto bukti dikirim manual ke admin; unggah privat belum aktif.</p><button class="primary">Paket diterima</button></form><form data-fail="${o.id}" class="inline-form"><label class="field">Alasan gagal antar<input name="reason" required maxlength="1000"></label><button>Catat gagal antar</button></form>`:''}`:''}${o.amountToCollect>0&&o.status!=='dibatalkan'?`<form data-cash="${o.id}"><label class="field">Aksi tunai<select name="operation"><option value="receive">Uang diterima</option><option value="deposit">Uang disetor ke kasir</option></select></label><label class="field">Nominal uang diterima (Rp)<input name="amount" type="number" min="0" step="1" value="${o.amountToCollect}"></label><label class="field">Referensi setoran<input name="reference" maxlength="200"></label><button>Simpan catatan tunai</button></form>`:''}</article>`).join('')||'<div class="empty">Belum ada tugas yang ditugaskan kepada Anda.</div>'}`;
$('#refresh').onclick=e=>busy(e.currentTarget,tasks);
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>busy(b,async()=>{await api('courierAction',{orderId:b.dataset.id,operation:b.dataset.action});await tasks();}));
document.querySelectorAll('[data-deliver]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const receiptNote=f.elements.receiptNote.value;busy(e.submitter,async()=>{await api('courierAction',{orderId:f.dataset.deliver,operation:'deliver',receiptNote});await tasks();});});
document.querySelectorAll('[data-fail]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const values=formValues(f);busy(e.submitter,async()=>{await api('courierAction',{orderId:f.dataset.fail,operation:'fail',...values});await tasks();});});
document.querySelectorAll('[data-cash]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const values=formValues(f);busy(e.submitter,async()=>{await api('cash',{orderId:f.dataset.cash,...values,amount:Number(values.amount)});await tasks();});});}
async function boot(){try{const c=await connect();c.auth.onAuthStateChanged(c.a,async u=>{try{if(!u){$('#logout').hidden=true;$('#content').innerHTML='<section class="panel narrow"><h1>Masuk sebagai kurir</h1><form id="login"><label class="field">Email<input name="email" type="email" required></label><label class="field">Password<input name="password" type="password" required></label><button class="primary">Masuk</button></form></section>';$('#login').onsubmit=e=>{e.preventDefault();const f=formValues(e.currentTarget);busy(e.submitter,()=>login(f.email,f.password));};return;}$('#logout').hidden=false;const profile=await c.fs.getDocFromServer(c.fs.doc(c.db,'courierProfiles',u.uid));if(!profile.exists()||!profile.data().active)throw Error('Akun ini tidak memiliki profil kurir aktif.');await tasks();}catch(e){$('#content').textContent='Tugas belum dapat dibuka.';message(e.message,true);}});$('#logout').onclick=()=>logout();}catch(e){message('Koneksi gagal. Muat ulang halaman. '+e.message,true);}}
boot();
