import {$,esc,input,area,checkbox,tabs,form,bindForm,message,date} from './planning-ui.js?v=kebijakan-20260913-r9';
import {supplierWorkflow} from './supplier-workflow-service.js?v=katalog-pembeli-20260909-r7';
import {PARTNERSHIP_DEFAULT,APPLICATION_LABELS,applicationNumber} from './supplier-workflow-domain.js?v=katalog-pembeli-20260909-r7';
export async function renderWebContent(U){
 const old=await U.store.get('siteContent/supplierPartnership'),content=old||PARTNERSHIP_DEFAULT;if(!U.isCurrent())return;
 $('#content').innerHTML='<h1>Data Web Katalog</h1>'+tabs('webcontent',[['kerjasama','Kerja Sama']],'kerjasama')+'<h2>Menjadi Supplier</h2><p>Konten ini tampil pada bagian Kerja Sama di katalog. Pengajuan diperiksa melalui modul Supplier.</p>'+form('partnership-content',input('title','Judul',content.title,'text','required maxlength="150"')+area('description','Deskripsi',content.description)+area('requirements','Persyaratan kerja sama',content.requirements)+input('buttonText','Teks tombol pendaftaran',content.buttonText,'text','required maxlength="80"')+checkbox('active','Aktifkan pendaftaran Supplier',content.active),'Simpan konten')+'<a href="toko.html?v=kebijakan-20260913-r9#kerjasama" target="_blank">Lihat bagian Kerja Sama di katalog</a>';
 bindForm('partnership-content',async(d,f)=>{await supplierWorkflow(U.store).configurePartnership(U.ctx,{...d,active:f.elements.active.checked,expectedRevision:old?.revision||0});await U.render();message('Konten Menjadi Supplier tersimpan.');});
}
export async function renderSupplierPartnership({store,c,user,isCurrent=()=>true}){
 const content=await store.get('siteContent/supplierPartnership')||PARTNERSHIP_DEFAULT,application=user?await store.get('supplierApplications/'+user.uid):null;if(!isCurrent())return;
 const safeLines=text=>esc(text).replaceAll('\n','<br>');
 $('#content').innerHTML='<section class="panel"><p class="eyebrow">Kerja Sama</p><h1>'+esc(content.title)+'</h1><p>'+safeLines(content.description)+'</p><h2>Persyaratan kerja sama</h2><p>'+safeLines(content.requirements)+'</p></section>'+(application?'<section class="panel"><h2>Pengajuan '+esc(applicationNumber(user.uid))+'</h2><p>'+esc(APPLICATION_LABELS[application.status])+' · '+date(application.updatedAt)+'</p><p>'+esc(application.reviewNote||'Pengajuan menunggu pemeriksaan admin.')+'</p></section>':'');
 if(!content.active){$('#content').insertAdjacentHTML('beforeend','<p class="notice">Pendaftaran Supplier sedang tidak aktif.</p>');return;}
 if(!user){$('#content').insertAdjacentHTML('beforeend','<section class="panel"><p>Masuk atau daftar memakai akun toko untuk mengirim pengajuan dan melihat statusnya. Pendaftaran Supplier tidak memberikan akses admin.</p><a class="button primary" href="#akun">Masuk / daftar akun toko</a></section>');return;}
 if(application&&application.status!=='needs_info')return;
 const a=application||{};$('#content').insertAdjacentHTML('beforeend','<h2>Formulir Penawaran</h2><p>Tawarkan barang yang dapat dipasok kepada toko Kubah Nabawi. Ini bukan pesanan pembelian atau pendaftaran reseller.</p>'+form('supplier-application',input('name','Nama usaha / supplier',a.name||'','text','required maxlength="150"')+input('pic','Nama penanggung jawab',a.pic||'','text','required maxlength="150"')+input('phone','Nomor WhatsApp / kontak',a.phone||'','tel','required maxlength="30"')+input('email','Email (opsional)',a.email??user.email??'','email','maxlength="150"')+area('address','Alamat atau kota',a.address||'')+input('category','Kategori produk yang ditawarkan',a.category||'','text','required maxlength="200"')+input('productName','Nama produk yang ditawarkan',a.productName||'','text','required maxlength="250"')+input('priceRange','Kisaran harga penawaran (Rp dan satuannya)',a.priceRange||'','text','required maxlength="300"')+input('minPurchase','Minimum pembelian (opsional)',a.minPurchase||'','text','maxlength="200"')+input('capacity','Kapasitas pasokan (opsional)',a.capacity||'','text','maxlength="200"')+area('offer','Rincian barang yang ditawarkan',a.offer||'')+area('notes','Catatan penawaran',a.notes||''),a.applicantUid?'Kirim informasi tambahan':content.buttonText));
 bindForm('supplier-application',async d=>{const result=await supplierWorkflow(store,{stamp:()=>c.fs.serverTimestamp()}).submitApplication({uid:user.uid},{...d,expectedRevision:a.revision||0});await renderSupplierPartnership({store,c,user,isCurrent});message('Pengajuan '+result.number+' tersimpan untuk pemeriksaan admin. Tidak ada akses admin atau dokumen internal yang diberikan.');});
}
