import {check,num,str,hash} from './manual-domain.js?v=katalog-pembeli-20260909-r7';
export const CATEGORIES=['Sajadah','Sarung','Atasan Pria','Mukenah & Atasan Wanita','Aksesoris & Songkok','Parfum','Makanan & Minuman'];
export const CHANNELS={website:'Website',manual_admin:'Manual Admin',reseller:'Reseller',unknown:'Belum diklasifikasikan'};
export function salesChannel(o){return ['website','manual_admin','reseller'].includes(o.salesChannel)?o.salesChannel:o.source==='website'?'website':o.source==='admin'?'manual_admin':'unknown';}
export const wibDay=(value=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(value?.toDate?.()||new Date(value));
export function day(value){check(/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value,'Tanggal tidak valid.');return value;}
export function dueState(invoice,today=wibDay(),thresholds=[7,3,0]){if(['lunas','dibatalkan','pending'].includes(invoice.status)||invoice.remaining<=0)return null;const days=Math.round((Date.parse(day(invoice.dueDate))-Date.parse(day(today)))/86400000);return {days,label:days<0?'Terlambat '+(-days)+' hari':days===0?'Jatuh tempo hari ini':'H-'+days,alert:days<=Math.max(...thresholds)};}
export function csv(rows,columns){const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';return '\ufeff'+[columns.map(c=>cell(c.label||c.key)).join(','),...rows.map(r=>columns.map(c=>cell(typeof c.value==='function'?c.value(r):r[c.key])).join(','))].join('\r\n');}
export const skuKey=value=>str(value,100,true).trim().toUpperCase();
export const skuId=value=>hash(skuKey(value)).slice(0,32);
export function pricingInput(d){const retail=num(Number(d.retail),1),wholesale=d.wholesale===''||d.wholesale==null?0:num(Number(d.wholesale)),minPcs=num(Number(d.minPcs||1),1),packPcs=num(Number(d.packPcs||1),1,10000);check(!wholesale||wholesale<=retail,'Harga grosir melebihi harga eceran.');return {retail,wholesale,minPcs,packPcs};}
export function unitPrice(p,v,qty,mode='eceran',approvedReseller=false,eligiblePcs=null){const w=p.website;check(w?.retail>0,'Tetapkan Harga Eceran/Grosir produk terlebih dahulu.');const vp=v?.pricing||{},pcs=num(Number(qty),1)*w.packPcs,n=eligiblePcs??pcs;let price=vp.retail||w.retail,kind='eceran';if(mode==='grosir')for(const t of w.tiers||[])if(n>=t.minPcs){price=vp.wholesale||t.price;kind='grosir';}if(approvedReseller&&w.reseller?.price>0&&n>=w.reseller.minPcs){price=w.reseller.price;kind='reseller';}return {price,kind,pcs,perPcs:price/w.packPcs};}
export const IMPORT_COLUMNS=['sku','name','category','subcategory','description','saleUnit','packPcs','weight','retail','wholesale','minPcs','variantSku','color','size','variantRetail','variantWholesale','stock','status','photos','variantPhoto','hpp'];
export const IMPORT_LABELS=["SKU Induk","Nama Produk","Kategori","Subkategori","Deskripsi","Satuan Jual","Pcs per Unit","Berat per Unit (gram)","Harga Eceran (Rp)","Harga Grosir (Rp)","Minimum Grosir (pcs)","SKU Varian","Warna","Ukuran","Eceran Varian (Rp)","Grosir Varian (Rp)","Stok (unit)","Status","Foto Produk (URL HTTPS)","Foto Varian (URL HTTPS)","HPP Internal (Rp)"];
export function importPreview(rows,products,{mode='add',stock=false}={}){
 rows=rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>{const i=IMPORT_LABELS.findIndex(label=>label.toLowerCase()===k.trim().toLowerCase());return [i<0?k.trim():IMPORT_COLUMNS[i],v];})));
 check(rows.length>0&&rows.length<=3000,'Impor 1–3.000 baris per berkas.');const groups=new Map(),errors=[];
 for(const [index,r] of rows.entries())try{const sku=skuKey(r.sku),vs=skuKey(r.variantSku);check(![...groups.values()].some(g=>g.rows.some(x=>skuKey(x.variantSku)===vs)),'SKU varian duplikat dalam berkas.');if(!groups.has(sku))groups.set(sku,{rows:[],row:index+2});groups.get(sku).rows.push(r);}catch(e){errors.push({row:index+2,error:e.message});}
 const plans=[];
 for(const [sku,g] of groups)try{
  const matches=products.filter(p=>p.sku&&skuKey(p.sku)===sku);check(matches.length<=1,'SKU produk sudah duplikat di database; selesaikan konflik dahulu.');const old=matches[0],r=g.rows[0];check(mode==='update'||!old,'SKU sudah ada; pilih mode Tambah & perbarui.');
  for(const x of g.rows)for(const k of ['name','category','packPcs','retail','wholesale','minPcs','status'])check(String(x[k]??'')===String(r[k]??''),'Data induk berbeda antarbaris varian: '+k);
  check(CATEGORIES.includes(r.category),'Pilih salah satu dari tujuh kategori; kategori lama harus dipetakan secara eksplisit.');const pr=pricingInput(r);check(['aktif','nonaktif','draft'].includes(r.status),'Status wajib aktif/nonaktif/draft.');
  const images=(!r.photos&&old?.images?.length)?old.images:String(r.photos||'').split('|').filter(Boolean).map((url,i)=>{check(/^https:\/\//.test(url),'Foto harus URL HTTPS, bukan lokasi file komputer.');return {url,isPrimary:i===0};});
  const variants=[...(old?.variants||[])].map(v=>({...v}));
  for(const vr of g.rows){const vs=skuKey(vr.variantSku),existing=variants.find(v=>v.sku&&skuKey(v.sku)===vs);check(!products.some(p=>p.id!==old?.id&&p.variants?.some(v=>v.sku&&skuKey(v.sku)===vs)),'SKU varian dipakai produk lain.');const v={...existing,id:existing?.id||'V-'+skuId(vs),sku:vs,color:str(String(vr.color||''),100),size:str(String(vr.size||''),100),stock:existing&&!stock?existing.stock:num(Number(vr.stock)),pricing:{retail:vr.variantRetail?num(Number(vr.variantRetail),1):null,wholesale:vr.variantWholesale?num(Number(vr.variantWholesale),1):null},image:String(vr.variantPhoto||existing?.image||'')};check(!v.image||v.image.startsWith('https://'),'Foto varian harus HTTPS.');if(vr.hpp!==''&&vr.hpp!=null)v.hpp=num(Number(vr.hpp));if(existing)variants[variants.indexOf(existing)]=v;else variants.push(v);}
  const product={...old,sku,name:str(String(r.name||''),250,true),category:r.category,subcategory:str(String(r.subcategory||''),100),description:String(r.description||''),saleUnit:str(String(r.saleUnit||'pcs'),40),weight:num(Number(r.weight||0)),status:r.status,images,variants,pricingVersion:2,website:{...old?.website,enabled:r.status==='aktif',retail:pr.retail,packPcs:pr.packPcs,tiers:pr.wholesale?[{minPcs:pr.minPcs,price:pr.wholesale},...(old?.website?.tiers||[]).slice(1)]:[],combine:old?.website?.combine||'product',group:old?.website?.group||'',promo:old?.website?.promo||false,reseller:old?.website?.reseller||{price:0,minPcs:20}}};
  plans.push({id:old?.id||'P-'+skuId(sku),product,expectedRevision:old?.revision||0,stock,kind:old?'perbarui':'tambah',key:'import-'+hash([g.rows,stock]),importHash:hash([g.rows,stock]),row:g.row});
 }catch(e){errors.push({row:g.row,sku,error:e.message});}
 return {plans,errors};
}
