import {productLifecycle} from './product-lifecycle.js?v=products-20260917-r16';
import {$,esc,money,input,area,select,checkbox,tabs,table,form,bindForm,busy,message,download} from './planning-ui.js?v=audit-20260920-r17';
import {CATEGORIES,IMPORT_COLUMNS,IMPORT_LABELS,importPreview,pricingInput,skuId,csv,unitPrice} from './planning-domain.js?v=products-20260917-r16';
import {productService} from './product-service.js?v=products-20260917-r16';
import {check,num} from './manual-domain.js?v=products-20260917-r16';
import {movementService,movementOptions,movementStatus,movementLabel,movementRows,movementCounts} from './product-movement.js?v=products-20260917-r16';
import {mountVariantTable} from './variant-table.js?v=audit-20260920-r17';
import {applyFormChanges} from './variant-draft.js?v=products-20260917-r16';
let filter={query:'',category:'',status:'',movement:'',publication:'',archive:'normal'};
const badge=m=>`<span class="movement-badge movement-${movementStatus(m)||'unrated'}">${movementLabel(m)}</span>`;
const excel=(name,rows)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi lalu coba lagi, atau gunakan CSV.');const sheet=XLSX.utils.json_to_sheet(rows.map(r=>Object.fromEntries(IMPORT_COLUMNS.map((k,i)=>[IMPORT_LABELS[i],r[k]??'']))),{header:IMPORT_LABELS}),book=XLSX.utils.book_new();sheet['!cols']=IMPORT_COLUMNS.map(k=>({wch:['name','description','photos'].includes(k)?36:20}));XLSX.utils.book_append_sheet(book,sheet,'Produk');XLSX.writeFile(book,name);};
export async function renderProducts(U){const [products,movementData]=await Promise.all([U.store.list('products'),U.store.list('productMovements')]);const movements=new Map(movementData.map(m=>[m.id,m]));if(!U.isCurrent())return;const active=U.tab==='impor'?'impor':['migrasi','pergerakan'].includes(U.tab)?'pergerakan':'daftar';
 $('#content').innerHTML=`<div class="page-head"><div><h1>Produk</h1><p>Harga Eceran/Grosir, stok, dan katalog pembeli dalam satu data produk.</p></div><a class="button primary" href="#products/new">Tambah produk</a></div>${tabs('products',[['','Daftar Produk'],['impor','Impor Excel'],['pergerakan','Status Pergerakan Produk']],active==='daftar'?'':active)}<div id="product-body"></div>`;
 document.querySelector('.tabs').classList.add('product-tabs');
 if(U.tab&&!['impor','migrasi','pergerakan'].includes(U.tab)){editor(products.find(p=>p.id===U.tab)||null);return;}
 if(U.tab==='impor'){importer();return;}
 $('#product-body').innerHTML=(active==='pergerakan'?'<p class="notice">Penilaian manual internal: Fast Moving (cepat), Medium (sedang), Slow Moving (lambat), Dead Stok (stok mengendap). Status tidak mengubah stok, harga, atau publikasi.</p><div id="movement-summary" class="movement-summary"></div><div id="movement-editor"></div>':'')+`<div class="filters">${active==='daftar'?select('archive','Daftar produk',[['normal','Produk tersedia'],['trash','Sampah']],filter.archive):''}${input('query','Cari nama / SKU',filter.query,'search')}${select('category','Kategori',[['','Semua kategori'],...CATEGORIES],filter.category)}${select('status','Status',[['','Semua status'],['aktif','Aktif'],['draft','Draft'],['nonaktif','Nonaktif']],filter.status)}${select('publication','Publikasi katalog',[['','Semua publikasi'],['published','Terbit'],['unpublished','Belum terbit']],filter.publication)}${select('movement','Status pergerakan',[['','Semua penilaian'],['unrated','Belum dinilai'],...movementOptions.slice(1)],filter.movement)}<button id="export-products">Ekspor hasil filter</button></div><section class="panel" id="products-table"></section>`;
 function rows(){return movementRows(products.filter(p=>active==='pergerakan'||filter.archive!=='trash'?p.deleted!==true:p.deleted===true),movements,filter);}
 function paint(){const list=rows();if(active==='pergerakan'){
 const counts=movementCounts(products.filter(p=>p.deleted!==true),movements);$('#movement-summary').innerHTML=movementOptions.map(([key,label])=>`<div class="panel">${badge({status:key})}<strong>${counts[key]}</strong><small>produk keseluruhan</small></div>`).join('');
 $('#products-table').innerHTML=`<p>${list.length} produk sesuai filter</p>`+table(['Foto','Produk / SKU','Kategori','Stok','Status pergerakan','Aksi'],list.map(p=>{const src=p.images?.[0]?.url||p.photoUrl;return [src&&/^https?:/.test(src)?`<img class="movement-photo" src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`:'Tanpa foto',esc(p.name)+'<br><small>'+esc(p.sku||'SKU belum diisi')+'</small>',esc(p.category||'Belum dipetakan'),esc(p.totalStock??(p.variants||[]).reduce((s,v)=>s+Number(v.stock||0),0)),badge(movements.get(p.id)),`<button data-movement="${esc(p.id)}" aria-label="Ubah status ${esc(p.name)}">Ubah status</button>`];}));
 document.querySelectorAll('[data-movement]').forEach(b=>b.onclick=()=>editMovement(b.dataset.movement));return;}
$('#products-table').innerHTML=`<p>${list.length} produk</p>`+table(['Produk / SKU','Kategori','Eceran / unit','Grosir / minimum','Stok / kemasan','Publikasi','Pergerakan','Aksi'],list.map(p=>[esc(p.name)+'<br><small>'+esc(p.sku||'SKU perlu diisi')+'</small>',esc(p.category||'Belum dipetakan'),p.website?.retail?money(p.website.retail):'Belum ditetapkan',(p.website?.tiers||[]).map(t=>money(t.price)+' / '+t.minPcs+' pcs').join('<br>')||'Ikut harga eceran',`${p.totalStock??(p.variants||[]).reduce((s,v)=>s+v.stock,0)} unit<br>${Number.isSafeInteger(p.website?.packPcs)&&p.website.packPcs>0?p.website.packPcs+' pcs / unit':'Isi kemasan belum ditetapkan'}`,esc(p.status)+(p.website?.enabled?' · katalog aktif':' · belum terbit')+(p.pricingVersion!==2?'<br><small>Perlu tinjau model harga</small>':''),badge(movements.get(p.id)),`<div class="product-row-actions">${p.deleted?`<button type="button" data-restore="${esc(p.id)}">Pulihkan</button>`:`<a class="button" href="#products/${esc(p.id)}">Periksa & ubah</a><button type="button" class="danger" data-trash="${esc(p.id)}">Hapus</button>`}</div>`]));document.querySelectorAll('[data-trash]').forEach(b=>b.onclick=()=>lifecycleDialog(products.find(p=>p.id===b.dataset.trash),true));document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>lifecycleDialog(products.find(p=>p.id===b.dataset.restore),false));}
 document.querySelectorAll('.filters input,.filters select').forEach(el=>el.oninput=()=>{filter[el.name]=el.value;if(el.name==='archive'){filter.status='';filter.publication='';document.querySelector('.filters [name=status]').value='';document.querySelector('.filters [name=publication]').value='';}paint();});paint();$('#export-products').onclick=()=>{const out=exportRows(rows());excel('Produk-Kubah-Nabawi.xlsx',out);};
 function editMovement(pid){const p=products.find(p=>p.id===pid),old=movements.get(pid);
 $('#movement-editor').innerHTML=form('movement-edit','<h2 class="full">'+esc(p.name)+'</h2>'+select('movementValue','Status pergerakan',movementOptions,movementStatus(old))+'<p class="full">Hanya penilaian internal yang disimpan. Harga dan stok tetap.</p>','Simpan status');
 $('#movement-editor').scrollIntoView({block:'nearest'});
 bindForm('movement-edit',async d=>{await movementService(U.store).save(U.ctx,{productId:pid,status:d.movementValue,expectedRevision:old?.revision||0});movements.set(pid,await U.store.get('productMovements/'+pid));paint();$('#movement-editor').innerHTML='';message('Status pergerakan tersimpan.');});
 }
 function lifecycleDialog(p,deleted){
  const dialog=document.createElement('dialog'),key=crypto.randomUUID();let pending=false;
  dialog.className='product-trash-dialog';dialog.setAttribute('aria-labelledby','product-trash-title');
  dialog.innerHTML=`<h2 id="product-trash-title">${deleted?'Hapus Produk':'Pulihkan Produk'}</h2><p><strong>${esc(p.name)}</strong><br>SKU: ${esc(p.sku||'Belum diisi')}</p><p>${deleted?'Produk beserta seluruh variannya akan disembunyikan dari katalog dan dipindahkan ke Sampah. Data produk, foto, stok, harga dan pesanan lama tetap tersimpan. Produk dapat dipulihkan. Edit formulir yang belum disimpan tidak ikut disimpan.':'Produk akan dipulihkan sebagai belum terbit. Stok terkini tetap digunakan; tidak ada stok yang ditambahkan kembali. Tinjau produk sebelum menerbitkannya.'}</p><p data-trash-error role="alert" class="notice error" hidden></p><div class="actions"><button type="button" data-cancel>Batal</button><button type="button" data-confirm class="${deleted?'danger':'primary'}">${deleted?'Pindahkan ke Sampah':'Pulihkan'}</button></div>`;
  document.body.append(dialog);dialog.showModal();const cancel=dialog.querySelector('[data-cancel]'),confirm=dialog.querySelector('[data-confirm]');cancel.focus();
  cancel.onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(pending)e.preventDefault();});dialog.addEventListener('close',()=>dialog.remove());
  confirm.onclick=async()=>{if(pending)return;pending=true;confirm.disabled=true;cancel.disabled=true;const notice=dialog.querySelector('[data-trash-error]');notice.hidden=true;
   try{const result=await productLifecycle(U.store).setTrashed(U.ctx,{productId:p.id,deleted,key,expectedTrashVersion:p.trashVersion||0});dialog.close();await U.render();message(result.deleted?'Produk dipindahkan ke Sampah dan disembunyikan dari katalog.':'Produk dipulihkan sebagai belum terbit. Tinjau sebelum menerbitkan.');}
   catch(error){notice.hidden=false;notice.textContent=error.message||'Penyimpanan gagal. Coba lagi.';}
   finally{pending=false;confirm.disabled=false;cancel.disabled=false;}
  };
 }
 function editor(old){if(old?.deleted){$('#product-body').innerHTML='<section class="panel"><h2>'+esc(old.name)+'</h2><p>SKU: '+esc(old.sku)+'</p><p>Produk berada di Sampah. Data seluruh varian, harga, stok, berat dan foto tetap tersimpan. Pulihkan produk sebelum mengeditnya.</p><button type="button" id="restore-product">Pulihkan</button></section>';$('#restore-product').onclick=()=>lifecycleDialog(old,false);return;}const p=old||{},w=p.website||{},t=w.tiers?.[0]||{},key=crypto.randomUUID();let base=old?structuredClone(old):null;let variants=(p.variants||[{id:'V-'+crypto.randomUUID(),stock:0}]).map(v=>({...v}));
  $('#product-body').innerHTML=(old&&p.pricingVersion!==2?`<section class="panel"><h2>Tinjau harga lama</h2><p>Offline: ${money(p.priceOffline)} · Online: ${money(p.priceOnline)}. Tentukan sendiri harga yang benar di bawah. Cadangan lengkap dibuat saat menyimpan.</p></section>`:'')+form('product-edit',input('name','Nama produk',p.name||'','text','required maxlength="250"')+input('sku','SKU induk',p.sku||'','text','required maxlength="100"')+select('category','Kategori',[['','Pilih kategori'],...(p.category&&!CATEGORIES.includes(p.category)?[[p.category,p.category+' — perlu dipetakan']]:[]),...CATEGORIES],p.category)+input('subcategory','Subkategori',p.subcategory||'')+input('saleUnit','Satuan jual (misalnya pak)',p.saleUnit||(old?'':'pcs'),'text','required')+input('packPcs','Pcs per satuan jual',w.packPcs??(old?'':1),'number','min="1" required')+input('weight','Berat per satuan jual (gram)',p.weight||0,'number','min="0" required')+input('retail','Harga Eceran per satuan jual (Rp)',w.retail||'','number','min="1" required')+input('wholesale','Harga Grosir per satuan jual (opsional)',t.price||'','number','min="1"')+input('minPcs','Minimum Grosir (pcs)',t.minPcs||1,'number','min="1" required')+select('combine','Gabungkan minimum grosir',[['product','Varian dalam produk'],['variant','Masing-masing varian'],['all','Kelompok produk yang sama']],w.combine||'product')+input('group','Kode kelompok grosir',w.group||'')+input('resellerPrice','Harga reseller disetujui (opsional)',w.reseller?.price||'','number','min="1"')+input('resellerMin','Minimum reseller (pcs)',w.reseller?.minPcs||20,'number','min="1"')+select('status','Status publikasi',[['draft','Draft'],['aktif','Aktif dan terbit di katalog'],['nonaktif','Nonaktif']],p.status||'draft')+select('movementValue','Status pergerakan — internal admin',movementOptions,movementStatus(movements.get(p.id)))+checkbox('wholesaleCollection','Tampilkan dalam koleksi Paket Grosir',p.collections?.includes('paket-grosir'))+checkbox('promo','Ikut promo gratis ongkir (syarat 20 pcs tetap terpisah)',!!w.promo)+area('description','Deskripsi',p.description||'')+area('photos','URL foto HTTPS, satu per baris (maksimal 9)',(p.images?.length?p.images:[{url:p.photoUrl}]).map(i=>i.url).filter(Boolean).join('\n'))+'<div id="variants" class="full"></div><div id="stock-conflict" class="full"></div>'+input('reason','Alasan pembaruan',old?'Perbarui produk / pemetaan harga':'Produk baru','text','required')+'<div class="full" id="price-preview"></div>'+checkbox('confirmed','Saya sudah memeriksa harga, kategori, varian, foto, dan status publikasi'),'Simpan produk & sinkronkan katalog');
  const f=$('#product-edit');
  if(old){const b=document.createElement('button');b.type='button';b.className='danger product-trash-edit';b.textContent='Hapus Produk';b.onclick=()=>lifecycleDialog(old,true);f.append(b);}
  const tableDraft=mountVariantTable($('#variants'),{variants,parent:p,c:U.c,canEdit:U.ctx.role==='admin',onChange:()=>{f.dataset.dirty='true';}});
  const collectVariants=()=>tableDraft.read();
  function draftProduct(d){return {...p,name:d.name,sku:d.sku,category:d.category,subcategory:d.subcategory,saleUnit:d.saleUnit,description:d.description,weight:Number(d.weight),status:d.status,collections:f.elements.wholesaleCollection.checked?['paket-grosir']:[],images:d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,i)=>({url,isPrimary:i===0})),variants:collectVariants(),website:{...w,enabled:d.status==='aktif',retail:Number(d.retail),packPcs:Number(d.packPcs),tiers:d.wholesale?[{minPcs:Number(d.minPcs),price:Number(d.wholesale)},...(w.tiers||[]).slice(1)]:[],reseller:{price:Number(d.resellerPrice||0),minPcs:Number(d.resellerMin||20)},promo:f.elements.promo.checked,combine:d.combine,group:d.group}};}
  let formBaseline=draftProduct(Object.fromEntries(new FormData(f)));
  const preview=()=>{const f=$('#product-edit'),r=Number(f.elements.retail.value),pack=Number(f.elements.packPcs.value);tableDraft.updateParent({saleUnit:f.elements.saleUnit.value,packPcs:pack,retail:f.elements.retail.value,wholesale:f.elements.wholesale.value,weight:f.elements.weight.value});$('#price-preview').textContent=r>0&&pack>0?`Harga eceran ${money(r)} / ${f.elements.saleUnit.value} (${pack} pcs), setara ${money(r/pack)} / pcs. Harga grosir berlaku mulai ${f.elements.minPcs.value} pcs.`:'Lengkapi Harga Eceran dan isi kemasan.';};$('#product-edit').addEventListener('input',preview);preview();
  bindForm('product-edit',async(d,f)=>{check(f.elements.confirmed.checked,'Tinjau rincian lalu centang konfirmasi.');check(CATEGORIES.includes(d.category),'Petakan kategori lama ke kategori yang tersedia.');const prices=pricingInput(d),vs=collectVariants();check(!vs.some(v=>v.pricing.wholesale&&!prices.wholesale),'Isi harga grosir induk sebelum membuat harga grosir varian.');const images=d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,i)=>{check(/^https:\/\//.test(url),'Foto harus URL HTTPS publik.');return {url,isPrimary:i===0};});check(images.length<=9,'Maksimal 9 foto.');
   const pid=p.id||'P-'+skuId(d.sku);check(!tableDraft.pending(),'Tunggu pratinjau foto selesai.');
   // Lock the draft while its photos and transaction are being saved.
   const controls=[...f.querySelectorAll('input,select,textarea,button')],disabled=controls.map(el=>el.disabled);controls.forEach(el=>el.disabled=true);tableDraft.setLocked(true);
   try {
    await tableDraft.upload(pid);
    const entered=draftProduct(d),product=base?applyFormChanges(base,formBaseline,entered):entered;
    const result=await productService(U.store).save(U.ctx,{id:pid,product,base:base||undefined,movement:d.movementValue!==movementStatus(movements.get(p.id))?{status:d.movementValue,expectedRevision:movements.get(p.id)?.revision||0}:undefined,expectedRevision:base?.revision||0,key,stock:true,reason:d.reason});
    tableDraft.dispose();location.hash='products';if(U.tab==='')await U.render();message('Produk tersimpan. Publikasi katalog mengikuti status yang dipilih. ID '+result.id);
   } catch(error) {
    if(error.code==='stock-conflict'){$('#stock-conflict').innerHTML='<section class="notice error"><h3>Stok perlu ditinjau</h3>'+table(['Varian','Saat dibuka','Stok terbaru','Draf Anda'],error.conflicts.map(x=>[esc(x.sku||x.id),x.previous,x.current,x.requested]))+'<p>Muat stok terbaru ke formulir. Harga dan edit lain dipertahankan; isi kembali stok akhir setelah ditinjau.</p><button type="button" id="review-latest-stock">Muat stok terbaru</button></section>';$('#review-latest-stock').onclick=e=>busy(e.currentTarget,async()=>{const latest=await U.store.get('products/'+pid);check(latest,'Produk tidak tersedia.');tableDraft.reviewStock(latest);base.revision=latest.revision||0;for(const v of base.variants){const current=latest.variants.find(x=>x.id===v.id);if(current){v.stock=current.stock;v.reserved=current.reserved||0;const initial=formBaseline.variants.find(x=>x.id===v.id);if(initial){initial.stock=current.stock;initial.reserved=current.reserved||0;}}}$('#stock-conflict').innerHTML='';message('Stok terbaru dimuat. Tinjau kembali sebelum Simpan Produk.');});$('#stock-conflict').scrollIntoView({block:'center'});}
    throw error;
   } finally {controls.forEach((el,i)=>el.disabled=disabled[i]);tableDraft.setLocked(false);}
  });
 }
 function importer(){let preview=null,parsed=[];
  $('#product-body').innerHTML=`<section class="panel"><h2>Impor & sinkronisasi katalog</h2><p>Gunakan SKU induk dan SKU varian yang tetap. URL foto HTTPS dapat dipisahkan dengan tanda |. Foto tertanam di Excel dan upload foto massal belum didukung pada versi ini.</p><div class="actions"><button id="template-xlsx">Unduh template Excel</button><button id="template-csv">Unduh template CSV</button></div></section>`+form('import-preview',input('file','Berkas XLSX / CSV','','file','accept=".xlsx,.csv" required')+select('mode','Mode',[['add','Tambah produk baru'],['update','Tambah & perbarui SKU yang ada']])+checkbox('stock','Perbarui stok produk lama dari berkas (perlu pemeriksaan)'),'Baca & tampilkan pratinjau')+'<section id="import-result"></section>';
  const example=()=>[{sku:'CONTOH-SARUNG',name:'Sarung Contoh',category:'Sarung',subcategory:'',description:'Ganti data contoh sebelum impor',saleUnit:'pak',packPcs:10,weight:3000,retail:500000,wholesale:450000,minPcs:20,variantSku:'CONTOH-SARUNG-BIRU',color:'Biru',size:'Dewasa',variantRetail:'',variantWholesale:'',stock:0,status:'draft',photos:'',variantPhoto:'',hpp:''}];
  $('#template-xlsx').onclick=()=>{const a=document.createElement('a');a.href='Template-Produk-Kubah-Nabawi.xlsx';a.download='Template-Produk-Kubah-Nabawi.xlsx';a.click();};$('#template-csv').onclick=()=>download('Template-Produk-Kubah-Nabawi.csv',csv(example(),IMPORT_COLUMNS.map(key=>({key}))));
  bindForm('import-preview',async(d,f)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi.');const file=f.elements.file.files[0];check(file.size<=10*1024*1024,'Berkas impor maksimal 10 MB.');const book=XLSX.read(await file.arrayBuffer(),{type:'array'});parsed=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''});preview=importPreview(parsed,products,{mode:d.mode,stock:f.elements.stock.checked});const {plans,errors}=preview;
   $('#import-result').innerHTML='<div class="panel"><h2>Pratinjau perubahan</h2><p>'+plans.length+' produk valid · '+errors.length+' kesalahan. Tidak ada data tersimpan sebelum konfirmasi.</p>'+table(['Baris','SKU','Nama','Tindakan','Publikasi','Stok lama'],plans.map(p=>[p.row,esc(p.product.sku),esc(p.product.name),p.kind,esc(p.product.status),p.stock?'Akan diperbarui':'Dipertahankan']))+table(['Baris','SKU','Kesalahan'],errors.map(e=>[e.row,esc(e.sku),esc(e.error)]))+checkbox('applyConfirm','Saya menyetujui rincian ini, termasuk produk aktif yang akan terbit di katalog.')+'<button id="apply-import" class="primary" '+(errors.length||!plans.length?'disabled':'')+'>Terapkan impor</button><div id="import-progress" role="status"></div></div>';
   $('#apply-import').onclick=e=>busy(e.currentTarget,async()=>{check($('[name=applyConfirm]').checked,'Centang konfirmasi publikasi terlebih dahulu.');const results=[];for(const plan of plans){try{const r=await productService(U.store).save(U.ctx,plan);results.push({sku:plan.product.sku,id:r.id,status:r.reused?'Sudah tersimpan sebelumnya':'Berhasil',error:''});}catch(error){results.push({sku:plan.product.sku,id:plan.id,status:'Gagal',error:error.message});}$('#import-progress').textContent=`Memproses ${results.length}/${plans.length} produk…`;}
    $('#import-progress').innerHTML=table(['SKU','ID','Hasil','Keterangan'],results.map(r=>[esc(r.sku),esc(r.id),esc(r.status),esc(r.error)]))+'<button type="button" id="download-report">Unduh laporan impor</button><p>Muat ulang pratinjau sebelum memperbaiki produk yang gagal. Produk yang sudah berhasil tidak digandakan ketika berkas yang sama dicoba lagi.</p>';$('#download-report').onclick=()=>download('Hasil-Impor-Produk.csv',csv(results,['sku','id','status','error'].map(key=>({key}))));message(results.some(r=>r.status==='Gagal')?'Sebagian produk gagal. Periksa laporan.':'Seluruh produk pada pratinjau berhasil disimpan.',results.some(r=>r.status==='Gagal'));});
  });
 }
}
function exportRows(products){return products.flatMap(p=>(p.variants||[]).map(v=>({sku:p.sku,name:p.name,category:p.category,subcategory:p.subcategory||'',description:p.description||'',saleUnit:p.saleUnit||'unit',packPcs:p.website?.packPcs??'',weight:p.weight||0,retail:p.website?.retail||'',wholesale:p.website?.tiers?.[0]?.price||'',minPcs:p.website?.tiers?.[0]?.minPcs||1,variantSku:v.sku,color:v.color,size:v.size,variantRetail:v.pricing?.retail||'',variantWholesale:v.pricing?.wholesale||'',stock:v.stock,status:p.status,photos:(p.images||[]).map(i=>i.url).join('|'),variantPhoto:v.image||'',hpp:v.hpp??p.hpp??''})));}
export async function renderCalculator(U){const products=await U.store.list('products');if(!U.isCurrent())return;$('#content').innerHTML='<h1>Perbandingan Harga</h1><p>Perbandingan per satuan jual dan per pcs. Perhitungan tidak mengubah harga produk atau pesanan lama.</p>'+form('calculator',select('productId','Produk',products.filter(p=>p.website?.retail>0).map(p=>[p.id,p.name]))+select('variantId','Varian',[])+input('qty','Jumlah unit',1,'number','min="1" required')+select('mode','Mode',['eceran','grosir'])+checkbox('reseller','Gunakan harga reseller disetujui (simulasi kalkulator)'),'Hitung')+'<section class="panel" id="calculation"></section>';
 const change=()=>{const p=products.find(p=>p.id===$('[name=productId]').value);$('[name=variantId]').innerHTML=(p?.variants||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.sku+' '+(v.color||'')+' '+(v.size||''))}</option>`).join('');};$('[name=productId]').onchange=change;change();bindForm('calculator',(d,f)=>{const p=products.find(p=>p.id===d.productId);check(p,'Pilih produk yang harganya sudah ditetapkan.');const v=p.variants.find(v=>v.id===d.variantId),q=Number(d.qty),r=unitPrice(p,v,q,d.mode,f.elements.reseller.checked),hpp=v.hpp??p.hpp;$('#calculation').innerHTML=table(['Keterangan','Hasil'],[['Harga yang berlaku',esc(r.kind)],['Jumlah',q+' unit / '+r.pcs+' pcs'],['Harga per unit',money(r.price)],['Setara per pcs',money(r.perPcs)],['Total penjualan',money(r.price*q)],['HPP total',hpp==null?'Belum tersedia':money(hpp*q)],['Selisih sebelum biaya lain',hpp==null?'Belum tersedia':money((r.price-hpp)*q)]]);});}
