import {productLifecycle} from './product-lifecycle.js?v=products-20260917-r16';
import {$,esc,money,input,area,select,checkbox,tabs,table,form,bindForm,busy,message,download} from './planning-ui.js?v=audit-20260920-r17';
import {CATEGORIES,IMPORT_COLUMNS,IMPORT_LABELS,importPreview,pricingInput,skuId,csv,unitPrice} from './planning-domain.js?v=products-20260917-r16';
import {productService} from './product-service.js?v=product-save-20260923-r19c';
import {check,num} from './manual-domain.js?v=products-20260917-r16';
import {movementService,movementOptions,movementStatus,movementLabel,movementRows,movementCounts} from './product-movement.js?v=products-20260917-r16';
import {mountVariantTable} from './variant-table.js?v=product-save-20260923-r19c';
import {applyFormChanges,resolveProductConflict,imageList,same} from './variant-draft.js?v=product-save-20260923-r19c';
import {productDrafts} from './product-edit-draft.js?v=product-save-20260923-r19c';
let filter={query:'',category:'',status:'',movement:'',publication:'',archive:'normal'};
const badge=m=>`<span class="movement-badge movement-${movementStatus(m)||'unrated'}">${movementLabel(m)}</span>`;
const excel=(name,rows)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi lalu coba lagi, atau gunakan CSV.');const sheet=XLSX.utils.json_to_sheet(rows.map(r=>Object.fromEntries(IMPORT_COLUMNS.map((k,i)=>[IMPORT_LABELS[i],r[k]??'']))),{header:IMPORT_LABELS}),book=XLSX.utils.book_new();sheet['!cols']=IMPORT_COLUMNS.map(k=>({wch:['name','description','photos'].includes(k)?36:20}));XLSX.utils.book_append_sheet(book,sheet,'Produk');XLSX.writeFile(book,name);};
export async function renderProducts(U){const [products,movementData]=await Promise.all([U.store.list('products'),U.store.list('productMovements')]);const movements=new Map(movementData.map(m=>[m.id,m]));if(!U.isCurrent())return;const active=U.tab==='impor'?'impor':['migrasi','pergerakan'].includes(U.tab)?'pergerakan':'daftar';
 $('#content').innerHTML=`<div class="page-head"><div><h1>Produk</h1><p>Harga Eceran/Grosir, stok, dan katalog pembeli dalam satu data produk.</p></div><a class="button primary" href="#products/new">Tambah produk</a></div>${tabs('products',[['','Daftar Produk'],['impor','Impor Excel'],['pergerakan','Status Pergerakan Produk']],active==='daftar'?'':active)}<div id="product-body"></div>`;
 document.querySelector('.tabs').classList.add('product-tabs');
 if(U.tab&&!['impor','migrasi','pergerakan'].includes(U.tab)){editor(products.find(p=>p.id===U.tab)||null);return;}
 if(U.tab==='impor'){importer();return;}
 $('#product-body').innerHTML=(active==='pergerakan'?'<p class="notice">Penilaian manual internal: Fast Moving (cepat), Medium (sedang), Slow Moving (lambat), Dead Stok (stok mengendap). Status tidak mengubah stok, harga, atau publikasi.</p><div id="movement-summary" class="movement-summary"></div><div id="movement-editor"></div>':'')+`<div class="filters">${active==='daftar'?select('archive','Daftar produk',[['normal','Produk tersedia'],['trash','Sampah']],filter.archive):''}${input('query','Cari nama / SKU',filter.query,'search')}${select('category','Kategori',[['','Semua kategori'],...CATEGORIES],filter.category)}${select('status','Status',[['','Semua status'],['aktif','Aktif'],['draft','Draft'],['nonaktif','Nonaktif']],filter.status)}${select('publication','Publikasi katalog',[['','Semua publikasi'],['published','Terbit'],['unpublished','Belum terbit']],filter.publication)}${select('movement','Status pergerakan',[['','Semua penilaian'],['unrated','Belum dinilai'],...movementOptions.slice(1)],filter.movement)}<button id="export-products">Ekspor hasil filter</button></div><section class="panel" id="products-table"></section>`;
 function rows(){return movementRows(products.filter(p=>active==='pergerakan'||filter.archive!=='trash'?p.deleted!==true:p.deleted===true),movements,filter);}
 function paint(){const list=rows();if(active==='pergerakan'){
 const counts=movementCounts(products.filter(p=>p.deleted!==true),movements);$('#movement-summary').innerHTML=movementOptions.map(([key,label])=>`<div class="panel">${badge({status:key})}<strong>${counts[key]}</strong><small>produk keseluruhan</small></div>`).join('');
 $('#products-table').innerHTML=`<p>${list.length} produk sesuai filter</p>`+table(['Foto','Produk / SKU','Kategori','Stok','Status pergerakan','Aksi'],list.map(p=>{const src=p.images?.[0]?.url||p.photoUrl;return [src&&/^https?:/.test(src)?`<img class="movement-photo" src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`:'Tanpa foto',esc(p.name)+'<br><small>'+esc(p.sku||'SKU belum diisi')+'</small>',esc(p.category||'Belum dipetakan'),esc(p.totalStock??(p.variants||[]).reduce((s,v)=>s+Number(v.stock||0),0)),badge(movements.get(p.id)),`<button data-movement="${esc(p.id)}" aria-label="Ubah status ${esc(p.name)}">Ubah status</button>`];}));
 document.querySelectorAll('[data-movement]').forEach(b=>b.onclick=()=>editMovement(b.dataset.movement));return;}
$('#products-table').innerHTML=`<p>${list.length} produk</p>`+table(['Produk / SKU','Kategori','Eceran / unit','Grosir / minimum','Stok / kemasan','Publikasi','Pergerakan','Aksi'],list.map(p=>[esc(p.name)+'<br><small>'+esc(p.sku||'SKU perlu diisi')+'</small>',esc(p.category||'Belum dipetakan'),p.website?.retail?money(p.website.retail):'Belum ditetapkan',(p.website?.tiers||[]).map(t=>money(t.price)+' / '+t.minPcs+' pcs').join('<br>')||'Ikut harga eceran',`${p.totalStock??(p.variants||[]).reduce((s,v)=>s+v.stock,0)} unit<br>${Number.isSafeInteger(p.website?.packPcs)&&p.website.packPcs>0?p.website.packPcs+' pcs / unit':'Isi kemasan belum ditetapkan'}`,esc(p.status)+(p.website?.enabled?' · katalog aktif':' · belum terbit')+(p.pricingVersion!==2?'<br><small>Perlu tinjau model harga</small>':''),badge(movements.get(p.id)),`<div class="product-row-actions">${p.deleted?`<button type="button" data-restore="${esc(p.id)}">Pulihkan</button>`:`<a class="button" href="#products/${esc(p.id)}">Periksa & ubah</a><button type="button" class="danger" data-trash="${esc(p.id)}">Hapus</button>`}</div>`]));document.querySelectorAll('[data-trash]').forEach(b=>b.onclick=()=>lifecycleDialog(products.find(p=>p.id===b.dataset.trash),true));document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>lifecycleDialog(products.find(p=>p.id===b.dataset.restore),false));}
 document.querySelectorAll('.filters input,.filters select').forEach(el=>el.oninput=()=>{filter[el.name]=el.value;if(el.name==='archive'){filter.status='';filter.publication='';document.querySelector('.filters [name=status]').value='';document.querySelector('.filters [name=publication]').value='';}paint();});paint();$('#export-products').onclick=()=>{const out=exportRows(rows());excel('Produk-Kubah-Nabawi.xlsx',out);};
 function editMovement(pid){const p=products.find(p=>p.id===pid),old=movements.get(pid);
 $('#movement-editor').innerHTML=form('movement-edit','<h2 class="full">'+esc(p.name)+'</h2>'+select('movementValue','Status pergerakan',movementOptions,movementStatus(old))+'<p class="full">Hanya penilaian internal yang disimpan. Harga dan stok tetap.</p>','Simpan status');
 $('#movement-editor').scrollIntoView({block:'nearest'});
 bindForm('movement-edit',async d=>{await movementService(U.store).save(U.ctx,{productId:pid,status:d.movementValue,expectedRevision:old?.revision||0});movements.set(pid,await U.store.get('productMovements/'+pid));paint();$('#movement-editor').innerHTML='';message('Status pergerakan tersimpan.');});
 }
 function lifecycleDialog(p,deleted){
  const dialog=document.createElement('dialog'),key=crypto.randomUUID();let pending=false;
  dialog.className='product-trash-dialog';dialog.setAttribute('aria-labelledby','product-trash-title');
  dialog.innerHTML=`<h2 id="product-trash-title">${deleted?'Hapus Produk':'Pulihkan Produk'}</h2><p><strong>${esc(p.name)}</strong><br>SKU: ${esc(p.sku||'Belum diisi')}</p><p>${deleted?'Produk beserta seluruh variannya akan disembunyikan dari katalog dan dipindahkan ke Sampah. Data produk, foto, stok, harga dan pesanan lama tetap tersimpan. Produk dapat dipulihkan. Edit formulir yang belum disimpan tidak ikut disimpan.':'Produk akan dipulihkan sebagai belum terbit. Stok terkini tetap digunakan; tidak ada stok yang ditambahkan kembali. Tinjau produk sebelum menerbitkannya.'}</p><p data-trash-error role="alert" class="notice error" hidden></p><div class="actions"><button type="button" data-cancel>Batal</button><button type="button" data-confirm class="${deleted?'danger':'primary'}">${deleted?'Pindahkan ke Sampah':'Pulihkan'}</button></div>`;
  document.body.append(dialog);dialog.showModal();const cancel=dialog.querySelector('[data-cancel]'),confirm=dialog.querySelector('[data-confirm]');cancel.focus();
  cancel.onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(pending)e.preventDefault();});dialog.addEventListener('close',()=>dialog.remove());
  confirm.onclick=async()=>{if(pending)return;pending=true;confirm.disabled=true;cancel.disabled=true;const notice=dialog.querySelector('[data-trash-error]');notice.hidden=true;
   try{const result=await productLifecycle(U.store).setTrashed(U.ctx,{productId:p.id,deleted,key,expectedTrashVersion:p.trashVersion||0});dialog.close();await U.render();message(result.deleted?'Produk dipindahkan ke Sampah dan disembunyikan dari katalog.':'Produk dipulihkan sebagai belum terbit. Tinjau sebelum menerbitkan.');}
   catch(error){notice.hidden=false;notice.textContent=error.message||'Penyimpanan gagal. Coba lagi.';}
   finally{pending=false;confirm.disabled=false;cancel.disabled=false;}
  };
 }
 function editor(old){if(old?.deleted){$('#product-body').innerHTML='<section class="panel"><h2>'+esc(old.name)+'</h2><p>SKU: '+esc(old.sku)+'</p><p>Produk berada di Sampah. Data seluruh varian, harga, stok, berat dan foto tetap tersimpan. Pulihkan produk sebelum mengeditnya.</p><button type="button" id="restore-product">Pulihkan</button></section>';$('#restore-product').onclick=()=>lifecycleDialog(old,false);return;}const draftId=old?.id||'new',drafts=productDrafts(sessionStorage,()=>U.c.a.currentUser?.uid,U.ctx.uid),recovered=drafts.read(draftId);const p=recovered?.origin||old||{},w=p.website||{},t=w.tiers?.[0]||{};let base=recovered?.base||(old?structuredClone(old):null),pendingAttempt=recovered?.pendingAttempt||null,saving=false;let variants=(p.variants||[{id:'V-'+crypto.randomUUID(),stock:0}]).map(v=>({...v}));
  $('#product-body').innerHTML=(old&&p.pricingVersion!==2?`<section class="panel"><h2>Tinjau harga lama</h2><p>Offline: ${money(p.priceOffline)} · Online: ${money(p.priceOnline)}. Tentukan sendiri harga yang benar di bawah. Cadangan lengkap dibuat saat menyimpan.</p></section>`:'')+form('product-edit',input('name','Nama produk',p.name||'','text','required maxlength="250"')+input('sku','SKU induk',p.sku||'','text','required maxlength="100"')+select('category','Kategori',[['','Pilih kategori'],...(p.category&&!CATEGORIES.includes(p.category)?[[p.category,p.category+' — perlu dipetakan']]:[]),...CATEGORIES],p.category)+input('subcategory','Subkategori',p.subcategory||'')+input('saleUnit','Satuan jual (misalnya pak)',p.saleUnit||(old?'':'pcs'),'text','required')+input('packPcs','Pcs per satuan jual',w.packPcs??(old?'':1),'number','min="1" required')+input('weight','Berat per satuan jual (gram)',p.weight||0,'number','min="0" required')+input('retail','Harga Eceran per satuan jual (Rp)',w.retail||'','number','min="1" required')+input('wholesale','Harga Grosir per satuan jual (opsional)',t.price||'','number','min="1"')+input('minPcs','Minimum Grosir (pcs)',t.minPcs||1,'number','min="1" required')+select('combine','Gabungkan minimum grosir',[['product','Varian dalam produk'],['variant','Masing-masing varian'],['all','Kelompok produk yang sama']],w.combine||'product')+input('group','Kode kelompok grosir',w.group||'')+input('resellerPrice','Harga reseller disetujui (opsional)',w.reseller?.price||'','number','min="1"')+input('resellerMin','Minimum reseller (pcs)',w.reseller?.minPcs||20,'number','min="1"')+select('status','Status publikasi',[['draft','Draft'],['aktif','Aktif dan terbit di katalog'],['nonaktif','Nonaktif']],p.status||'draft')+select('movementValue','Status pergerakan — internal admin',movementOptions,movementStatus(movements.get(p.id)))+checkbox('wholesaleCollection','Tampilkan dalam koleksi Paket Grosir',p.collections?.includes('paket-grosir'))+checkbox('promo','Ikut promo gratis ongkir (syarat 20 pcs tetap terpisah)',!!w.promo)+area('description','Deskripsi',p.description||'')+area('photos','URL foto HTTPS, satu per baris (maksimal 9)',imageList(p.images?.length?p.images:[{url:p.photoUrl}]).map(i=>i.url).filter(Boolean).join('\n'))+'<div id="variants" class="full"></div><div id="stock-conflict" class="full"></div>'+input('reason','Alasan pembaruan',old?'Perbarui produk / pemetaan harga':'Produk baru','text','required')+'<div class="full" id="price-preview"></div>'+checkbox('confirmed','Saya sudah memeriksa harga, kategori, varian, foto, dan status publikasi'),'Simpan produk & sinkronkan katalog');
  const f=$('#product-edit');f.noValidate=true;
  if(old){const b=document.createElement('button');b.type='button';b.className='danger product-trash-edit';b.textContent='Hapus Produk';b.onclick=()=>lifecycleDialog(old,true);f.append(b);}
  const tableDraft=mountVariantTable($('#variants'),{variants,parent:p,c:U.c,canEdit:U.ctx.role==='admin',onChange:()=>{f.dataset.dirty='true';persist();}});
  const collectVariants=()=>tableDraft.read();
  function draftProduct(d){return {...p,name:d.name,sku:d.sku,category:d.category,subcategory:d.subcategory,saleUnit:d.saleUnit,description:d.description,weight:Number(d.weight),status:d.status,photoUrl:d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)[0]||'',collections:f.elements.wholesaleCollection.checked?['paket-grosir']:[],images:d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,i)=>({url,isPrimary:i===0})),variants:collectVariants(),website:{...w,enabled:d.status==='aktif',retail:Number(d.retail),packPcs:Number(d.packPcs),tiers:d.wholesale?[{minPcs:Number(d.minPcs),price:Number(d.wholesale)},...(w.tiers||[]).slice(1)]:[],reseller:{price:Number(d.resellerPrice||0),minPcs:Number(d.resellerMin||20)},promo:f.elements.promo.checked,combine:d.combine,group:d.group}};}
  let formBaseline=recovered?.initial||draftProduct(Object.fromEntries(new FormData(f)));
  const status=document.createElement('p');status.className='notice full';status.setAttribute('role','status');status.setAttribute('aria-live','polite');f.prepend(status);
  const saveButton=f.querySelector('button.primary:not([type=button])');
  const readRaw=()=>({fields:Object.fromEntries([...f.elements].filter(el=>el.name&&el.type!=='file').map(el=>[el.name,el.type==='checkbox'?el.checked:el.value])),variants:tableDraft.snapshot(),queuedPhotos:tableDraft.queuedPhotos()});
  function restoreRaw(raw){for(const [name,value] of Object.entries(raw.fields||{})){const el=f.elements.namedItem(name);if(el){if(el.type==='checkbox')el.checked=!!value;else el.value=value??'';}}tableDraft.replace(raw.variants);}
  function persist(){if(!f.isConnected)return;const ok=drafts.write(draftId,{origin:p,base,initial:formBaseline,raw:readRaw(),pendingAttempt});if(!ok&&U.c.a.currentUser?.uid===U.ctx.uid){status.textContent='Draf tetap di formulir. Penyimpanan draf di tab ini tidak tersedia; jangan tutup tab sebelum berhasil menyimpan.';}}
  function writeModel(model){const x=model.website||{},tier=x.tiers?.[0]||{};const fields={name:model.name,sku:model.sku,category:model.category,subcategory:model.subcategory||'',saleUnit:model.saleUnit||'pcs',description:model.description||'',weight:model.weight??0,status:model.status,photos:imageList(model.images?.length?model.images:model.images===undefined?[{url:model.photoUrl}]:[]).map(i=>i.url).join('\n'),retail:x.retail,packPcs:x.packPcs,wholesale:tier.price??'',minPcs:tier.minPcs||1,combine:x.combine||'product',group:x.group||'',resellerPrice:x.reseller?.price||'',resellerMin:x.reseller?.minPcs||20,promo:!!x.promo,wholesaleCollection:model.collections?.includes('paket-grosir')};restoreRaw({fields,variants:model.variants});}
  const preview=()=>{const r=Number(f.elements.retail.value),pack=Number(f.elements.packPcs.value);tableDraft.updateParent({saleUnit:f.elements.saleUnit.value,packPcs:pack,retail:f.elements.retail.value,wholesale:f.elements.wholesale.value,weight:f.elements.weight.value});$('#price-preview').textContent=r>0&&pack>0?'Harga eceran '+money(r)+' / '+f.elements.saleUnit.value+' ('+pack+' pcs), setara '+money(r/pack)+' / pcs. Harga grosir berlaku mulai '+f.elements.minPcs.value+' pcs.':'Lengkapi Harga Eceran dan isi kemasan.';};
  if(recovered){restoreRaw(recovered.raw);f.elements.confirmed.checked=false;status.textContent='Draf akun Anda dipulihkan dari tab ini, termasuk referensi foto yang sudah terunggah. Tinjau lalu simpan. Pilih ulang berkas yang belum diunggah bila diperlukan.';}else status.textContent='Perubahan disimpan sebagai draf di tab ini sampai berhasil disimpan dan diperiksa di server.';
  f.addEventListener('input',()=>{f.dataset.dirty='true';preview();persist();});f.addEventListener('change',persist);preview();
  const errorText=e=>['auth/session-changed','unauthenticated','auth/user-token-expired'].includes(e.code)?'Sesi berakhir atau akun berubah. Masuk kembali dengan akun yang sama lalu buka produk ini untuk memulihkan draf.':String(e.code).includes('permission-denied')?'Akses penyimpanan ditolak. Periksa akun admin Anda. Draf tetap tersedia.':e.message||'Penyimpanan belum berhasil. Draf tetap tersedia untuk dicoba ulang.';
  function showConflicts(error,pid){
   const host=$('#stock-conflict');
   if(error.code==='stock-conflict'){
    host.innerHTML='<section class="notice error"><h3>Stok perlu ditinjau</h3>'+table(['Varian','Saat dibuka','Stok terbaru','Perubahan saya'],error.conflicts.map(x=>[esc(x.sku||x.id),x.previous,x.current,x.requested]))+'<p>Muat stok terbaru ke formulir. Harga dan edit lain dipertahankan; isi kembali stok akhir setelah ditinjau.</p><button type="button" id="review-latest-stock">Muat stok terbaru</button></section>';
    $('#review-latest-stock').onclick=e=>busy(e.currentTarget,async()=>{const latest=await U.store.get('products/'+pid);check(latest,'Produk tidak tersedia.');tableDraft.reviewStock(latest);base.revision=latest.revision||0;for(const v of base.variants){const current=latest.variants.find(x=>x.id===v.id);if(current){v.stock=current.stock;v.reserved=current.reserved||0;const initial=formBaseline.variants.find(x=>x.id===v.id);if(initial){initial.stock=current.stock;initial.reserved=current.reserved||0;}}}host.innerHTML='';persist();status.textContent='Stok terbaru dimuat. Tinjau kembali sebelum Simpan Produk.';});
   }else if(error.code==='product-conflict'&&error.conflicts?.length){
    const value=v=>v===undefined?'Belum diisi':typeof v==='object'?JSON.stringify(v,null,2):String(v);
    host.innerHTML='<section class="notice error"><h3>Tinjau perubahan pada kolom yang sama</h3><p>Tidak ada data ditimpa. Pilihan hanya berlaku untuk nilai yang sedang dibandingkan; perubahan baru tetap diperiksa saat menyimpan.</p>'+table(['Kolom','Perubahan saya','Data terbaru','Pilih penyelesaian'],error.conflicts.map((x,i)=>[esc(x.field),'<pre class="conflict-value">'+esc(value(x.requested))+'</pre>','<pre class="conflict-value">'+esc(value(x.current))+'</pre>','<select data-resolution="'+i+'" aria-label="Penyelesaian '+esc(x.field)+'"><option value="">Pilih…</option><option value="mine">Gunakan perubahan saya</option><option value="latest">Gunakan data terbaru</option></select>']))+'<button type="button" data-resolve>Terapkan pilihan ke draf</button></section>';
    host.querySelector('[data-resolve]').onclick=e=>busy(e.currentTarget,async()=>{let desired=applyFormChanges(base,formBaseline,draftProduct(Object.fromEntries(new FormData(f)))),nextBase=base;const selections=[...host.querySelectorAll('[data-resolution]')];check(selections.every(el=>el.value),'Pilih penyelesaian untuk setiap kolom.');for(const [i,x] of error.conflicts.entries()){const result=resolveProductConflict(nextBase,desired,x,selections[i].value);nextBase=result.base;desired=result.desired;}base=nextBase;writeModel(desired);host.innerHTML='';persist();status.textContent='Pilihan diterapkan ke draf. Tinjau lalu Simpan Produk.';});
   }
   if(host.textContent)host.scrollIntoView({block:'nearest'});
  }
  f.onsubmit=async event=>{
   event.preventDefault();if(saving)return;saving=true;$('#notice').hidden=true;
   let controls=[],disabled=[],attempt=pendingAttempt,committed=false;
   try{
    check(U.c.a.currentUser?.uid===U.ctx.uid,'Masuk kembali dengan akun yang sama untuk melanjutkan draf.','auth/session-changed');
    check(f.elements.confirmed.checked,'Tinjau rincian lalu centang konfirmasi.');
    const d=Object.fromEntries(new FormData(f)),pid=p.id||'P-'+skuId(d.sku);
    if(!attempt){if(!f.reportValidity())return;check(CATEGORIES.includes(d.category),'Petakan kategori lama ke kategori yang tersedia.');const prices=pricingInput(d),vs=collectVariants();check(!vs.some(v=>v.pricing.wholesale&&!prices.wholesale),'Isi harga grosir induk sebelum membuat harga grosir varian.');const photos=d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);check(photos.every(url=>/^https:\/\//.test(url)),'Foto harus URL HTTPS publik.');check(photos.length<=9,'Maksimal 9 foto.');}
    check(!tableDraft.pending(),'Tunggu pratinjau foto selesai.');
    controls=[...f.querySelectorAll('input,select,textarea,button')];disabled=controls.map(el=>el.disabled);controls.forEach(el=>el.disabled=true);tableDraft.setLocked(true);saveButton.textContent='Menyimpan…';status.textContent=attempt?'Memeriksa dan mencoba kembali penyimpanan sebelumnya…':'Menyimpan…';
    if(!attempt){await tableDraft.upload(pid);const entered=draftProduct(d);attempt={request:{id:pid,product:base?applyFormChanges(base,formBaseline,entered):entered,...(base?{base}:{}),...(d.movementValue!==movementStatus(movements.get(p.id))?{movement:{status:d.movementValue,expectedRevision:movements.get(p.id)?.revision||0}}:{}),expectedRevision:base?.revision||0,key:crypto.randomUUID(),stock:true,reason:d.reason},raw:readRaw()};pendingAttempt=attempt;persist();}
    const service=productService(U.store);await service.save(U.ctx,attempt.request);committed=true;
    const verified=await service.verify(U.ctx,attempt.request);
    if(!verified.catalogSynced){
     status.textContent='Produk sudah tersimpan, tetapi katalog terbaru belum konsisten. Gunakan Coba sinkronkan katalog; stok dan varian tidak disimpan ulang.';
     const retry=document.createElement('button');retry.type='button';retry.textContent='Coba sinkronkan katalog';retry.onclick=e=>busy(e.currentTarget,async()=>{await service.syncCatalog(U.ctx,verified.id);const latest=await service.verify(U.ctx,attempt.request);check(latest.catalogSynced,'Sinkronisasi belum terverifikasi. Coba lagi.');retry.remove();await finish(latest,attempt);});status.append(document.createElement('br'),retry);return;
    }
    await finish(verified,attempt);
   }catch(error){
    if(['product-conflict','stock-conflict','invalid-argument','failed-precondition'].includes(error.code)&&!committed)pendingAttempt=null;
    status.textContent=(committed?'Transaksi diterima server, tetapi pemeriksaan ulang belum selesai. Klik Simpan untuk memeriksa kembali tanpa menggandakan perubahan. ':'')+errorText(error);
    if(!committed&&pendingAttempt)status.textContent+=' Saat dicoba lagi, permintaan sebelumnya diperiksa dahulu; edit tambahan tetap menjadi draf.';
    showConflicts(error,attempt?.request.id||p.id);persist();
   }finally{saving=false;controls.forEach((el,i)=>el.disabled=disabled[i]);tableDraft.setLocked(false);saveButton.textContent='Simpan produk & sinkronkan katalog';}
  };
  async function finish(verified,attempt){
   // Keep edits made after an uncertain failure while rebasing to actual server values.
   const currentRaw=readRaw(),extras=!same(attempt.raw,currentRaw);
   const beforeFields=attempt.raw.fields;const changedFields=Object.fromEntries(Object.entries(currentRaw.fields).filter(([k,v])=>!same(v,beforeFields[k])));
   const remainingRows=applyFormChanges({variants:verified.product.variants},{variants:attempt.raw.variants},{variants:currentRaw.variants}).variants;
   base={...verified.product,id:verified.id};pendingAttempt=null;
   if(verified.movement)movements.set(verified.id,verified.movement);
   writeModel(base);f.elements.movementValue.value=movementStatus(verified.movement);formBaseline=draftProduct(Object.fromEntries([...f.elements].filter(el=>el.name).map(el=>[el.name,el.value])));
   if(extras)restoreRaw({fields:changedFields,variants:remainingRows});
   p.id=verified.id;drafts.remove(draftId);if(extras)persist();else tableDraft.markSaved();f.dataset.dirty=extras?'true':'false';$('#stock-conflict').innerHTML='';preview();
   status.textContent='Produk tersimpan dan katalog terverifikasi. ID '+verified.id+(extras?' Edit tambahan masih berupa draf; tinjau lalu simpan lagi.':' Anda dapat melanjutkan edit atau kembali ke Daftar Produk.');
   message('Produk tersimpan dan katalog terverifikasi.');
  }

 }
 function importer(){let preview=null,parsed=[];
  $('#product-body').innerHTML=`<section class="panel"><h2>Impor & sinkronisasi katalog</h2><p>Gunakan SKU induk dan SKU varian yang tetap. URL foto HTTPS dapat dipisahkan dengan tanda |. Foto tertanam di Excel dan upload foto massal belum didukung pada versi ini.</p><div class="actions"><button id="template-xlsx">Unduh template Excel</button><button id="template-csv">Unduh template CSV</button></div></section>`+form('import-preview',input('file','Berkas XLSX / CSV','','file','accept=".xlsx,.csv" required')+select('mode','Mode',[['add','Tambah produk baru'],['update','Tambah & perbarui SKU yang ada']])+checkbox('stock','Perbarui stok produk lama dari berkas (perlu pemeriksaan)'),'Baca & tampilkan pratinjau')+'<section id="import-result"></section>';
  const example=()=>[{sku:'CONTOH-SARUNG',name:'Sarung Contoh',category:'Sarung',subcategory:'',description:'Ganti data contoh sebelum impor',saleUnit:'pak',packPcs:10,weight:3000,retail:500000,wholesale:450000,minPcs:20,variantSku:'CONTOH-SARUNG-BIRU',color:'Biru',size:'Dewasa',variantRetail:'',variantWholesale:'',stock:0,status:'draft',photos:'',variantPhoto:'',hpp:''}];
  $('#template-xlsx').onclick=()=>{const a=document.createElement('a');a.href='Template-Produk-Kubah-Nabawi.xlsx';a.download='Template-Produk-Kubah-Nabawi.xlsx';a.click();};$('#template-csv').onclick=()=>download('Template-Produk-Kubah-Nabawi.csv',csv(example(),IMPORT_COLUMNS.map(key=>({key}))));
  bindForm('import-preview',async(d,f)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi.');const file=f.elements.file.files[0];check(file.size<=10*1024*1024,'Berkas impor maksimal 10 MB.');const book=XLSX.read(await file.arrayBuffer(),{type:'array'});parsed=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''});preview=importPreview(parsed,products,{mode:d.mode,stock:f.elements.stock.checked});const {plans,errors}=preview;
   $('#import-result').innerHTML='<div class="panel"><h2>Pratinjau perubahan</h2><p>'+plans.length+' produk valid · '+errors.length+' kesalahan. Tidak ada data tersimpan sebelum konfirmasi.</p>'+table(['Baris','SKU','Nama','Tindakan','Publikasi','Stok lama'],plans.map(p=>[p.row,esc(p.product.sku),esc(p.product.name),p.kind,esc(p.product.status),p.stock?'Akan diperbarui':'Dipertahankan']))+table(['Baris','SKU','Kesalahan'],errors.map(e=>[e.row,esc(e.sku),esc(e.error)]))+checkbox('applyConfirm','Saya menyetujui rincian ini, termasuk produk aktif yang akan terbit di katalog.')+'<button id="apply-import" class="primary" '+(errors.length||!plans.length?'disabled':'')+'>Terapkan impor</button><div id="import-progress" role="status"></div></div>';
   $('#apply-import').onclick=e=>busy(e.currentTarget,async()=>{check($('[name=applyConfirm]').checked,'Centang konfirmasi publikasi terlebih dahulu.');const results=[];for(const plan of plans){try{const r=await productService(U.store).save(U.ctx,plan);results.push({sku:plan.product.sku,id:r.id,status:r.reused?'Sudah tersimpan sebelumnya':'Berhasil',error:''});}catch(error){results.push({sku:plan.product.sku,id:plan.id,status:'Gagal',error:error.message});}$('#import-progress').textContent=`Memproses ${results.length}/${plans.length} produk…`;}
    $('#import-progress').innerHTML=table(['SKU','ID','Hasil','Keterangan'],results.map(r=>[esc(r.sku),esc(r.id),esc(r.status),esc(r.error)]))+'<button type="button" id="download-report">Unduh laporan impor</button><p>Muat ulang pratinjau sebelum memperbaiki produk yang gagal. Produk yang sudah berhasil tidak digandakan ketika berkas yang sama dicoba lagi.</p>';$('#download-report').onclick=()=>download('Hasil-Impor-Produk.csv',csv(results,['sku','id','status','error'].map(key=>({key}))));message(results.some(r=>r.status==='Gagal')?'Sebagian produk gagal. Periksa laporan.':'Seluruh produk pada pratinjau berhasil disimpan.',results.some(r=>r.status==='Gagal'));});
  });
 }
}
function exportRows(products){return products.flatMap(p=>(p.variants||[]).map(v=>({sku:p.sku,name:p.name,category:p.category,subcategory:p.subcategory||'',description:p.description||'',saleUnit:p.saleUnit||'unit',packPcs:p.website?.packPcs??'',weight:p.weight||0,retail:p.website?.retail||'',wholesale:p.website?.tiers?.[0]?.price||'',minPcs:p.website?.tiers?.[0]?.minPcs||1,variantSku:v.sku,color:v.color,size:v.size,variantRetail:v.pricing?.retail||'',variantWholesale:v.pricing?.wholesale||'',stock:v.stock,status:p.status,photos:(p.images||[]).map(i=>i.url).join('|'),variantPhoto:v.image||'',hpp:v.hpp??p.hpp??''})));}
export async function renderCalculator(U){const products=await U.store.list('products');if(!U.isCurrent())return;$('#content').innerHTML='<h1>Perbandingan Harga</h1><p>Perbandingan per satuan jual dan per pcs. Perhitungan tidak mengubah harga produk atau pesanan lama.</p>'+form('calculator',select('productId','Produk',products.filter(p=>p.website?.retail>0).map(p=>[p.id,p.name]))+select('variantId','Varian',[])+input('qty','Jumlah unit',1,'number','min="1" required')+select('mode','Mode',['eceran','grosir'])+checkbox('reseller','Gunakan harga reseller disetujui (simulasi kalkulator)'),'Hitung')+'<section class="panel" id="calculation"></section>';
 const change=()=>{const p=products.find(p=>p.id===$('[name=productId]').value);$('[name=variantId]').innerHTML=(p?.variants||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.sku+' '+(v.color||'')+' '+(v.size||''))}</option>`).join('');};$('[name=productId]').onchange=change;change();bindForm('calculator',(d,f)=>{const p=products.find(p=>p.id===d.productId);check(p,'Pilih produk yang harganya sudah ditetapkan.');const v=p.variants.find(v=>v.id===d.variantId),q=Number(d.qty),r=unitPrice(p,v,q,d.mode,f.elements.reseller.checked),hpp=v.hpp??p.hpp;$('#calculation').innerHTML=table(['Keterangan','Hasil'],[['Harga yang berlaku',esc(r.kind)],['Jumlah',q+' unit / '+r.pcs+' pcs'],['Harga per unit',money(r.price)],['Setara per pcs',money(r.perPcs)],['Total penjualan',money(r.price*q)],['HPP total',hpp==null?'Belum tersedia':money(hpp*q)],['Selisih sebelum biaya lain',hpp==null?'Belum tersedia':money((r.price-hpp)*q)]]);});}
