import {$,esc,money,input,area,select,checkbox,tabs,table,form,bindForm,busy,message,download} from './planning-ui.js?v=admin-lengkap-20260909-r2';
import {CATEGORIES,IMPORT_COLUMNS,IMPORT_LABELS,importPreview,pricingInput,skuId,csv,unitPrice} from './planning-domain.js?v=admin-lengkap-20260909-r2';
import {productService} from './product-service.js?v=admin-lengkap-20260909-r2';
import {check,num} from './manual-domain.js?v=admin-lengkap-20260909-r2';
let filter={query:'',category:'',status:''};
const excel=(name,rows)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi lalu coba lagi, atau gunakan CSV.');const sheet=XLSX.utils.json_to_sheet(rows.map(r=>Object.fromEntries(IMPORT_COLUMNS.map((k,i)=>[IMPORT_LABELS[i],r[k]??'']))),{header:IMPORT_LABELS}),book=XLSX.utils.book_new();sheet['!cols']=IMPORT_COLUMNS.map(k=>({wch:['name','description','photos'].includes(k)?36:20}));XLSX.utils.book_append_sheet(book,sheet,'Produk');XLSX.writeFile(book,name);};
export async function renderProducts(U){const products=await U.store.list('products');if(!U.isCurrent())return;const active=U.tab==='impor'?'impor':U.tab==='migrasi'?'migrasi':'daftar';
 $('#content').innerHTML=`<div class="page-head"><div><h1>Produk</h1><p>Harga Eceran/Grosir, stok, dan katalog pembeli dalam satu data produk.</p></div><a class="button primary" href="#products/new">Tambah produk</a></div>${tabs('products',[['','Daftar Produk'],['impor','Impor Excel'],['migrasi','Pemetaan Harga Lama']],active==='daftar'?'':active)}<div id="product-body"></div>`;
 if(U.tab&&!['impor','migrasi'].includes(U.tab)){editor(products.find(p=>p.id===U.tab)||null);return;}
 if(U.tab==='impor'){importer();return;}
 $('#product-body').innerHTML=(active==='migrasi'?'<p class="notice">Periksa tiap produk. Nilai Offline/Online disimpan dalam cadangan perubahan, tidak otomatis menjadi Eceran/Grosir. Harga pada pesanan lama tetap utuh.</p>':'')+`<div class="filters">${input('query','Cari nama / SKU',filter.query,'search')}${select('category','Kategori',[['','Semua kategori'],...CATEGORIES],filter.category)}${select('status','Status',[['','Semua status'],['aktif','Aktif'],['draft','Draft'],['nonaktif','Nonaktif']],filter.status)}<button id="export-products">Ekspor hasil filter</button></div><section class="panel" id="products-table"></section>`;
 function rows(){const q=filter.query.toLowerCase();return products.filter(p=>(active!=='migrasi'||p.pricingVersion!==2)&&(!filter.category||p.category===filter.category)&&(!filter.status||p.status===filter.status)&&(!q||[p.name,p.sku,...(p.variants||[]).map(v=>v.sku)].some(v=>String(v||'').toLowerCase().includes(q))));}
 function paint(){const list=rows();$('#products-table').innerHTML=`<p>${list.length} produk</p>`+table(['Produk / SKU','Kategori','Eceran / unit','Grosir / minimum','Stok / kemasan','Publikasi','Aksi'],list.map(p=>[esc(p.name)+'<br><small>'+esc(p.sku||'SKU perlu diisi')+'</small>',esc(p.category||'Belum dipetakan'),p.website?.retail?money(p.website.retail):'Belum ditetapkan',(p.website?.tiers||[]).map(t=>money(t.price)+' / '+t.minPcs+' pcs').join('<br>')||'Ikut harga eceran',`${p.totalStock??(p.variants||[]).reduce((s,v)=>s+v.stock,0)} unit<br>${p.website?.packPcs||1} pcs / unit`,esc(p.status)+(p.website?.enabled?' · katalog aktif':' · belum terbit')+(p.pricingVersion!==2?'<br><small>Perlu tinjau model harga</small>':''),`<a class="button" href="#products/${esc(p.id)}">Periksa & ubah</a>`]));}
 document.querySelectorAll('.filters input,.filters select').forEach(el=>el.oninput=()=>{filter[el.name]=el.value;paint();});paint();$('#export-products').onclick=()=>{const out=exportRows(rows());excel('Produk-Kubah-Nabawi.xlsx',out);};
 function editor(old){const p=old||{},w=p.website||{},t=w.tiers?.[0]||{},key=crypto.randomUUID();let variants=(p.variants||[{id:'V-'+crypto.randomUUID(),stock:0}]).map(v=>({...v}));
  $('#product-body').innerHTML=(old&&p.pricingVersion!==2?`<section class="panel"><h2>Tinjau harga lama</h2><p>Offline: ${money(p.priceOffline)} · Online: ${money(p.priceOnline)}. Tentukan sendiri harga yang benar di bawah. Cadangan lengkap dibuat saat menyimpan.</p></section>`:'')+form('product-edit',input('name','Nama produk',p.name||'','text','required maxlength="250"')+input('sku','SKU induk',p.sku||'','text','required maxlength="100"')+select('category','Kategori',[['','Pilih kategori'],...(p.category&&!CATEGORIES.includes(p.category)?[[p.category,p.category+' — perlu dipetakan']]:[]),...CATEGORIES],p.category)+input('subcategory','Subkategori',p.subcategory||'')+input('saleUnit','Satuan jual (misalnya pak)',p.saleUnit||'pcs','text','required')+input('packPcs','Pcs per satuan jual',w.packPcs||1,'number','min="1" required')+input('weight','Berat per satuan jual (gram)',p.weight||0,'number','min="0" required')+input('retail','Harga Eceran per satuan jual (Rp)',w.retail||'','number','min="1" required')+input('wholesale','Harga Grosir per satuan jual (opsional)',t.price||'','number','min="1"')+input('minPcs','Minimum Grosir (pcs)',t.minPcs||1,'number','min="1" required')+select('combine','Gabungkan minimum grosir',[['product','Varian dalam produk'],['variant','Masing-masing varian'],['all','Kelompok produk yang sama']],w.combine||'product')+input('group','Kode kelompok grosir',w.group||'')+input('resellerPrice','Harga reseller disetujui (opsional)',w.reseller?.price||'','number','min="1"')+input('resellerMin','Minimum reseller (pcs)',w.reseller?.minPcs||20,'number','min="1"')+select('status','Status publikasi',[['draft','Draft'],['aktif','Aktif dan terbit di katalog'],['nonaktif','Nonaktif']],p.status||'draft')+checkbox('wholesaleCollection','Tampilkan dalam koleksi Paket Grosir',p.collections?.includes('paket-grosir'))+checkbox('promo','Ikut promo gratis ongkir (syarat 20 pcs tetap terpisah)',!!w.promo)+area('description','Deskripsi',p.description||'')+area('photos','URL foto HTTPS, satu per baris (maksimal 9)',(p.images?.length?p.images:[{url:p.photoUrl}]).map(i=>i.url).filter(Boolean).join('\n'))+'<div id="variants" class="full"></div><button type="button" id="add-variant">Tambah varian</button><div class="full">'+checkbox('stockUpdate','Saya ingin mengubah stok sesuai angka pada formulir',!old)+'</div>'+input('reason','Alasan pembaruan',old?'Perbarui produk / pemetaan harga':'Produk baru','text','required')+'<div class="full" id="price-preview"></div>'+checkbox('confirmed','Saya sudah memeriksa harga, kategori, varian, foto, dan status publikasi'),'Simpan produk & sinkronkan katalog');
  function paintVariants(){const box=$('#variants');box.innerHTML='<h2>Varian & stok</h2><p class="muted">Harga varian kosong mengikuti harga induk. Stok adalah jumlah satuan jual, bukan jumlah pcs. Varian lama tidak dihapus oleh impor.</p>'+variants.map((v,i)=>`<div class="variant-row form-grid" data-var="${i}">${input('v_sku','SKU varian',v.sku||'','text','required')}${input('v_color','Warna',v.color||v.name||'')}${input('v_size','Ukuran',v.size||'')}${input('v_stock','Stok unit',v.stock||0,'number','min="0" required')}${input('v_retail','Eceran varian (opsional)',v.pricing?.retail||'','number','min="1"')}${input('v_wholesale','Grosir varian (opsional)',v.pricing?.wholesale||'','number','min="1"')}${input('v_hpp','HPP per unit — hanya admin',v.hpp??p.hpp??'','number','min="0"')}${input('v_image','URL foto varian HTTPS',v.image||'','url')}</div>`).join('');}
  function collectVariants(){return [...document.querySelectorAll('[data-var]')].map(el=>{const v=variants[Number(el.dataset.var)],get=n=>el.querySelector('[name="v_'+n+'"]').value;return {...v,sku:get('sku'),color:get('color'),size:get('size'),stock:Number(get('stock')),hpp:get('hpp')===''?null:Number(get('hpp')),image:get('image'),pricing:{retail:get('retail')?Number(get('retail')):null,wholesale:get('wholesale')?Number(get('wholesale')):null}};});}
  paintVariants();$('#add-variant').onclick=()=>{variants=collectVariants();variants.push({id:'V-'+crypto.randomUUID(),stock:0});paintVariants();};
  const preview=()=>{const f=$('#product-edit'),r=Number(f.elements.retail.value),pack=Number(f.elements.packPcs.value);$('#price-preview').textContent=r>0&&pack>0?`Harga eceran ${money(r)} / ${f.elements.saleUnit.value} (${pack} pcs), setara ${money(r/pack)} / pcs. Harga grosir berlaku mulai ${f.elements.minPcs.value} pcs.`:'Lengkapi Harga Eceran dan isi kemasan.';};$('#product-edit').addEventListener('input',preview);preview();
  bindForm('product-edit',async(d,f)=>{check(f.elements.confirmed.checked,'Tinjau rincian lalu centang konfirmasi.');check(CATEGORIES.includes(d.category),'Petakan kategori lama ke kategori yang tersedia.');const prices=pricingInput(d),vs=collectVariants();check(!vs.some(v=>v.pricing.wholesale&&!prices.wholesale),'Isi harga grosir induk sebelum membuat harga grosir varian.');const images=d.photos.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,i)=>{check(/^https:\/\//.test(url),'Foto harus URL HTTPS publik.');return {url,isPrimary:i===0};});check(images.length<=9,'Maksimal 9 foto.');
   const product={...p,name:d.name,sku:d.sku,category:d.category,subcategory:d.subcategory,saleUnit:d.saleUnit,description:d.description,weight:Number(d.weight),status:d.status,collections:f.elements.wholesaleCollection.checked?['paket-grosir']:[],images,variants:vs,website:{...w,enabled:d.status==='aktif',retail:prices.retail,packPcs:prices.packPcs,tiers:prices.wholesale?[{minPcs:prices.minPcs,price:prices.wholesale},...(w.tiers||[]).slice(1)]:[],reseller:{price:Number(d.resellerPrice||0),minPcs:Number(d.resellerMin||20)},promo:f.elements.promo.checked,combine:d.combine,group:d.group}};
   const result=await productService(U.store).save(U.ctx,{id:p.id||'P-'+skuId(d.sku),product,expectedRevision:p.revision||0,key,stock:f.elements.stockUpdate.checked,reason:d.reason});location.hash='products';if(U.tab==='')await U.render();message('Produk tersimpan. Publikasi katalog mengikuti status yang dipilih. ID '+result.id);});
 }
 function importer(){let preview=null,parsed=[];
  $('#product-body').innerHTML=`<section class="panel"><h2>Impor & sinkronisasi katalog</h2><p>Gunakan SKU induk dan SKU varian yang tetap. URL foto HTTPS dapat dipisahkan dengan tanda |. Foto tertanam di Excel dan upload foto massal belum didukung pada versi ini.</p><div class="actions"><button id="template-xlsx">Unduh template Excel</button><button id="template-csv">Unduh template CSV</button></div></section>`+form('import-preview',input('file','Berkas XLSX / CSV','','file','accept=".xlsx,.csv" required')+select('mode','Mode',[['add','Tambah produk baru'],['update','Tambah & perbarui SKU yang ada']])+checkbox('stock','Perbarui stok produk lama dari berkas (perlu pemeriksaan)'),'Baca & tampilkan pratinjau')+'<section id="import-result"></section>';
  const example=()=>[{sku:'CONTOH-SARUNG',name:'Sarung Contoh',category:'Sarung',subcategory:'',description:'Ganti data contoh sebelum impor',saleUnit:'pak',packPcs:10,weight:3000,retail:500000,wholesale:450000,minPcs:20,variantSku:'CONTOH-SARUNG-BIRU',color:'Biru',size:'Dewasa',variantRetail:'',variantWholesale:'',stock:0,status:'draft',photos:'',variantPhoto:'',hpp:''}];
  $('#template-xlsx').onclick=()=>{const a=document.createElement('a');a.href='Template-Produk-Kubah-Nabawi.xlsx';a.download='Template-Produk-Kubah-Nabawi.xlsx';a.click();};$('#template-csv').onclick=()=>download('Template-Produk-Kubah-Nabawi.csv',csv(example(),IMPORT_COLUMNS.map(key=>({key}))));
  bindForm('import-preview',async(d,f)=>{check(globalThis.XLSX,'Pustaka Excel belum termuat. Periksa koneksi.');const file=f.elements.file.files[0];check(file.size<=10*1024*1024,'Berkas impor maksimal 10 MB.');const book=XLSX.read(await file.arrayBuffer(),{type:'array'});parsed=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''});preview=importPreview(parsed,products,{mode:d.mode,stock:f.elements.stock.checked});const {plans,errors}=preview;
   $('#import-result').innerHTML='<div class="panel"><h2>Pratinjau perubahan</h2><p>'+plans.length+' produk valid · '+errors.length+' kesalahan. Tidak ada data tersimpan sebelum konfirmasi.</p>'+table(['Baris','SKU','Nama','Tindakan','Publikasi','Stok lama'],plans.map(p=>[p.row,esc(p.product.sku),esc(p.product.name),p.kind,esc(p.product.status),p.stock?'Akan diperbarui':'Dipertahankan']))+table(['Baris','SKU','Kesalahan'],errors.map(e=>[e.row,esc(e.sku),esc(e.error)]))+checkbox('applyConfirm','Saya menyetujui rincian ini, termasuk produk aktif yang akan terbit di katalog.')+'<button id="apply-import" class="primary" '+(errors.length||!plans.length?'disabled':'')+'>Terapkan impor</button><div id="import-progress" role="status"></div></div>';
   $('#apply-import').onclick=e=>busy(e.currentTarget,async()=>{check($('[name=applyConfirm]').checked,'Centang konfirmasi publikasi terlebih dahulu.');const results=[];for(const plan of plans){try{const r=await productService(U.store).save(U.ctx,plan);results.push({sku:plan.product.sku,id:r.id,status:r.reused?'Sudah tersimpan sebelumnya':'Berhasil',error:''});}catch(error){results.push({sku:plan.product.sku,id:plan.id,status:'Gagal',error:error.message});}$('#import-progress').textContent=`Memproses ${results.length}/${plans.length} produk…`;}
    $('#import-progress').innerHTML=table(['SKU','ID','Hasil','Keterangan'],results.map(r=>[esc(r.sku),esc(r.id),esc(r.status),esc(r.error)]))+'<button type="button" id="download-report">Unduh laporan impor</button><p>Muat ulang pratinjau sebelum memperbaiki produk yang gagal. Produk yang sudah berhasil tidak digandakan ketika berkas yang sama dicoba lagi.</p>';$('#download-report').onclick=()=>download('Hasil-Impor-Produk.csv',csv(results,['sku','id','status','error'].map(key=>({key}))));message(results.some(r=>r.status==='Gagal')?'Sebagian produk gagal. Periksa laporan.':'Seluruh produk pada pratinjau berhasil disimpan.',results.some(r=>r.status==='Gagal'));});
  });
 }
}
function exportRows(products){return products.flatMap(p=>(p.variants||[]).map(v=>({sku:p.sku,name:p.name,category:p.category,subcategory:p.subcategory||'',description:p.description||'',saleUnit:p.saleUnit||'unit',packPcs:p.website?.packPcs||1,weight:p.weight||0,retail:p.website?.retail||'',wholesale:p.website?.tiers?.[0]?.price||'',minPcs:p.website?.tiers?.[0]?.minPcs||1,variantSku:v.sku,color:v.color,size:v.size,variantRetail:v.pricing?.retail||'',variantWholesale:v.pricing?.wholesale||'',stock:v.stock,status:p.status,photos:(p.images||[]).map(i=>i.url).join('|'),variantPhoto:v.image||'',hpp:v.hpp??p.hpp??''})));}
export async function renderCalculator(U){const products=await U.store.list('products');if(!U.isCurrent())return;$('#content').innerHTML='<h1>Kalkulator Harga</h1><p>Perbandingan per satuan jual dan per pcs. Perhitungan tidak mengubah harga produk atau pesanan lama.</p>'+form('calculator',select('productId','Produk',products.filter(p=>p.website?.retail>0).map(p=>[p.id,p.name]))+select('variantId','Varian',[])+input('qty','Jumlah unit',1,'number','min="1" required')+select('mode','Mode',['eceran','grosir'])+checkbox('reseller','Gunakan harga reseller disetujui (simulasi kalkulator)'),'Hitung')+'<section class="panel" id="calculation"></section>';
 const change=()=>{const p=products.find(p=>p.id===$('[name=productId]').value);$('[name=variantId]').innerHTML=(p?.variants||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.sku+' '+(v.color||'')+' '+(v.size||''))}</option>`).join('');};$('[name=productId]').onchange=change;change();bindForm('calculator',(d,f)=>{const p=products.find(p=>p.id===d.productId);check(p,'Pilih produk yang harganya sudah ditetapkan.');const v=p.variants.find(v=>v.id===d.variantId),q=Number(d.qty),r=unitPrice(p,v,q,d.mode,f.elements.reseller.checked),hpp=v.hpp??p.hpp;$('#calculation').innerHTML=table(['Keterangan','Hasil'],[['Harga yang berlaku',esc(r.kind)],['Jumlah',q+' unit / '+r.pcs+' pcs'],['Harga per unit',money(r.price)],['Setara per pcs',money(r.perPcs)],['Total penjualan',money(r.price*q)],['HPP total',hpp==null?'Belum tersedia':money(hpp*q)],['Selisih sebelum biaya lain',hpp==null?'Belum tersedia':money((r.price-hpp)*q)]]);});}
