import {returnPolicyHTML,retentionPolicyHTML} from './return-domain.js?v=kebijakan-20260913-r9';
import {connect,withDeadline,esc,date,message,busy} from './shop-client.js?v=kebijakan-20260913-r9';
import {manualStore} from './manual-store.js?v=admin-supplier-20260909-r3';
import {PROGRAMS,customerMessages,messagePayload,messageNumber,MESSAGE_STATUS} from './customer-message-service.js?v=katalog-pembeli-20260909-r7';

export const MAP_URL='https://maps.app.goo.gl/YEehCmwGr1Sjg6re6?g_st=ic';
export const STORE_NAME='Kubah Nabawi Store';
export const PROFILE='Kubah Nabawi Store dikelola oleh PT Raudah Artha Mandiri dan melayani pembelian eceran maupun grosir untuk kebutuhan perlengkapan ibadah, busana muslim, serta oleh-oleh. Kami melayani kebutuhan pribadi, reseller, toko fashion muslim, serta pengadaan untuk lembaga dan acara.';
export const CONTACT={phone:'085843713080',email:'kubahnabawiofficialshop@gmail.com',address:'Pademonegoro, Sukodono, Sidoarjo, Jawa Timur.'};
export const CATEGORY_NAMES=['Sajadah','Sarung','Atasan Pria','Mukenah & Atasan Wanita','Aksesoris & Songkok','Parfum','Makanan & Minuman'];
const icon=(path)=>`<svg class="info-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
const icons=['M3 8h18v13H3zM3 8l3-5h12l3 5M8 8v13M16 8v13','M4 21V6l8-4 8 4v15M4 8l8 4 8-4M12 12v9','M3 8h18v4H3zM5 12v9h14v-9M12 8v13M12 8C4 8 6 0 10 4l2 4zm0 0c8 0 6-8 2-4z','M8 3l-6 5 4 4 2-2v11h8V10l2 2 4-4-6-5-4 2z','M2 12l8-2V4a2 2 0 0 1 4 0v6l8 2v3l-8-1v5l3 2H7l3-2v-5l-8 1z','M3 21h18M5 21V10h14v11M8 10V7l4-4 4 4v3M10 21v-6h4v6','M3 8h18v13H3zM12 8v13M2 8l10-5 10 5','M3 21V9l9-7 9 7v12M8 21v-8h8v8','M2 8l5-4 5 2 5-2 5 4-5 12-5-2-5 2zM7 6l5 4 4-2M8 13l6 5'];
export function mapsButton(){return `<a class="button primary" href="${MAP_URL}" target="_blank" rel="noopener">Buka Google Maps ↗</a>`;}
export function footerHTML(year=new Date().getFullYear()){
  return `<div class="footer-groups"><section class="footer-profile"><h2>Profil Kubah Nabawi Store</h2><p>${PROFILE}</p><a href="informasi.html?v=kebijakan-20260913-r9#profil">Tentang toko →</a></section><section><h2>Tautan Langsung</h2><ul>${[['toko.html?v=kebijakan-20260913-r9#katalog','Beranda'],['toko.html?v=kebijakan-20260913-r9#katalog','Semua Produk'],['toko.html?v=kebijakan-20260913-r9#pesanan','Pesanan Saya'],['toko.html?v=kebijakan-20260913-r9#akun','Akun Saya'],['informasi.html?v=kebijakan-20260913-r9#kerjasama','Kerja Sama'],['informasi.html?v=kebijakan-20260913-r9#kontak','Hubungi Kami']].map(([url,t])=>`<li><a href="${url}">${t}</a></li>`).join('')}<li><a href="kurir.html?v=kebijakan-20260913-r9">Kurir toko</a></li></ul></section><section><h2>Kategori Produk</h2><ul>${CATEGORY_NAMES.map(c=>`<li><a href="toko.html?v=kebijakan-20260913-r9#katalog/${encodeURIComponent(c)}">${esc(c)}</a></li>`).join('')}</ul></section><section><h2>Hubungi Kami</h2><ul><li><a href="https://wa.me/6285843713080" target="_blank" rel="noopener">WhatsApp ${CONTACT.phone}</a></li><li><a href="mailto:${CONTACT.email}">${CONTACT.email}</a></li><li>${CONTACT.address}</li></ul></section><section><h2>Kerja Sama</h2><p>Untuk kebutuhan usaha, lembaga, acara, dan pemasok.</p><a href="informasi.html?v=kebijakan-20260913-r9#kerjasama">Lihat semua program →</a></section></div><section class="warehouse" aria-labelledby="warehouse-title"><div><p class="eyebrow">KUNJUNGI LOKASI KAMI</p><h2 id="warehouse-title">Warehouse Kubah Nabawi</h2><p>${CONTACT.address}</p>${mapsButton()}</div><figure><a href="${MAP_URL}" target="_blank" rel="noopener"><img src="warehouse-qr.png?v=informasi-katalog-20260909-r6" width="200" height="200" alt="QR lokasi Warehouse Kubah Nabawi di Google Maps"></a><figcaption>Pindai untuk melihat lokasi gudang</figcaption></figure></section><div class="footer-bottom"><p>© <span id="copyright-year">${year}</span> ${STORE_NAME}</p><nav aria-label="Kebijakan toko"><a href="informasi.html?v=kebijakan-20260913-r9#syarat">Syarat dan Ketentuan</a><a href="informasi.html?v=kebijakan-20260913-r9#privasi">Kebijakan Privasi</a><a href="informasi.html?v=kebijakan-20260913-r9#retur">Penukaran dan Pengembalian</a></nav></div>`;
}
export function programsHTML(){const cards=[['reseller','Reseller','Untuk mitra yang membeli produk Kubah Nabawi untuk dijual kembali.','toko.html?v=kebijakan-20260913-r9#reseller','Daftar reseller'],...PROGRAMS.map(([id,title,description])=>[id,title,description,'#pengajuan/'+id,'Ajukan kebutuhan']),['supplier','Menjadi Supplier / Pemasok','Untuk usaha atau produsen yang menawarkan barang agar dipasok ke toko Kubah Nabawi.','toko.html?v=kebijakan-20260913-r9#kerjasama','Ajukan penawaran']];return `<p class="eyebrow">TUMBUH BERSAMA</p><h1>Kerja Sama dengan Kubah Nabawi</h1><p class="info-intro">Pilih program sesuai kebutuhan Anda. Setiap pengajuan ditinjau tim toko sebelum kesepakatan dibuat.</p><div class="program-grid">${cards.map(([id,title,description,href,cta],i)=>`<article class="program-card">${icon(icons[i])}<h2>${title}</h2><p>${description}</p><a class="button ${id==='supplier'?'primary':''}" href="${href}">${cta} →</a></article>`).join('')}</div>`;}
const field=(name,label,type='text',max=150,required=false)=>`<label class="field">${label}<input name="${name}" type="${type}" maxlength="${max}" ${required?'required':''}></label>`;
function requestForm(program='contact'){
  const general=program==='contact';return `<section class="panel"><h2>${general?'Kirim pesan ke toko':'Formulir kebutuhan kerja sama'}</h2><p>Gunakan akun toko yang sama untuk menyimpan pesan dan melihat tindak lanjut. <a href="toko.html?v=kebijakan-20260913-r9#akun" target="_blank" rel="noopener">Masuk / daftar akun toko ↗</a></p><form id="customer-message"><input type="hidden" name="program" value="${program}"><div class="form-grid">${field('name','Nama','text',150,true)}${!general?field('business','Nama usaha / lembaga (opsional)'):''}${field('phone','WhatsApp','tel',30,true)}${field('email','Email (opsional)','email')}${general?field('topic','Topik','text',200,true):field('city','Kota','text',150,true)+field('needs','Produk / kebutuhan','text',1500,true)+field('quantity','Perkiraan jumlah dan satuan','text',150,true)+field('neededDate','Tanggal kebutuhan (opsional)','date',10)+field('budget','Anggaran (opsional)','text',150)}<label class="field wide">${general?'Pesan':'Catatan kebutuhan'}<textarea name="message" required maxlength="3000"></textarea></label></div><p class="meta">Data kontak digunakan untuk menindaklanjuti pesan ini. <a href="#privasi">Lihat informasi privasi</a>.</p><button class="primary" type="submit">Simpan dan kirim ke toko</button><p id="send-result" role="status"></p></form><details><summary>Pesan Saya</summary><button id="my-messages">Muat pesan tersimpan</button><div id="message-history"></div></details></section>`;
}
export function pageHTML(page,id){
  if(page==='kerjasama')return programsHTML();
  if(page==='pengajuan'){const p=PROGRAMS.find(([key])=>key===id);return p?`<a href="#kerjasama">← Semua program</a><h1>${p[1]}</h1><p>${p[2]}</p>${requestForm(id)}`:'<h1>Program tidak ditemukan</h1><a href="#kerjasama">Lihat program kerja sama</a>';}
  if(page==='kontak')return `<p class="eyebrow">KAMI SIAP MENDENGAR</p><h1>Hubungi Kami</h1><div class="contact-grid"><section class="panel">${icon('M5 2h4l2 5-3 2a14 14 0 0 0 7 7l2-3 5 2v4c-10 4-23-9-17-17')}<h2>WhatsApp & telepon</h2><p>${CONTACT.phone}</p><a class="button primary" href="https://wa.me/6285843713080" target="_blank" rel="noopener">Buka WhatsApp ↗</a> <a class="button" href="tel:+6285843713080">Telepon</a></section><section class="panel">${icon('M2 4h20v16H2zM2 5l10 8L22 5')}<h2>Email layanan pelanggan</h2><a href="mailto:${CONTACT.email}">${CONTACT.email}</a></section><section class="panel">${icon('M12 22s8-8 8-14a8 8 0 1 0-16 0c0 6 8 14 8 14zM9 8a3 3 0 1 0 6 0 3 3 0 1 0-6 0')}<h2>Warehouse Kubah Nabawi</h2><p>${CONTACT.address}</p>${mapsButton()}</section></div>${requestForm()}`;
  if(page==='syarat')return '<article class="policy panel"><h1>Syarat dan Ketentuan</h1><h2>Proses pemesanan</h2><p>Pilih produk, varian, jumlah, dan satuan dengan teliti. Harga eceran atau grosir mengikuti data produk serta minimum pembelian yang ditampilkan. Pengajuan pesanan diperiksa admin untuk harga, stok, pengiriman, dan jadwal sebelum total akhir dikonfirmasi.</p><h2>Pembayaran dan pengiriman</h2><p>Transfer manual memerlukan pemeriksaan dana masuk oleh admin. Mengirim bukti transfer tidak otomatis membuat pesanan Lunas. Ongkir yang belum ditentukan berstatus Menunggu Konfirmasi Ongkir. Promo kurir toko berlaku setelah kelayakan produk peserta, minimal 20 pcs, dan rute jalan maksimal 25 km diperiksa.</p><h2>Pengajuan kerja sama</h2><p>Pengajuan kebutuhan dan penawaran Supplier ditinjau toko. Pengajuan bukan persetujuan otomatis, pesanan pembelian, atau pemberian akses admin.</p><p class="notice">Ketentuan retur, penukaran, dan refund tersedia pada <a href="#retur">Kebijakan Retur</a>. Hak konsumen tetap dihormati. Hubungi admin sebelum mengirim barang kembali.</p><a href="#kontak">Hubungi Kami →</a></article>';
  if(page==='privasi')return '<article class="policy panel"><h1>Kebijakan Privasi</h1><h2>Informasi yang digunakan</h2><p>Informasi akun, nama, kontak, alamat, rincian pesanan, serta isi pengajuan digunakan untuk layanan akun, pembelian, pengiriman, dan tindak lanjut pesan. Isi hanya informasi yang diperlukan; jangan menulis password atau data pembayaran rahasia dalam formulir kontak.</p><h2>Akses dan penyimpanan</h2><p>Akun dan data aplikasi menggunakan Firebase. Dokumen yang diunggah pada fitur dokumen privat menggunakan Supabase. Pesan kontak dan pengajuan umum dapat dibaca pengirim serta admin yang berwenang. Data yang diperlukan untuk pengiriman diperiksa petugas terkait.</p><h2>Koreksi dan pertanyaan</h2><p>Untuk pertanyaan penggunaan data atau permintaan koreksi/penghapusan, hubungi layanan pelanggan. Permintaan akan diperiksa sesuai data dan proses toko yang terkait.</p><h2>Masa penyimpanan data</h2>' + retentionPolicyHTML() + '<p>Dokumen digunakan sesuai tujuan layanan dan kewajiban hukum. Akses dokumen pembeli hanya pemilik pesanan dan admin berwenang. Penerapan masa simpan tidak menjalankan penghapusan otomatis.</p><a href="#kontak">Hubungi Kami →</a></article>';
  if(page==='retur')return returnPolicyHTML();
  return `<section class="profile-hero"><p class="eyebrow">TENTANG KAMI</p><h1>${STORE_NAME}</h1><p class="info-intro">${PROFILE}</p><div class="actions"><a class="button primary" href="toko.html?v=kebijakan-20260913-r9#katalog">Lihat produk →</a><a class="button" href="#kerjasama">Pilihan kerja sama</a></div></section><div class="contact-grid"><section class="panel"><h2>Eceran & grosir</h2><p>Pilih jumlah dan satuan sesuai kebutuhan. Harga dan minimum grosir ditampilkan pada produk yang tersedia.</p></section><section class="panel"><h2>Kebutuhan usaha & acara</h2><p>Sampaikan kebutuhan kepada tim toko melalui program kerja sama yang sesuai.</p></section><section class="panel"><h2>Lokasi gudang</h2><p>${CONTACT.address}</p>${mapsButton()}</section></div>`;
}
async function session(){const c=await connect();await withDeadline(c.a.authStateReady(),15000);if(!c.a.currentUser)throw Error('Masuk ke akun toko pada tautan di atas, lalu coba kirim kembali. Pesan belum dikirim.');return {c,uid:c.a.currentUser.uid,store:manualStore(c)};}
function bindMessage(){
  const form=document.getElementById('customer-message');if(!form)return;
  let pending=null;
  form.onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const values=messagePayload(Object.fromEntries(new FormData(form)));if(pending&&JSON.stringify(values)!==JSON.stringify(pending.values))throw Error('Isi berubah setelah percobaan kirim. Periksa Pesan Saya, lalu muat ulang untuk membuat pesan berbeda.');
    const {c,uid,store}=await session();pending??={key:crypto.randomUUID(),values};const r=await withDeadline(customerMessages(store,{stamp:()=>c.fs.serverTimestamp()}).submit(uid,pending.values,pending.key),30000);form.innerHTML=`<p class="notice" role="status">Pesan ${esc(r.number)} berhasil tersimpan untuk ditinjau toko.</p><a class="button" href="#kontak">Hubungi Kami</a>`;message('Pesan '+r.number+' tersimpan.');});};
  document.getElementById('my-messages').onclick=e=>busy(e.currentTarget,async()=>{const {uid,store}=await session(),rows=await withDeadline(store.list('customerMessages',[['customerId','==',uid]]),15000);document.getElementById('message-history').innerHTML=rows.map(r=>`<article class="panel"><strong>${esc(messageNumber(r.id))}</strong><p>${date(r.createdAt)} · ${esc(MESSAGE_STATUS[r.status])}</p><p>${esc(r.payload.topic||PROGRAMS.find(([k])=>k===r.payload.program)?.[1]||'Pesan')}</p><p>${esc(r.reviewNote||'Menunggu pemeriksaan toko.')}</p></article>`).join('')||'<p>Belum ada pesan tersimpan pada akun ini.</p>';});
}
if(typeof document!=='undefined'){
  const year=document.getElementById('copyright-year');if(year)year.textContent=new Date().getFullYear();
  if(document.body.dataset.publicInfo){const render=()=>{const [page='profil',id]=location.hash.slice(1).split('/');document.getElementById('notice').hidden=true;document.getElementById('content').innerHTML=pageHTML(page,id);bindMessage();};window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();}
}
