import {connect,login,logout,ensureAdminAccess,api,esc,money} from './shop-client.js?v=katalog-penawaran-20260909-r4';
import {manualStore} from './manual-store.js?v=admin-supplier-20260909-r3';
import {resellerService,totals,need} from './reseller-service.js?v=admin-supplier-20260909-r3';
import {prepareDocument,documentStorage,storageConfiguration} from './document-storage.js?v=admin-supplier-20260909-r3';
const adminPage=document.body.dataset.audience==='admin',root=document.getElementById('reseller-content');
const $=s=>document.querySelector(s),today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const tabs=adminPage?[['ringkasan','Ringkasan'],['data','Data Reseller'],['pendaftaran','Pendaftaran'],['resi','Resi & Pengiriman'],['pembayaran','Pembayaran']]:[['ringkasan','Ringkasan'],['resi','Resi & Pengiriman'],['pembayaran','Pembayaran']];
const status=v=>({pending:'Menunggu Pemeriksaan',approved:'Disetujui',correction:'Perlu Perbaikan',menunggu:'Menunggu',disetujui:'Aktif',ditolak:'Ditolak',dinonaktifkan:'Nonaktif'}[v]||v);
let c,store,core,storage,ctx=null,tab='ringkasan',data={resellers:[],orders:[],cases:[],revisions:[],reviews:[],banks:[]},urls=new Set(),generation=0;
function notice(text,error=false){$('#notice').textContent=text;$('#notice').className=error?'notice error':'notice';$('#notice').hidden=!text;if(error&&$('#document-dialog').open){let box=$('#dialog-message');if(!box){box=document.createElement('p');box.id='dialog-message';box.setAttribute('role','alert');$('#dialog-content').prepend(box);}box.className='notice error';box.textContent=text;}}
function safeURL(blob){const u=URL.createObjectURL(blob);urls.add(u);return u;}
function clearPrivate(){generation++;for(const u of urls)URL.revokeObjectURL(u);urls.clear();data={resellers:[],orders:[],cases:[],revisions:[],reviews:[],banks:[]};root.innerHTML='';$('#document-dialog').close();$('#dialog-content').innerHTML='';$('#identity').textContent='';$('#login-form').elements.password.value='';notice('');}
function configurationText(){return storageConfiguration().message;}
async function act(button,fn){const text=button.textContent;button.disabled=true;button.textContent='Memproses…';try{return await fn();}catch(e){notice(e.message,true);}finally{button.disabled=false;button.textContent=text;}}
async function load(){
 const g=generation,uid=ctx.uid,filters=adminPage?[]:[['resellerId','==',uid]];
 const [resellers,orders,cases,revisions,reviews,settings]=await Promise.all([
  adminPage?store.list('resellers'):store.get('resellers/'+uid).then(r=>r?[{...r,id:uid}]:[]),
  store.list('orders',adminPage?[]:[['customerId','==',uid]]),store.list('resellerCases',filters),store.list('resellerRevisions',filters),store.list('resellerReviews',filters),store.get('publicSettings/store')]);
 if(g!==generation||c.a.currentUser?.uid!==uid)return;
 data={resellers,orders,cases,revisions,reviews,banks:settings?.banks||[]};render();
}
function linkedOrders(){return data.orders.filter(o=>o.salesChannel==='reseller'&&o.resellerId===o.customerId&&o.status!=='dibatalkan');}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">Belum ada data.</td></tr>`}</tbody></table></div>`;}
function balance(o){const t=totals(o);return `<span>${money(t.total)}</span><small>Terverifikasi ${money(t.paid)} · Sisa ${money(t.remaining)}</small>`;}
function overview(){const cases=data.cases;return `<div class="reseller-stats">${[[data.resellers.filter(r=>r.status==='disetujui').length,'Reseller aktif'],[data.resellers.filter(r=>r.status==='menunggu').length,'Pendaftaran menunggu'],[cases.filter(c=>c.kind==='shipping'&&c.status==='pending').length,'Resi perlu diperiksa'],[cases.filter(c=>c.kind==='payment'&&c.status==='pending').length,'Pembayaran perlu diverifikasi']].map(([n,t])=>`<section class="panel"><strong>${n}</strong><p>${t}</p></section>`).join('')}</div><section class="panel"><h2>Dokumen dan pembayaran reseller</h2><p>${esc(configurationText())}</p><p>Upload bukti tidak mengubah pembayaran menjadi Lunas. Persetujuan dilakukan setelah admin memeriksa dana masuk.</p>${!adminPage?'<p>Pilih pesanan milik Anda pada tab Resi & Pengiriman atau Pembayaran.</p>':''}</section>`;}
function people(){return `<p>Riwayat memakai ID akun dan pesanan. Aktivasi dokumen memerlukan claim dan sinkronisasi akses oleh pengelola.</p>${table(['Reseller / toko','Kontak / kanal','Status','Pesanan'],data.resellers.map(r=>`<tr><td>${esc(r.name)}<small>${esc(r.storeName)}</small></td><td>${esc(r.phone)}<small>${esc(r.channel)}</small></td><td>${esc(status(r.status))}</td><td>${data.orders.filter(o=>o.customerId===r.id).map(o=>`${esc(o.invoiceNo||'Belum ada invoice')} · ${money(o.total)}`).join('<br>')||'Belum ada pesanan'}</td></tr>`))}<section class="panel"><h2>Hubungkan pesanan asal reseller</h2><p>Pilih hanya pesanan yang memang berasal dari reseller. Pemilik Firebase pesanan tidak diubah. Setelah disimpan, jalankan skrip sinkronisasi akses dokumen.</p><form id="link-order"><label>Pesanan milik akun reseller<select name="orderId" required><option value="">Pilih pesanan</option>${data.orders.filter(o=>data.resellers.some(r=>r.id===o.customerId&&r.status==='disetujui')&&o.salesChannel!=='reseller').map(o=>`<option value="${esc(o.id)}">${esc(o.invoiceNo||'Belum ada invoice')} — ${esc(o.customerName)}</option>`).join('')}</select></label><label>Alasan penetapan kanal<input name="reason" required maxlength="500"></label><label class="check"><input type="checkbox" required> Saya sudah memastikan ini pesanan asal reseller.</label><button>Hubungkan pesanan</button></form></section>`;}
function registrations(){return `${table(['Nama / toko','Kanal / kontak','Status / catatan','Pemeriksaan'],data.resellers.map(r=>`<tr><td>${esc(r.name)}<small>${esc(r.storeName)}</small></td><td>${esc(r.channel)}<small>${esc(r.phone)}</small></td><td>${esc(status(r.status))}<small>${esc(r.note)}</small></td><td><button data-register="${esc(r.id)}">Periksa</button></td></tr>`))}<p>Persetujuan pendaftaran tetap memakai Firebase. Setelah persetujuan baru atau penonaktifan, jalankan skrip claim/sinkronisasi sesuai panduan sebelum akses dokumen dinyatakan aktif.</p>`;}
function documents(kind){const cases=data.cases.filter(c=>c.kind===kind);return `<div class="actions"><button class="primary" data-new="${kind}">${kind==='shipping'?'Upload resi':'Upload bukti pembayaran'}</button><span>${kind==='payment'?'Bukti diperiksa terpisah dari dana yang benar-benar masuk.':'Revisi tidak membuat pengiriman kedua.'}</span></div>${kind==='payment'?`<section class="panel"><h2>Tagihan dan transfer manual</h2>${data.banks.length?data.banks.map(b=>`<p>${esc(b.bank)} · ${esc(b.number)} · ${esc(b.name)}</p>`).join(''):'<p>Rekening aktif belum dikonfigurasi admin. Jangan mengirim transfer sebelum rekening dikonfirmasi.</p>'}${table(['Invoice','Total / pembayaran','Status pembayaran'],linkedOrders().map(o=>`<tr><td>${esc(o.invoiceNo)}</td><td>${balance(o)}</td><td>${totals(o).remaining===0?'Lunas':totals(o).paid?'Dibayar sebagian':'Belum Dibayar'}</td></tr>`))}</section>`:''}${table(['Invoice / reseller',kind==='shipping'?'Resi / kurir':'Tanggal / nominal','Status','Aksi'],cases.map(c=>{const r=data.revisions.find(r=>r.id===c.currentRevisionId);return `<tr><td>${esc(c.invoiceNo)}<small>${esc(data.resellers.find(x=>x.id===c.resellerId)?.storeName||'')}</small></td><td>${kind==='shipping'?esc(r?.trackingNo)+'<small>'+esc(r?.courier)+'</small>':esc(r?.transferDate)+'<small>'+money(r?.amount)+'</small>'}</td><td><span class="tag ${c.status}">${kind==='payment'&&c.status==='pending'?'Menunggu Verifikasi':esc(status(c.status))}</span></td><td><button data-detail="${esc(c.id)}">Detail & riwayat</button>${c.status==='correction'?` <button data-revise="${esc(c.id)}">Kirim revisi</button>`:''}</td></tr>`;}))}`;}
function render(){
 const requested=location.hash.slice(1);tab=tabs.some(([k])=>k===requested)?requested:tab;if(adminPage&&window.parent!==window)window.parent.postMessage({type:'kubah-admin-route',route:'resellers/'+tab},location.origin);
 $('#tabs').innerHTML=tabs.map(([k,t])=>`<button role="tab" id="tab-${k}" aria-controls="tab-panel" aria-selected="${tab===k}" tabindex="${tab===k?0:-1}" data-tab="${k}">${t}</button>`).join('');
 root.innerHTML=`<div id="tab-panel" role="tabpanel" aria-labelledby="tab-${tab}">${tab==='ringkasan'?overview():tab==='data'?people():tab==='pendaftaran'?registrations():documents(tab==='resi'?'shipping':'payment')}</div>`;
 $('#tabs').querySelectorAll('button').forEach((b,i)=>{b.onclick=()=>{tab=b.dataset.tab;location.hash=tab;render();};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tab=tabs[n][0];location.hash=tab;render();$('#tab-'+tab).focus();};});
 root.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>uploadDialog(b.dataset.new));root.querySelectorAll('[data-revise]').forEach(b=>b.onclick=()=>{const item=data.cases.find(c=>c.id===b.dataset.revise);uploadDialog(item.kind,item);});
 root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(data.cases.find(c=>c.id===b.dataset.detail)));
 root.querySelectorAll('[data-register]').forEach(b=>b.onclick=()=>registrationDialog(data.resellers.find(r=>r.id===b.dataset.register)));
 $('#link-order')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));act(e.submitter,async()=>{const selected=data.orders.find(o=>o.id===v.orderId);need(selected?.invoiceNo,'Pesanan harus memiliki invoice.');await c.fs.runTransaction(c.db,async tx=>{const ref=c.fs.doc(c.db,'orders',selected.id),s=await tx.get(ref),o=s.data();need(o.customerId===selected.customerId&&o.salesChannel!=='reseller','Data pesanan berubah.');tx.update(ref,{salesChannel:'reseller',resellerId:o.customerId,resellerLinkHistory:[...(o.resellerLinkHistory||[]),{from:o.salesChannel||o.channel||'',to:'reseller',reason:v.reason,by:ctx.uid,at:new Date().toISOString()}]});});notice('Pesanan dihubungkan. Jalankan sinkronisasi akses dokumen agar upload dapat digunakan.');await load();});});
}
function dialog(html){const d=$('#document-dialog');$('#dialog-content').innerHTML=html;if(!d.open)d.showModal();return d;}
function uploadDialog(kind,existing){
 const options=linkedOrders().filter(o=>(kind!=='payment'||o.schemaVersion===2&&o.paymentMethod==='transfer'&&o.totalAccepted===true&&totals(o).remaining>0)&&(!existing||o.id===existing.orderId));const prior=existing&&data.revisions.find(r=>r.id===existing.currentRevisionId);let prepared=null,previewURL=null,preparation=0;
 dialog(`<h2>${existing?'Kirim revisi':kind==='shipping'?'Upload label pengiriman':'Upload bukti pembayaran'}</h2><p>${esc(configurationText())}</p><form id="upload-form"><label>Pesanan<select name="orderId" required><option value="">Pilih pesanan milik reseller</option>${options.map(o=>`<option value="${esc(o.id)}" ${existing?'selected':''}>${esc(o.invoiceNo)} — ${esc(o.customerName||'')} · ${money(totals(o).remaining)} tersisa</option>`).join('')}</select></label><label>Nomor invoice<input name="invoiceNo" required maxlength="200" value="${esc(existing?.invoiceNo||'')}"></label>${kind==='shipping'?`<label>Nomor resi<input name="trackingNo" required maxlength="200" value="${esc(prior?.trackingNo||'')}"></label><label>Nama kurir<input name="courier" required maxlength="200" value="${esc(prior?.courier||'')}"></label>`:`<label>Tanggal transfer<input name="transferDate" type="date" required max="${today()}" value="${esc(prior?.transferDate||today())}"></label><label>Nominal transfer (Rp)<input name="amount" type="number" min="1" step="1" required value="${prior?.amount||''}"></label>`}<label>Berkas PDF/JPG/PNG<input id="upload-file" type="file" accept="application/pdf,image/jpeg,image/png" required></label><p>Hasil upload maksimal 2 MB. Foto dikompres di perangkat; PDF tidak dikompres.</p><div id="file-preview"></div><label class="check"><input type="checkbox" id="readable" required> Saya sudah memeriksa bahwa tulisan dan barcode pada berkas tetap terbaca.</label><progress id="upload-progress" value="0" max="100"></progress><p id="upload-status" role="status"></p><button class="primary" ${storageConfiguration().ready?'':'disabled'}>Kirim dokumen</button></form>`);
 const form=$('#upload-form');form.elements.orderId.onchange=()=>{form.elements.invoiceNo.value=options.find(o=>o.id===form.elements.orderId.value)?.invoiceNo||'';};
 $('#upload-file').onchange=async()=>{const ticket=++preparation;prepared=null;$('#readable').checked=false;if(previewURL){URL.revokeObjectURL(previewURL);urls.delete(previewURL);}$('#file-preview').textContent='Menyiapkan pratinjau…';try{const result=await prepareDocument($('#upload-file').files[0]);if(ticket!==preparation||!form.isConnected)return;prepared=result;previewURL=safeURL(prepared.blob);const preview=$('#file-preview');preview.textContent='';if(prepared.mime==='application/pdf'){const a=document.createElement('a');a.href=previewURL;a.target='_blank';a.rel='noopener';a.textContent='Buka pratinjau PDF';preview.append(a);}else{const img=document.createElement('img');img.src=previewURL;img.alt='Pratinjau dokumen setelah kompresi';preview.append(img);}const size=document.createElement('small');size.textContent=Math.ceil(prepared.size/1024)+' KB';preview.append(size);}catch(e){if(ticket===preparation&&form.isConnected)$('#file-preview').textContent=e.message;}};
 form.onsubmit=e=>{e.preventDefault();act(e.submitter,async()=>{need(prepared,'Pilih berkas dan tunggu pratinjau selesai.');const v=Object.fromEntries(new FormData(form)),o=options.find(o=>o.id===v.orderId);need(o,'Pilih pesanan yang valid.');need(v.invoiceNo.trim()===o.invoiceNo,'Nomor invoice tidak cocok.');const uid=ctx.uid;try{const f=await storage.upload(prepared,{uid:o.resellerId,orderId:o.id,invoiceNo:o.invoiceNo,kind,onProgress:(n,t)=>{$('#upload-progress').value=n;$('#upload-status').textContent=t;}});need(c.a.currentUser?.uid===uid,'Sesi berubah.');$('#upload-status').textContent='Berkas tersimpan; menyimpan pengajuan ke Firebase…';await core.submit(ctx,{...v,kind,caseId:existing?.id,file:f});$('#document-dialog').close();notice('Dokumen tersimpan dan menunggu pemeriksaan. Pembayaran belum otomatis Lunas.');await load();}catch(err){$('#upload-status').textContent=err.message+' Pilih Kirim dokumen lagi untuk mencoba ulang. Berkas dengan isi yang sama tidak ditimpa atau digandakan.';throw err;}});};
}
async function openFile(rev,mode){
 const uid=c.a.currentUser?.uid,popup=mode==='print'?window.open('','_blank'):null;if(popup){popup.document.body.textContent='Memuat dokumen privat…';}
 try{const blob=await storage.read(rev.file);need(c.a.currentUser?.uid===uid,'Sesi berubah. Buka dokumen kembali.');const url=safeURL(blob),name=`${rev.kind}-${rev.invoiceNo.replace(/[^a-zA-Z0-9_-]/g,'_')}-r${rev.revision}.${rev.file.mime==='application/pdf'?'pdf':rev.file.mime==='image/jpeg'?'jpg':'png'}`;
  if(mode==='view'){need($('#document-dialog').open,'Buka detail dokumen kembali.');let viewer=$('#private-viewer');if(!viewer){viewer=document.createElement('section');viewer.id='private-viewer';viewer.className='panel';$('#dialog-content').append(viewer);}viewer.innerHTML=`<h3>Dokumen privat — Revisi ${rev.revision}</h3>${rev.file.mime==='application/pdf'?`<iframe title="Pratinjau dokumen privat" src="${url}" style="width:100%;height:60vh;border:0"></iframe>`:`<img alt="Dokumen privat tersimpan" src="${url}" style="max-width:100%;height:auto">`}`;viewer.scrollIntoView({block:'nearest'});return;}
  if(mode==='download'){const a=document.createElement('a');a.href=url;a.download=name;a.click();return;}
  need(popup,'Izinkan popup untuk membuka dokumen.');popup.document.title=name;popup.document.body.textContent='';
  const help=popup.document.createElement('p');help.textContent=rev.file.mime==='application/pdf'?'Gunakan ikon cetak pada penampil PDF atau Ctrl + P.':'Gunakan tombol Cetak atau Ctrl + P.';popup.document.body.append(help);
  const print=popup.document.createElement('button');print.textContent='Cetak';popup.document.body.append(print);
  const el=popup.document.createElement(rev.file.mime==='application/pdf'?'iframe':'img');el.src=url;el.style.cssText='width:100%;'+(rev.file.mime==='application/pdf'?'height:90vh;border:0':'height:auto');popup.document.body.append(el);
  print.onclick=()=>{if(el.tagName==='IFRAME'){try{el.contentWindow.focus();el.contentWindow.print();}catch{help.textContent='Gunakan ikon cetak pada penampil PDF.';}}else popup.print();};
 }catch(e){if(popup)popup.document.body.textContent=e.message;throw e;}
}
function detail(item){
 const versions=data.revisions.filter(r=>r.caseId===item.id).sort((a,b)=>b.revision-a.revision);const current=versions[0];
 dialog(`<h2>${esc(item.invoiceNo)} — ${item.kind==='shipping'?'Label pengiriman':'Bukti pembayaran'}</h2><p>ID pesanan: ${esc(item.orderId)}</p><p>Penerima: ${esc(data.orders.find(o=>o.id===item.orderId)?.customerName||'Belum tersedia')}<br>${esc(data.orders.find(o=>o.id===item.orderId)?.addressData?.text||data.orders.find(o=>o.id===item.orderId)?.address||'Alamat belum tersedia')}<br>${esc(data.orders.find(o=>o.id===item.orderId)?.phone||'')}</p>${versions.map(r=>{const review=data.reviews.find(x=>x.id===r.id);return `<section class="panel"><h3>Revisi ${r.revision}</h3><p>${item.kind==='shipping'?esc(r.trackingNo)+' · '+esc(r.courier):esc(r.transferDate)+' · '+money(r.amount)}</p><small>Dicatat oleh ${esc(r.createdBy)}</small><p>${review?esc(status(review.decision))+' — '+esc(review.reason||'Pemeriksaan disetujui'):'Menunggu pemeriksaan'}</p><div class="actions">${['view','download','print'].map((m,i)=>`<button data-file="${esc(r.id)}" data-mode="${m}">${['Lihat','Unduh','Cetak'][i]}</button>`).join('')}</div></section>`;}).join('')}${adminPage&&item.status==='pending'?`<form id="review-form"><h3>Pemeriksaan admin</h3><label>Keputusan<select name="decision"><option value="correction">Minta perbaikan</option><option value="approved">Setujui</option></select></label><label>Alasan / catatan<textarea name="reason" maxlength="1000"></textarea></label>${item.kind==='payment'?'<label>Referensi mutasi bank unik<input name="bankReference" maxlength="80" placeholder="BANK-TANGGAL-REFERENSI"></label><label class="check"><input type="checkbox" name="fundsConfirmed"> Saya sudah memeriksa dana benar-benar masuk dan nominalnya sesuai.</label>':''}<button class="primary">Simpan pemeriksaan</button></form>`:''}`);
 $('#dialog-content').querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>act(b,()=>openFile(versions.find(r=>r.id===b.dataset.file),b.dataset.mode)));
 $('#review-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,v=Object.fromEntries(new FormData(form));act(e.submitter,async()=>{if(v.decision==='approved')await storage.read(current.file);await core.review(ctx,{...v,caseId:item.id,revisionId:item.currentRevisionId,fundsConfirmed:form.elements.fundsConfirmed?.checked===true});$('#document-dialog').close();notice('Pemeriksaan tersimpan.');await load();});});
}
function registrationDialog(r){dialog(`<h2>Periksa ${esc(r.storeName)}</h2><form id="registration-review"><label>Status<select name="status"><option value="disetujui">Setujui</option><option value="ditolak">Tolak</option><option value="dinonaktifkan">Nonaktifkan</option></select></label><label>Catatan admin<textarea name="note" maxlength="1000" required></textarea></label><p>Setelah perubahan, jalankan skrip sinkronisasi akses dokumen. Akses penyimpanan menggunakan daftar izin tersendiri.</p><button>Simpan</button></form>`);$('#registration-review').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));act(e.submitter,async()=>{await api('reviewReseller',{customerId:r.id,...v});$('#document-dialog').close();notice('Status Firebase tersimpan. Perbarui claim bila akun baru, lalu sinkronkan akses Supabase.');await load();});};}
async function boot(){try{c=await connect();store=manualStore(c);core=resellerService(store,{stamp:()=>c.fs.serverTimestamp()});storage=documentStorage(c);c.auth.onAuthStateChanged(c.a,async user=>{clearPrivate();ctx=null;$('#login-panel').hidden=!!user;$('#workspace').hidden=!user;$('#logout').hidden=!user;if(!user)return;try{if(adminPage)await ensureAdminAccess(user);else{const r=await store.get('resellers/'+user.uid);need(r?.status==='disetujui','Akun belum menjadi reseller aktif. Ajukan atau periksa status melalui menu Reseller pada toko.');}ctx={uid:user.uid,role:adminPage?'admin':'reseller'};$('#identity').textContent=(adminPage?'Admin: ':'Reseller: ')+(user.email||user.uid);await load();}catch(e){$('#workspace').hidden=true;notice(e.message,true);}});}catch(e){notice('Firebase belum terhubung: '+e.message,true);}}
$('#login-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));act(e.submitter,()=>login(v.email,v.password));};
$('#logout').onclick=e=>act(e.currentTarget,logout);$('#refresh').onclick=e=>act(e.currentTarget,load);$('#refresh-access').onclick=e=>act(e.currentTarget,async()=>{need(c.a.currentUser,'Silakan masuk.');await c.a.currentUser.getIdToken(true);notice(configurationText());await load();});
$('#dialog-close').onclick=()=>$('#document-dialog').close();window.addEventListener('hashchange',()=>ctx&&render());
if(new URLSearchParams(location.search).get('embed')==='1')document.body.classList.add('embedded');
boot();
