import {check,str,num,hash} from './manual-domain.js?v=katalog-pembeli-20260909-r7';
export const RETURN_REASONS=['Barang berbeda dari pesanan','Varian salah','Barang rusak atau cacat saat diterima','Jumlah kurang','Tidak sesuai deskripsi','Produk kedaluwarsa','Permintaan penukaran karena pilihan pelanggan','Kendala lainnya'];
export const LEGACY_REASONS=['Barang salah','Barang rusak','Barang belum diterima','Lainnya'];
export const RETURN_STAGES={diajukan:'Diajukan',ditinjau:'Ditinjau',perlu_informasi:'Perlu Informasi Tambahan',menunggu_pengembalian:'Menunggu Pengembalian',barang_diterima:'Barang Diterima',penyelesaian_diproses:'Penyelesaian Diproses',selesai:'Selesai',ditolak:'Ditolak'};
export const caseId=(uid,oid,index)=>'CR-'+hash([uid,oid,index]).slice(0,40);
export function caseStage(r){return r.stage||(['diajukan','ditolak'].includes(r.status)?r.status:r.returnInspected?'barang_diterima':'penyelesaian_diproses');}
export function stageChange(r,to,note){
 check(RETURN_STAGES[to]&&str(note,1000,true),'Isi catatan pemeriksaan.');
 const from=caseStage(r),allowed={diajukan:['ditinjau','perlu_informasi'],ditinjau:['perlu_informasi','penyelesaian_diproses'],perlu_informasi:['ditinjau'],menunggu_pengembalian:['perlu_informasi'],barang_diterima:['penyelesaian_diproses','perlu_informasi'],penyelesaian_diproses:['perlu_informasi','selesai']};
 check(allowed[from]?.includes(to),'Perubahan tahap tidak sesuai alur. Gunakan pemeriksaan gudang/solusi untuk tahap khusus.');
 if(to==='selesai'){check(r.resolutionNote,'Tentukan penyelesaian terlebih dahulu.');check(!r.refundAmount||r.refundPaid,'Refund belum benar-benar dibayarkan.');check(!['retur','penggantian'].includes(r.status)||!r.returnRequired||r.returnInspected,'Barang kembali belum diperiksa.');check(!['penggantian','kirim_kekurangan'].includes(r.status)||r.fulfilled,'Pengiriman penyelesaian belum dicatat.');}
 return to;
}
export const POLICY_FIELDS={submissionWindow:'Batas waktu pengajuan sejak diterima (termasuk satuan hari kerja/kalender)',responseEstimate:'Estimasi respons admin',returnShipmentWindow:'Batas waktu pengiriman balik',returnShippingCost:'Penanggung ongkir menurut penyebab',changeOfMind:'Penukaran karena pilihan pelanggan',itemCondition:'Kondisi barang dan kelengkapan',refundMethod:'Metode refund',refundEstimate:'Estimasi refund',returnAddress:'Alamat retur lengkap dan kontak penerima'};
export const RETENTION_FIELDS={transactions:'Transaksi dan pencatatan keuangan',claims:'Riwayat retur/komplain',evidence:'Lampiran bukti pembeli',audits:'Catatan pemeriksaan/tindakan admin'};
export function policyDraft(raw){const fields={};for(const k of Object.keys(POLICY_FIELDS))fields[k]=str(raw[k]||'',3000);const retention={};for(const k of Object.keys(RETENTION_FIELDS))retention[k]=str(raw['retention_'+k]||'',1000);return {version:str(raw.version||'draft-r8',80,true),effectiveAt:raw.effectiveAt?new Date(raw.effectiveAt).toISOString():null,status:'draft',fields,retention,automaticDeletion:false,updatedAt:new Date().toISOString()};}
export const RETURN_INTRO='Kubah Nabawi Store membantu menangani kendala pada pesanan yang diterima pelanggan. Jika terdapat barang rusak, salah kirim, jumlah kurang, atau ketidaksesuaian dengan pesanan, silakan ajukan melalui detail pesanan atau hubungi layanan pelanggan agar dapat diperiksa dan diberikan penyelesaian yang sesuai.';
export function returnPolicyHTML(){return `<article class="policy panel"><h1>Kebijakan Retur, Penukaran, dan Pengembalian Dana</h1><p>${RETURN_INTRO}</p><h2>Alasan pengajuan</h2><ul>${RETURN_REASONS.map(r=>'<li>'+r+'</li>').join('')}</ul><p>Masalah barang atau pengiriman diperiksa terpisah dari penukaran karena pilihan pelanggan. Hak atas barang cacat atau salah kirim tidak dihilangkan oleh ketentuan penukaran karena berubah pikiran.</p><h2>Cara mengajukan</h2><p>Pesanan Saya → Detail Pesanan → Ajukan Retur/Komplain → pilih barang dan jumlah → alasan → bukti → kirim. Sebagian barang dapat diajukan; invoice mengikuti pesanan yang sama di admin.</p><p>Bukti dapat berupa foto barang, label, kemasan atau dokumen pendukung. Maksimal 3 PDF/JPG/PNG, 2 MB per berkas. Jangan mengirim KTP atau informasi rahasia. Video tidak didukung pada upload ini. Video unboxing dapat membantu, tetapi bukan satu-satunya dasar menerima atau menolak pengajuan. Jika upload belum aktif, pengajuan tanpa lampiran tetap dapat disampaikan.</p><h2>Pemeriksaan dan penyelesaian</h2><p>Admin dapat meminta informasi tambahan, mengirim kekurangan, mengganti/menukar barang, atau menyetujui refund sebagian/penuh sesuai barang terdampak dan dana yang diterima. Tidak semua kasus memerlukan pengiriman balik.</p><p>Jangan mengirim barang kembali sebelum menerima instruksi, alamat lengkap dan kontak penerima dari admin. Alamat wilayah Warehouse bukan instruksi retur. Penolakan disertai alasan; hubungi layanan pelanggan untuk meminta peninjauan kembali.</p><p>Refund baru selesai setelah pembayaran benar-benar dilakukan. Barang retur diperiksa gudang sebelum dapat masuk stok layak jual. Pengajuan tidak otomatis menyetujui refund atau menambah stok.</p><p class="notice">Rincian batas waktu, ongkir, penukaran pilihan pelanggan, alamat retur dan estimasi refund belum ditetapkan. Hak pembeli yang berlaku tetap dihormati; perubahan kebijakan tidak mengurangi hak pesanan lama.</p><a class="button" href="toko.html?v=dokumen-privat-20260913-r8b#pesanan">Pesanan Saya</a> <a class="button" href="informasi.html?v=dokumen-privat-20260913-r8b#kontak">Hubungi layanan pelanggan</a></article>`;}

