import {label} from './shop-client.js?v=katalog-pembeli-20260909-r7';
import { $,esc,money,date,input,area,select,checkbox,tabs,table,form,bindForm,api,busy,message,download } from './planning-ui.js?v=katalog-pembeli-20260909-r7';
import {wibDay,unitPrice,salesChannel,CHANNELS,csv} from './planning-domain.js?v=katalog-pembeli-20260909-r7';
import {check,hash} from './manual-domain.js?v=katalog-pembeli-20260909-r7';
let filters={query:'',status:'',courier:'',date:''};
const invoice=o=>esc(o.invoiceNo||'Belum ada invoice');
export async function renderShipping(U){const data=await api('adminData');if(!U.isCurrent())return;const tab=['kelola','kurir','jadwal'].includes(U.tab)?U.tab:'kelola';
 $('#content').innerHTML=`<div class="page-head"><div><h1>Pengiriman & Kurir</h1><p>Kelola pengiriman, kurir, dan jadwal toko.</p></div><a class="button" href="kurir.html" target="_blank">Halaman kurir</a></div>${tabs('shipping',[['kelola','Kelola Pengiriman'],['kurir','Data Kurir'],['jadwal','Jadwal Pengiriman']],tab)}<div id="shipping-body"></div>`;
 if(tab==='kelola'&&U.oid)filters.courier=U.oid;const couriers=data.couriers.map(c=>[c.id,c.name+(c.active?'':' · nonaktif')]);
 if(tab==='kelola'){
  $('#shipping-body').innerHTML=`<div class="filters">${input('query','Cari invoice / penerima',filters.query,'search')}${select('status','Status',[['','Semua status'],...[...new Set(data.orders.map(o=>o.status))].map(s=>[s,label(s)])],filters.status)}${select('courier','Kurir',[['','Semua kurir'],...couriers],filters.courier)}${input('date','Tanggal pesanan (WIB)',filters.date,'date')}</div><div id="shipping-table"></div><section id="shipping-detail"></section>`;
  const paint=()=>{const q=filters.query.toLowerCase(),rows=data.orders.filter(o=>(!q||[o.invoiceNo,o.customerName].some(x=>String(x||'').toLowerCase().includes(q)))&&(!filters.status||o.status===filters.status)&&(!filters.courier||o.courierId===filters.courier)&&(!filters.date||o.createdAt&&wibDay(o.createdAt)===filters.date));$('#shipping-table').innerHTML=table(['Invoice','Penerima & alamat','Metode / resi','Kurir / jadwal','Pembayaran','Status','Aksi'],rows.map(o=>[invoice(o),esc(o.customerName)+'<br><small>'+esc(o.addressData?.text||o.address||'')+'</small>',esc(({store:'Kurir Toko',pickup:'Ambil di Gudang',regular:'Reguler',instant:'Instan',cargo:'Kargo'})[o.shippingMethod]||'—')+'<br>'+esc(o.trackingNumber||'Belum ada resi'),esc(o.courier||'Belum ditugaskan')+'<br>'+(o.slot?date(o.slot.startAt):'Belum terjadwal'),esc(label(o.paymentStatus))+'<br>'+money(Math.max(0,(o.total||0)-(o.paidAmount||0))),esc(o.detailStatus||o.status),`<button data-detail="${esc(o.id)}">Rincian</button>`]));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(data.orders.find(o=>o.id===b.dataset.detail)));};
  document.querySelectorAll('.filters input,.filters select').forEach(el=>el.oninput=()=>{filters[el.name]=el.value;paint();});paint();
  function detail(o){$('#shipping-detail').innerHTML=`<div class="panel"><h2>${invoice(o)} · ${esc(o.customerName)}</h2><p>${esc(o.addressData?.text||o.address||'')}<br>${esc(o.phone||'')}</p><p>${esc(CHANNELS[salesChannel(o)])} · ${esc(o.note||'')}</p>${table(['Barang','Varian','Unit','Pcs'],(o.items||[]).map(i=>[esc(i.productName),esc(i.variant),i.qty,i.pcs??i.qty]))}<a class="button" href="admin-website.html?embed=1#orders/${encodeURIComponent(o.id)}">Buka detail pesanan & status</a></div>${form('packages',input('packageCount','Jumlah paket pengiriman',o.packageCount||'', 'number','min="1" max="100" required')+input('reason','Catatan pembagian paket',o.packageNote||'', 'text','required'),'Simpan jumlah paket')}${form('channel',select('salesChannel','Koreksi Sales Channel',Object.entries(CHANNELS).filter(([k])=>k!=='unknown'),salesChannel(o))+input('reason','Alasan koreksi kanal','','text','required'),'Simpan koreksi kanal')}${!o.invoiceNo?form('invoice-fill',input('invoiceNo','Nomor invoice yang benar','','text','required maxlength="100"')+input('reason','Alasan melengkapi invoice','','text','required'),'Simpan invoice'):''}${o.shippingMethod==='store'&&o.status==='diproses'?form('assign',select('courierId','Kurir aktif',couriers.filter(([uid])=>data.couriers.find(c=>c.id===uid).active),o.courierId),'Tugaskan kurir')+form('schedule',select('slotId','Slot baru',data.slots.filter(s=>s.enabled&&s.capacity>s.used).map(s=>[s.id,date(s.startAt)+' · sisa '+(s.capacity-s.used)]),o.slotId)+input('note','Alasan perubahan jadwal','','text','required'),'Pindah jadwal'):''}`;
   bindForm('packages',async d=>{await U.store.run(async tx=>{const original=await tx.get('orders/'+o.id),task=await tx.get('courierTasks/'+o.id);check(original,'Pesanan tidak ditemukan.');const count=Number(d.packageCount);check(Number.isSafeInteger(count)&&count>=1&&count<=100,'Jumlah paket 1–100.');const patch={packageCount:count,packageNote:d.reason};tx.update('orders/'+o.id,patch);if(task)tx.update('courierTasks/'+o.id,patch);tx.set('channelAudits/packages-'+crypto.randomUUID(),{orderId:o.id,type:'package_count',before:original.packageCount||null,after:count,actor:U.ctx.uid,at:new Date().toISOString(),reason:d.reason});});await U.render();message('Jumlah paket tersimpan tanpa mengganti invoice.');});
   bindForm('channel',async d=>{await U.store.run(async tx=>{const original=await tx.get('orders/'+o.id);check(original,'Pesanan tidak ditemukan.');check(['website','manual_admin','reseller'].includes(d.salesChannel),'Kanal tidak valid.');if(d.salesChannel==='reseller')check(original.resellerId,'Tautkan pemilik pesanan lewat modul Reseller terlebih dahulu.');check(original.salesChannel!==d.salesChannel,'Kanal sudah sesuai.');tx.update('orders/'+o.id,{salesChannel:d.salesChannel});tx.set('channelAudits/channel-'+crypto.randomUUID(),{orderId:o.id,type:'channel_correction',before:original.salesChannel||null,after:d.salesChannel,actor:U.ctx.uid,at:new Date().toISOString(),reason:d.reason});});await U.render();message('Kanal diperbarui. Nominal, invoice, stok, dan pembayaran tetap.');});
   bindForm('assign',async d=>{await api('orderAction',{orderId:o.id,operation:'assign',courierId:d.courierId});await U.render();message('Kurir ditugaskan.');});bindForm('schedule',async d=>{await api('reschedule',{orderId:o.id,...d});await U.render();message('Jadwal diperbarui.');});
   bindForm('invoice-fill',async d=>{check(!data.orders.some(x=>x.id!==o.id&&x.invoiceNo===d.invoiceNo.trim()),'Nomor invoice dipakai pesanan lain.');await U.store.run(async tx=>{const order=await tx.get('orders/'+o.id),task=await tx.get('courierTasks/'+o.id);check(order&&!order.invoiceNo,'Invoice sudah diisi. Muat ulang.');tx.update('orders/'+o.id,{invoiceNo:d.invoiceNo.trim()});if(task)tx.update('courierTasks/'+o.id,{invoiceNo:d.invoiceNo.trim()});tx.set('channelAudits/invoice-'+hash([o.id,d.invoiceNo]),{orderId:o.id,type:'invoice_completed',before:order.invoiceNo||null,after:d.invoiceNo.trim(),reason:d.reason,actor:U.ctx.uid,at:new Date().toISOString()});});await U.render();message('Invoice dilengkapi pada pesanan dan tugas kurir.');});$('#shipping-detail').scrollIntoView({behavior:'smooth',block:'start'});
  }
 }else if(tab==='kurir'){
  $('#shipping-body').innerHTML=table(['Nama kurir','Telepon','Status','Tugas aktif','Aksi'],data.couriers.map(c=>[esc(c.name),esc(c.phone),c.active?'Aktif':'Nonaktif',data.orders.filter(o=>o.courierId===c.id&&!['selesai','dibatalkan'].includes(o.status)).length,`<button data-edit="${esc(c.id)}">Ubah</button> <a class="button" href="#shipping/kelola/${esc(c.id)}">Lihat tugas</a>`]))+'<div id="courier-editor"></div>';
  const edit=(c={})=>{$('#courier-editor').innerHTML=form('courier',`<h2 class="full">${c.id?'Ubah':'Tambah'} kurir</h2><p class="full muted">Gunakan UID akun Firebase kurir yang sudah dibuat. Akun Supplier tidak mendapatkan akses ini.</p>`+input('uid','UID Firebase',c.id||'','text','required '+(c.id?'readonly':''))+input('name','Nama kurir',c.name||'','text','required')+input('phone','Nomor telepon',c.phone||'','tel','required')+checkbox('active','Kurir aktif',c.active??true));bindForm('courier',async(d,f)=>{await api('saveCourier',{...d,active:f.elements.active.checked});await U.render();message('Profil kurir tersimpan.');});};edit();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(data.couriers.find(c=>c.id===b.dataset.edit)));
 }else{
  $('#shipping-body').innerHTML=table(['Tanggal / rentang WIB','Batas pemesanan','Kapasitas','Kurir','Status','Aksi'],data.slots.map(s=>[date(s.startAt)+' – '+date(s.endAt),date(s.cutoffAt),`${s.used||0} / ${s.capacity}`,esc(data.couriers.find(c=>c.id===s.courierId)?.name||'Belum ditentukan'),s.enabled?'Aktif':'Nonaktif',`<button data-slot="${esc(s.id)}">Ubah</button>`]))+'<div id="slot-editor"></div>'+form('days','<h2 class="full">Hari operasional & libur</h2>'+[0,1,2,3,4,5,6].map((d)=>checkbox('day'+d,['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][d],data.settings.operatingDays.includes(d))).join('')+area('holidays','Tanggal libur, satu YYYY-MM-DD per baris',data.settings.holidays.join('\n')),'Simpan hari operasional');
  const local=v=>v?new Date(new Date(v).getTime()+7*3600000).toISOString().slice(0,16):'';
  const edit=(s={})=>{$('#slot-editor').innerHTML=form('slot','<h2 class="full">'+(s.id?'Ubah slot':'Tambah slot')+'</h2>'+input('startAt','Mulai (WIB)',local(s.startAt),'datetime-local','required')+input('endAt','Selesai (WIB)',local(s.endAt),'datetime-local','required')+input('cutoffAt','Batas pemesanan (WIB)',local(s.cutoffAt),'datetime-local','required')+input('capacity','Kapasitas pengiriman',s.capacity||6,'number','min="1" required')+select('courierId','Kurir', [['','Belum ditentukan'],...couriers],s.courierId)+checkbox('enabled','Slot aktif',s.enabled??true));const key=s.id||crypto.randomUUID();bindForm('slot',async(d,f)=>{await api('saveSlot',{...d,id:key,startAt:new Date(d.startAt+':00+07:00').toISOString(),endAt:new Date(d.endAt+':00+07:00').toISOString(),cutoffAt:new Date(d.cutoffAt+':00+07:00').toISOString(),capacity:Number(d.capacity),enabled:f.elements.enabled.checked});await U.render();message('Slot tersimpan.');});};edit();document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>edit(data.slots.find(s=>s.id===b.dataset.slot)));
  bindForm('days',async(d,f)=>{await api('saveConfig',{settings:{...data.settings,operatingDays:[0,1,2,3,4,5,6].filter(n=>f.elements['day'+n].checked),holidays:d.holidays.split(/\s+/).filter(Boolean)}});await U.render();message('Hari operasional tersimpan.');});
 }
}
export async function renderNewOrder(U){const [products,resellers]=await Promise.all([U.store.list('products'),U.store.list('resellers')]);if(!U.isCurrent())return;const variants=products.filter(p=>p.status==='aktif'&&p.website?.retail>0).flatMap(p=>p.variants.map(v=>[p.id+'/'+v.id,`${p.name} · ${v.color||''} ${v.size||''} · ${v.sku} · stok ${v.stock}`]));const key=crypto.randomUUID();
 $('#content').innerHTML='<h1>Buat Pesanan</h1><p>Harga mengikuti Eceran/Grosir. Pilih reseller hanya jika pesanan dibuat atas nama reseller aktif.</p>'+form('new-order',input('customerName','Nama pelanggan','','text','required')+input('phone','Telepon','','tel','required')+select('resellerId','Sales Channel',[['','Manual Admin'],...resellers.filter(r=>r.status==='disetujui').map(r=>[r.id,'Reseller · '+(r.storeName||r.name)])])+area('address','Alamat lengkap')+select('mode','Harga',['eceran','grosir'])+input('shippingCost','Ongkir yang telah diperiksa (Rp)',0,'number','min="0" required')+'<div id="order-lines" class="full"></div><button type="button" id="add-line">Tambah barang</button><p class="full" id="order-total"></p>','Simpan pesanan, belum dibayar');
 const line=()=>{const row=document.createElement('div');row.className='variant-row form-grid';row.innerHTML=select('item','Produk / varian',variants)+input('qty','Jumlah unit',1,'number','min="1" required')+'<button type="button" class="remove">Hapus baris</button>';row.querySelector('.remove').onclick=()=>{row.remove();total();};row.oninput=total;$('#order-lines').append(row);total();};
 const items=()=>[...document.querySelectorAll('#order-lines .variant-row')].map(r=>{const [productId,variantId]=r.querySelector('[name=item]').value.split('/');return {productId,variantId,qty:Number(r.querySelector('[name=qty]').value)};});
 function total(){try{const f=$('#new-order'),rows=items();const value=rows.reduce((s,i)=>{const p=products.find(p=>p.id===i.productId),v=p.variants.find(v=>v.id===i.variantId);return s+unitPrice(p,v,i.qty,f.elements.mode.value,!!f.elements.resellerId.value,rows.filter(x=>p.website.combine==='variant'?x.productId===i.productId&&x.variantId===i.variantId:p.website.combine==='all'?products.find(y=>y.id===x.productId).website.combine==='all'&&products.find(y=>y.id===x.productId).website.group===p.website.group:x.productId===i.productId).reduce((n,x)=>n+x.qty*products.find(y=>y.id===x.productId).website.packPcs,0)).price*i.qty;},Number(f.elements.shippingCost.value||0));$('#order-total').textContent='Perkiraan total '+money(value)+' · stok dan harga diperiksa kembali saat menyimpan.';}catch{$('#order-total').textContent='Lengkapi barang dan jumlah.';}}
 $('#add-line').onclick=line;$('#new-order').oninput=total;line();bindForm('new-order',async d=>{const r=await api('legacyManualOrder',{...d,key,shippingCost:Number(d.shippingCost),items:items()});location.href='admin-website.html?embed=1#orders/'+encodeURIComponent(r.id);});
}
