import {catalogHero,categoryStrip} from './catalog-design.js?v=desain-20260913-r10';
import {APPROVED_POLICY_SUMMARY} from './return-domain.js?v=kebijakan-20260913-r9';
import {mountBuyerRevisions} from './return-evidence-ui.js?v=kebijakan-20260913-r9';
import {RETURN_REASONS,RETURN_STAGES,caseStage,caseId} from './return-domain.js?v=kebijakan-20260913-r9';
import {mountClaimUpload,evidenceButtons} from './buyer-document-ui.js?v=kebijakan-20260913-r9';
import {api,connect,login,logout,upload,viewEvidence,money,date,esc,safeURL,$,label,formValues,message,busy} from './shop-client.js?v=kebijakan-20260913-r9';
import {manualStore} from './manual-store.js?v=admin-supplier-20260909-r3';
import {renderSupplierPartnership} from './partnership-ui.js?v=kebijakan-20260913-r9';
import {CATEGORIES,catalogEstimate,cardPrice,shippingText,submitOrderRequest,productFacts,productGallery,catalogOptions,filterCatalog,timestamp,reorderCart,quoteSignature} from './catalog-domain.js?v=katalog-pembeli-20260909-r7';
const read=(key,def)=>{try{return JSON.parse(localStorage.getItem(key))??def;}catch{return def;}};
const S={products:[],settings:{},user:null,mode:read('kn-mode','eceran'),cart:read('kn-cart',[]),wish:read('kn-wish',[]),category:'',sort:'newest',availability:'',minPrice:'',maxPrice:'',material:'',size:'',wishlistView:false,orderTab:'all',onlyStock:false,onlyWholesale:false,query:'',account:null,resellerPrices:[],quote:null,checkoutDraft:read('kn-checkout',null)};
let pageVersion=0,detailProduct=null;
const photo=p=>p.images?.find(i=>i.isPrimary)?.url||p.images?.[0]?.url||'';
const qtyCount=()=>S.cart.reduce((s,i)=>s+i.qty,0);
function save(){localStorage.setItem('kn-cart',JSON.stringify(S.cart));localStorage.setItem('kn-wish',JSON.stringify(S.wish));localStorage.setItem('kn-mode',JSON.stringify(S.mode));$('#cart-count').textContent=qtyCount();}
const empty=(title,text,action='')=>`<div class="empty"><h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;
function show(html){$('#content').innerHTML=html;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>location.hash=b.dataset.page);}
function requireLogin(){if(S.user)return true;show(authHTML());bindAuth();return false;}
async function loadCatalog(){const r=await api('catalog');S.products=r.products;S.settings=r.settings;const phone=String(S.settings.whatsapp||'').replace(/\D/g,'').replace(/^0/,'62');$('#help').hidden=!phone;if(phone)$('#help').href='https://wa.me/'+phone;}
function bindCatalog(){
  document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>busy(b,()=>detail(b.dataset.product)));
  document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>{const pid=b.dataset.wish;S.wish=S.wish.includes(pid)?S.wish.filter(id=>id!==pid):[...S.wish,pid];save();catalog(S.wishlistView);});
  $('#catalog-filters').onsubmit=e=>{e.preventDefault();const f=formValues(e.currentTarget);Object.assign(S,{category:f.category,sort:f.sort,availability:f.availability,minPrice:f.minPrice,maxPrice:f.maxPrice,material:f.material,size:f.size,onlyWholesale:!!e.currentTarget.elements.onlyWholesale.checked});if(S.minPrice!==''&&S.maxPrice!==''&&Number(S.minPrice)>Number(S.maxPrice)){message('Harga minimum melebihi maksimum.',true);return;}catalog(S.wishlistView);};
  $('#category').onchange=e=>{S.category=e.target.value;S.material='';S.size='';catalog(S.wishlistView);};
  $('#reset-filters').onclick=()=>{Object.assign(S,{category:'',query:'',sort:'newest',availability:'',material:'',size:'',minPrice:'',maxPrice:'',onlyWholesale:false});$('#search').value='';catalog(S.wishlistView);};
  $('#toggle-filters').onclick=()=>{const panel=$('#catalog-filter-panel');panel.hidden=!panel.hidden;$('#toggle-filters').setAttribute('aria-expanded',String(!panel.hidden));};
  $('#quick-sort').onchange=e=>{S.sort=e.target.value;catalog(S.wishlistView);};
  document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{S.category=b.dataset.category;S.material='';S.size='';catalog(false);$('#product-results').scrollIntoView({behavior:'smooth',block:'start'});});
  const setMode=mode=>{S.mode=mode;invalidateCheckout();save();catalog(S.wishlistView);};
  document.querySelectorAll('[data-catalog-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.catalogMode));
  document.querySelector('[data-wholesale]')?.addEventListener('click',()=>{S.category='';S.material='';S.size='';S.onlyWholesale=false;setMode('grosir');$('#product-results').scrollIntoView({behavior:'smooth',block:'start'});});
  $('#shop-now')?.addEventListener('click',()=>$('#product-results').scrollIntoView({behavior:'smooth',block:'start'}));
}
function catalog(wishlist=false){
  S.wishlistView=wishlist;const options=catalogOptions(S.products,S.category),source=S.products.filter(p=>!wishlist||S.wish.includes(p.id)),products=filterCatalog(source,S,S.mode),unavailable=wishlist?S.wish.filter(id=>!S.products.some(p=>p.id===id)):[],hero=S.products.find(p=>safeURL(photo(p)));
  const select=(name,values,current,all,disabled=false)=>'<label>'+name+'<select name="'+values.id+'" '+(disabled?'disabled':'')+'><option value="">'+all+'</option>'+values.items.map(v=>'<option '+(v===current?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label>';
  show((!S.settings.enabled?'<p class="notice">Toko belum menerima checkout. Anda tetap dapat melihat katalog yang tersedia.</p>':'')+
  (!wishlist?catalogHero()+categoryStrip(S.category,S.mode):'')+
  '<div class="catalog-head" id="product-results"><div><h2>'+(wishlist?'Wishlist Anda':S.mode==='grosir'?'Pilihan grosir':'Katalog produk')+'</h2><p>'+(S.mode==='grosir'?'Gabungkan jumlah varian sesuai aturan produk. 1 kodi = 20 pcs.':'Harga eceran dan grosir mengikuti produk serta variannya.')+'</p></div><span class="meta">'+products.length+' produk</span></div>'+
  '<div class="catalog-toolbar"><div class="mode" aria-label="Jenis harga"><button data-catalog-mode="eceran" class="'+(S.mode==='eceran'?'selected':'')+'" aria-pressed="'+(S.mode==='eceran')+'">Eceran</button><button data-catalog-mode="grosir" class="'+(S.mode==='grosir'?'selected':'')+'" aria-pressed="'+(S.mode==='grosir')+'">Grosir</button></div><button id="toggle-filters" aria-expanded="false" aria-controls="catalog-filter-panel">Filter</button><label>Urutkan<select id="quick-sort">'+[['newest','Terbaru'],['low','Harga terendah'],['high','Harga tertinggi'],['name','Nama produk']].map(([v,t])=>'<option value="'+v+'" '+(S.sort===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label></div><div class="catalog-layout"><aside class="filters" id="catalog-filter-panel" hidden><details class="filter-disclosure"><summary>Filter & urutkan</summary><form id="catalog-filters"><label>Kategori<select id="category" name="category"><option value="">Semua kategori</option>'+CATEGORIES.map(c=>'<option '+(c===S.category?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></label><label>Urutkan<select name="sort">'+[['newest','Terbaru'],['low','Harga terendah'],['high','Harga tertinggi'],['name','Nama produk']].map(([v,t])=>'<option value="'+v+'" '+(S.sort===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><p class="meta">Urutan terbaru mengikuti tanggal produk yang tersedia. Produk tanpa tanggal diurutkan menurut nama.</p><div class="price-range"><label>Harga minimum<input name="minPrice" type="number" min="0" step="1" value="'+esc(S.minPrice)+'" placeholder="Rp"></label><label>Harga maksimum<input name="maxPrice" type="number" min="0" step="1" value="'+esc(S.maxPrice)+'" placeholder="Rp"></label></div><p class="meta">Filter harga memakai harga mulai per pcs/paket pada mode yang dipilih.</p><label>Ketersediaan<select name="availability">'+[['','Semua stok'],['available','Stok tersedia'],['empty','Stok habis']].map(([v,t])=>'<option value="'+v+'" '+(S.availability===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label>'+
  select('Bahan',{id:'material',items:options.materials},S.material,options.materials.length?'Semua bahan':'Data bahan belum tersedia',!options.materials.length)+select('Ukuran',{id:'size',items:options.sizes},S.size,options.sizes.length?'Semua ukuran':'Data ukuran belum tersedia',!options.sizes.length)+
  '<label class="checkline"><input name="onlyWholesale" type="checkbox" '+(S.onlyWholesale?'checked':'')+'> Koleksi Paket Grosir</label><div class="actions"><button class="primary">Terapkan</button><button type="button" id="reset-filters">Reset</button></div></form></details></aside><div class="products">'+
  products.map(p=>'<article class="product"><button class="product-photo" data-product="'+esc(p.id)+'" aria-label="Lihat '+esc(p.name)+'">'+(safeURL(photo(p))?'<img src="'+esc(safeURL(photo(p)))+'" alt="'+esc(p.name)+'" loading="lazy">':'<span class="photo-empty">Foto belum tersedia</span>')+'</button><div class="product-body"><span class="eyebrow">'+esc(p.category)+'</span><h3>'+esc(p.name)+'</h3>'+(p.description?'<p class="card-description">'+esc(p.description)+'</p>':'')+cardPricing(p)+'<span class="meta">'+(p.packPcs>1?'Per paket · '+p.packPcs+' pcs':'Per pcs')+' · '+p.variants.length+' varian</span>'+(!p.variants.some(v=>v.stock>0)?'<span class="badge">Stok habis</span>':'')+'<div class="product-actions"><button data-product="'+esc(p.id)+'">Pilih varian</button><button data-wish="'+esc(p.id)+'" aria-label="'+(S.wish.includes(p.id)?'Hapus dari':'Simpan ke')+' wishlist">'+(S.wish.includes(p.id)?'♥':'♡')+'</button></div></div></article>').join('')+
  unavailable.map(id=>'<article class="product unavailable"><div class="photo-empty">Produk tidak tersedia</div><div class="product-body"><p>Produk ini sudah nonaktif atau tidak lagi dipublikasikan.</p><small>ID '+esc(id)+'</small><button data-wish="'+esc(id)+'">Hapus dari wishlist</button></div></article>').join('')+
  (!products.length&&!unavailable.length?empty(wishlist?'Belum ada produk tersimpan':'Produk tidak ditemukan',wishlist?'Tekan hati pada produk untuk menyimpannya.':'Coba kata pencarian atau filter lain.'):'')+'</div></div>'+(!wishlist&&S.settings.promos?.length?'<div class="promos">'+S.settings.promos.map(p=>'<article class="promo"><div><h2>'+esc(p.title)+'</h2><p>'+esc(p.text)+'</p></div>'+(safeURL(p.image)?'<img src="'+esc(safeURL(p.image))+'" alt="">':'')+'</article>').join('')+'</div>':''));
  document.querySelector('.filter-disclosure').open=true;
  bindCatalog();
}
function cardPricing(p){const r=cardPrice(p,'eceran'),g=cardPrice(p,'grosir');const fmt=v=>(v.varies?'Mulai ':'')+money(v.price);return `<span class="price-label">${S.mode==='grosir'&&g.minimum?'Grosir':'Eceran'}</span><span class="price">${fmt(S.mode==='grosir'?g:r)}</span>${g.minimum?`<span class="meta">${S.mode==='grosir'?'Eceran '+fmt(r):'Grosir '+fmt(g)}</span><span class="meta">Minimum grosir ${g.minimum} pcs</span>`:'<span class="meta">Harga grosir belum tersedia</span>'}`;}
const estimate=items=>catalogEstimate(items,S.products,S.mode,S.settings,S.resellerPrices);
async function detail(pid){const p=S.products.find(p=>p.id===pid);if(!p)return;detailProduct=p;
  const images=productGallery(p).map(url=>({url})),facts=productFacts(p),phone=String(S.settings.whatsapp||'').replace(/\D/g,'').replace(/^0/,'62');
  $('#detail-content').innerHTML=`<div class="detail-layout"><div>${safeURL(photo(p))?`<img id="gallery-main" class="gallery-main" src="${esc(safeURL(photo(p)))}" alt="${esc(p.name)}">`:'<div class="empty">Foto belum tersedia</div>'}<div class="gallery-thumbs">${images.map(i=>`<button data-image="${esc(safeURL(i.url))}" aria-label="Lihat foto"><img src="${esc(safeURL(i.url))}" alt=""></button>`).join('')}</div></div><div><p class="eyebrow">${esc(p.category)}</p><h2>${esc(p.name)}</h2><div class="detail-price">${cardPricing(p)}<span class="meta">Per ${p.packPcs>1?'paket '+p.packPcs+' pcs':'pcs'}</span></div><details class="product-description" open><summary>Deskripsi produk</summary><p class="detail-description" style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(p.description || "Deskripsi belum diisi oleh admin.")}</p></details><p class="meta">SKU ${esc(p.sku)} · ${p.weight>0?p.weight+' gram / unit':'Berat belum dicantumkan'}</p><dl class="product-specs">${[['Bahan',facts.material],['Ukuran',facts.size],['Ketebalan',facts.thickness],['Ketentuan motif/warna',facts.conditions],['Isi paket',p.packPcs+' pcs per unit']].filter(([,v])=>v).map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><p class="detail-description meta">${esc(p.specifications)}</p>
  ${p.tiers.length?`<p>Harga grosir: ${p.tiers.map(t=>`${t.minPcs} pcs → ${money(t.price)}/unit`).join(' · ')}</p><p class="meta">Gabungan minimum: ${p.combine==='all'?'produk dalam kelompok harga yang sama':p.combine==='product'?'semua varian produk ini':'setiap varian'}. Harga final diperiksa saat checkout.</p>`:''}
  <div class="table-wrap"><table><thead><tr><th>Varian</th><th>Harga Eceran / Grosir</th><th>Stok unit</th><th>Jumlah unit</th></tr></thead><tbody>${p.variants.map(v=>`<tr><td>${safeURL(v.image)?`<button data-image="${esc(safeURL(v.image))}" aria-label="Foto varian"><img class="thumb" src="${esc(safeURL(v.image))}" alt=""></button>`:''}<strong>${esc(v.color)} ${esc(v.size)}</strong><br><span class="meta">${esc(v.sku)}</span></td><td>${money(v.pricing?.retail||p.price)}<br>${p.tiers.length?money(v.pricing?.wholesale||p.tiers[0].price):'Ikut eceran'}</td><td>${v.stock}</td><td><input data-variant="${esc(v.id)}" type="number" min="0" max="${v.stock}" step="1" value="0" aria-label="Jumlah ${esc(v.color+' '+v.size)}" ${v.stock===0?'disabled':''}></td></tr>`).join('')}</tbody></table></div><p id="bulk-summary" class="notice">Pilih jumlah varian yang dibutuhkan.</p><p class="meta">${p.promo?'Produk ini mengikuti promo gratis ongkir kurir toko.':'Produk ini tidak mengikuti promo gratis ongkir.'}</p></div></div><section class="panel" style="margin-top:2rem"><h2>Ulasan pembeli</h2><div id="reviews">Memuat ulasan…</div></section>`;
  document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{let img=$('#gallery-main');if(img)img.src=b.dataset.image;});
  document.querySelectorAll('[data-variant]').forEach(i=>i.oninput=()=>{
    const chosen=[...document.querySelectorAll('[data-variant]')].filter(el=>Number(el.value)>0);
    if(!chosen.length){$('#bulk-summary').textContent='Pilih jumlah varian yang dibutuhkan.';return;}
    try{const combined=[...S.cart.map(i=>({...i})),...chosen.map(el=>({productId:pid,variantId:el.dataset.variant,qty:Number(el.value)}))],q=estimate(combined);$('#bulk-summary').textContent=`Total keranjang setelah ditambahkan: ${q.pcs} pcs · ${money(q.subtotal)} (belum termasuk ongkir). Harga mengikuti jumlah gabungan yang memenuhi minimum.`;}catch(e){$('#bulk-summary').textContent=e.message;}
  });
  $('#detail-actions').innerHTML=`${phone?'<a class="button" target="_blank" rel="noopener" href="https://wa.me/'+phone+'?text='+encodeURIComponent('Saya ingin bertanya tentang '+p.name+' ('+p.sku+').')+'">Chat</a>':''}<button id="add-cart">Keranjang</button><button id="buy-now" class="primary">Beli Sekarang</button>`;
  const add=(buy=false)=>{const chosen=[...document.querySelectorAll('[data-variant]')].filter(i=>Number(i.value)>0);if(!chosen.length){$('#bulk-summary').textContent='Isi jumlah minimal satu varian.';document.querySelector('[data-variant]:not([disabled])')?.focus();return;}
    for(const input of chosen){if(!input.checkValidity()){input.reportValidity();return;}const qty=Number(input.value);const v=p.variants.find(v=>v.id===input.dataset.variant),old=S.cart.find(i=>i.productId===pid&&i.variantId===v.id);if((old?.qty||0)+qty>v.stock){$('#bulk-summary').textContent='Jumlah dalam keranjang melebihi stok '+v.color;input.focus();return;}}
    for(const input of chosen){const qty=Number(input.value),variantId=input.dataset.variant,old=S.cart.find(i=>i.productId===pid&&i.variantId===variantId);if(old)old.qty+=qty;else S.cart.push({productId:pid,variantId,qty});}
    invalidateCheckout();save();$('#detail').close();message('Produk ditambahkan ke keranjang.');if(buy)location.hash='checkout';};
  $('#add-cart').onclick=()=>add();$('#buy-now').onclick=()=>add(true);
  if(!$('#detail').open)$('#detail').showModal();
  try{const reviews=await api('reviews',{productId:pid});if(detailProduct?.id===pid)$('#reviews').innerHTML=reviews.length?reviews.map(r=>`<p><strong>${r.rating}/5 · ${esc(r.buyerLabel)}</strong><br>${esc(r.text)}<br><small>${date(r.createdAt)}</small></p>`).join(''):'Belum ada ulasan pembeli.';}catch{$('#reviews').textContent='Ulasan gagal dimuat. Buka kembali produk untuk mencoba lagi.';}
}
function invalidateCheckout(){S.quote=null;localStorage.removeItem('kn-pending');}
function cart(){let q;try{if(S.cart.length)q=estimate(S.cart);}catch{}const valid=!!q&&S.cart.every(i=>S.products.some(p=>p.id===i.productId&&p.variants.some(v=>v.id===i.variantId&&v.stock>=i.qty)));const rows=S.cart.map((i,n)=>{const p=S.products.find(p=>p.id===i.productId),v=p?.variants.find(v=>v.id===i.variantId),priced=q?.items.find(x=>x.productId===i.productId&&x.variantId===i.variantId);return `<tr><td>${safeURL(v?.image||photo(p||{}))?`<img class="cart-photo" src="${esc(safeURL(v?.image||photo(p)))}" alt="">`:""}<strong>${esc(p?.name||'Produk tidak aktif')}</strong><br>${esc(v?[v.color,v.size].join(' / '):'Varian tidak tersedia')}<br><small>${p?.packPcs||'?'} pcs / unit</small>${!v||v.stock<i.qty?'<p class="error">Stok / varian berubah. Sesuaikan keranjang.</p>':''}</td><td>${money(priced?.price)}<br><small>${esc(priced?.priceKind||'Perlu diperiksa')}</small><br><strong>${money(priced?.lineTotal)}</strong></td><td><input data-cart-qty="${n}" type="number" min="1" step="1" max="${v?.stock||0}" value="${i.qty}" aria-label="Jumlah unit"></td><td><button data-remove="${n}">Hapus</button></td></tr>`;}).join('');
  show(`<h1>Keranjang Anda</h1>${S.cart.length?`<div class="panel table-wrap"><table><thead><tr><th>Produk / varian</th><th>Harga per unit / jumlah</th><th>Jumlah unit</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><p><strong>Subtotal ${money(q?.subtotal)}</strong> · ${q?.pcs??'—'} pcs</p>${q&&S.settings.freeShipping?.enabled?promoProgress(q):''}<p class="meta">Harga mengikuti varian dan minimum ${esc(S.mode)}. Voucher, stok dan ongkir dikonfirmasi admin sebelum pembayaran.</p><div class="actions"><a class="button" href="#katalog">Lanjut belanja</a>${valid?'<a class="button primary" href="#checkout">Lanjut checkout →</a>':'<p class="error">Perbaiki stok/varian keranjang sebelum checkout.</p>'}</div>`:empty('Keranjang masih kosong','Pilih produk dari katalog untuk mulai belanja.','<a class="button primary" href="#katalog">Lihat produk</a>')}`);
  document.querySelectorAll('[data-cart-qty]').forEach(i=>i.onchange=()=>{if(!i.checkValidity()){i.reportValidity();return;}S.cart[+i.dataset.cartQty].qty=Number(i.value);invalidateCheckout();save();cart();});
  document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{S.cart.splice(+b.dataset.remove,1);invalidateCheckout();save();cart();});
}
function promoProgress(q){const min=S.settings.freeShipping.minPcs||20,eligible=q.usesReseller&&!S.settings.freeShipping.allowReseller?0:q.eligiblePcs||0;return '<section class="quantity-progress"><strong>'+eligible+' / '+min+' pcs peserta promo</strong><progress value="'+Math.min(eligible,min)+'" max="'+min+'" aria-label="Jumlah pcs peserta promo"></progress><p>'+(eligible<min?'Tambah '+(min-eligible)+' pcs produk peserta untuk memenuhi syarat jumlah.':'Syarat jumlah terpenuhi.')+' Gratis ongkir belum dikonfirmasi: khusus kurir toko dan rute jalan maksimal 25 km, diperiksa admin.</p><small>Minimum grosir mengikuti produk; berbeda dari syarat promo ongkir.</small></section>';}
const addressFields=(a={})=>`<div class="form-grid"><label class="field">Nama penerima<input name="name" value="${esc(a.name||'')}" required maxlength="150" autocomplete="name"></label><label class="field">WhatsApp<input name="phone" value="${esc(a.phone||'')}" required maxlength="30" autocomplete="tel"></label><label class="field wide">Alamat lengkap<textarea name="text" required maxlength="1000" autocomplete="street-address">${esc(a.text||'')}</textarea></label><label class="field">Latitude pin<input type="number" name="lat" step="any" min="-90" max="90" value="${a.lat??''}" required></label><label class="field">Longitude pin<input type="number" name="lng" step="any" min="-180" max="180" value="${a.lng??''}" required></label></div><div class="actions"><button type="button" data-location>Gunakan lokasi saya</button><a href="https://maps.google.com" target="_blank" rel="noopener">Cari pin di Google Maps ↗</a></div><p class="meta">Pastikan pin berada di alamat penerima. Salin koordinat dari peta bila alamat berbeda dari lokasi Anda.</p>`;
const parsedAddress=f=>({name:f.name,phone:f.phone,text:f.text,lat:Number(f.lat),lng:Number(f.lng)});
function bindLocation(){document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>{if(!navigator.geolocation){message('Lokasi tidak tersedia. Isi koordinat dari peta.',true);return;}navigator.geolocation.getCurrentPosition(pos=>{const form=b.closest('form');form.elements.lat.value=pos.coords.latitude;form.elements.lng.value=pos.coords.longitude;form.dispatchEvent(new Event('change',{bubbles:true}));},()=>message('Lokasi tidak dapat diambil. Isi koordinat dari peta.',true));});}
const shippingLabels={store:'Kurir Toko',instant:'Kurir instan — dipesan manual admin',regular:'Ekspedisi reguler — konfirmasi tarif admin',cargo:'Kargo — konfirmasi tarif admin',pickup:'Ambil sendiri di gudang'};
const paymentLabels={transfer:'Transfer bank manual',cash_store:'Tunai kepada kurir toko',cash_pickup:'Tunai di gudang',gateway:'QRIS / VA / e-wallet (gateway)'};
async function checkout(){if(!requireLogin())return;if(!S.cart.length){cart();return;}const v=pageVersion;
  const [account,slots]=await Promise.all([api('myAccount'),api('slots'),loadCatalog()]);if(v!==pageVersion)return;S.account=account;
  const addresses=account.profile?.addresses||[],draft=S.checkoutDraft;
  show(`<h1>Checkout</h1><p class="meta">1. Alamat & pengiriman → 2. Kirim permintaan → 3. Admin mengonfirmasi → 4. Anda menyetujui total</p><div class="two-col"><form id="checkout-form"><section class="panel"><h2>Alamat penerima</h2>${addresses.length?`<label class="field">Alamat tersimpan<select id="saved-address"><option value="">Isi alamat baru</option>${addresses.map((a,i)=>`<option value="${i}">${esc(a.name+' — '+a.text)}</option>`).join('')}</select></label>`:''}${addressFields(draft?.address||addresses[0]||{})}</section><section class="panel"><h2>Pengiriman & pembayaran</h2><label class="field">Metode pengiriman<select name="shippingMethod" id="shipping-method">${Object.entries(S.settings.shipping||{}).filter(([,v])=>v).map(([k])=>`<option value="${k}">${shippingLabels[k]}</option>`).join('')}</select></label><label class="field" id="slot-field">Jadwal kurir toko<select name="slotId"><option value="">${slots.length?'Pilih jadwal tersedia':'Belum ada jadwal tersedia'}</option>${slots.map(s=>`<option value="${s.id}">${date(s.startAt)} – ${date(s.endAt)} (${s.remaining} kuota)</option>`).join('')}</select></label><p class="meta">Slot adalah perkiraan rentang pengantaran, bukan janji waktu tiba tepat.</p><label class="field">Pembayaran<select name="paymentMethod" id="payment-method"></select></label>${S.account?.reseller?.status==='disetujui'?'<label class="field">Asal pesanan<select name="orderOrigin"><option value="website">Belanja melalui Website</option><option value="reseller">Pesanan Reseller</option></select></label>':''}<label class="field">Kode voucher<input name="voucher" maxlength="40" value="${esc(draft?.voucher||'')}"></label><label class="field">Catatan pembeli<textarea name="note" maxlength="1000">${esc(draft?.note||'')}</textarea></label><button class="primary" id="calculate">Hitung & tinjau rincian</button></section></form><aside><section class="panel"><h2>Rincian belanja</h2><div id="quote-summary"><p>Isi alamat dan pengiriman, lalu hitung rincian dari toko.</p></div><button id="place-order" class="primary" hidden>Buat pesanan</button></section></aside></div>`);
  const form=$('#checkout-form');if(draft){form.elements.shippingMethod.value=draft.shippingMethod;form.elements.slotId.value=draft.slotId||'';if(form.elements.orderOrigin)form.elements.orderOrigin.value=draft.orderOrigin||'website';}
  function methods(){const method=form.elements.shippingMethod.value;form.elements.slotId.disabled=method==='store'&&!slots.length;$('#calculate').disabled=method==='store'&&!slots.length;$('#slot-field').hidden=method!=='store';form.elements.slotId.required=method==='store';const prior=form.elements.paymentMethod.value||draft?.paymentMethod;$('#payment-method').innerHTML=Object.entries(S.settings.payments||{}).filter(([k,v])=>v&&(k!=='cash_store'||method==='store')&&(k!=='cash_pickup'||method==='pickup')).map(([k])=>`<option value="${k}">${paymentLabels[k]}</option>`).join('');if([...form.elements.paymentMethod.options].some(o=>o.value===prior))form.elements.paymentMethod.value=prior;}
  methods();$('#shipping-method').onchange=methods;bindLocation();
  $('#saved-address')?.addEventListener('change',e=>{const a=addresses[Number(e.target.value)];if(a)for(const k of ['name','phone','text','lat','lng'])form.elements[k].value=a[k];form.dispatchEvent(new Event('change',{bubbles:true}));});
  function request(){const f=formValues(form);return {items:S.cart.map(i=>({...i})),address:parsedAddress(f),orderOrigin:f.orderOrigin||'website',mode:S.mode,shippingMethod:f.shippingMethod,slotId:f.shippingMethod==='store'?f.slotId:'',paymentMethod:f.paymentMethod,voucher:f.voucher,note:f.note};}
  form.addEventListener('input',()=>{S.quote=null;$('#place-order').hidden=true;$('#quote-summary').textContent='Rincian berubah. Hitung ulang sebelum membuat pesanan.';});
  form.addEventListener('change',()=>{S.quote=null;$('#place-order').hidden=true;S.checkoutDraft=request();localStorage.setItem('kn-checkout',JSON.stringify(S.checkoutDraft));});
  form.onsubmit=e=>{e.preventDefault();busy($('#calculate'),async()=>{const data=request(),q=await api('quote',data);if(JSON.stringify(data)!==JSON.stringify(request()))throw Error('Rincian berubah saat dihitung. Coba lagi.');S.quote={data,q};$('#quote-summary').innerHTML=quoteHTML(q);$('#place-order').hidden=false;$('#place-order').textContent='Kirim permintaan pesanan kepada admin';S.checkoutDraft=data;localStorage.setItem('kn-checkout',JSON.stringify(data));});};
  $('#place-order').onclick=e=>busy(e.currentTarget,async()=>{if(!S.quote)throw Error('Hitung ulang rincian.');const {data,q}=S.quote;if(JSON.stringify(data)!==JSON.stringify(request()))throw Error('Rincian berubah, hitung ulang.');
    const result=await submitOrderRequest({uid:S.user.uid,data:{...data,pricingSignature:q.pricingSignature},storage:localStorage,locks:navigator.locks,send:d=>api('createOrder',d)});S.cart=[];save();localStorage.removeItem('kn-checkout');S.checkoutDraft=null;location.hash='pesanan/'+result.id;message('Permintaan tersimpan. Admin akan memvalidasi harga, stok, jadwal, dan ongkir.');});
}
function quoteHTML(q){return `${q.estimateOnly?'<p class="notice">Perkiraan dari katalog. Harga grosir/reseller, voucher, stok, jadwal, dan ongkir belum disetujui. Tidak ada reservasi sebelum admin mengonfirmasi.</p>':''}${q.items.map(i=>`<div class="summary-row"><span>${esc(i.productName)}<br><small>${esc(i.variant)} · ${i.qty} unit / ${i.pcs} pcs<br>${money(i.price)} · ${label(i.priceKind)}</small></span><strong>${money(i.lineTotal)}</strong></div>`).join('')}<p>${q.pcs} pcs · ${(q.pcs/20).toLocaleString('id-ID')} kodi</p><div class="summary-row"><span>Subtotal</span><span>${money(q.subtotal)}</span></div><div class="summary-row"><span>Diskon</span><span>− ${money(q.discount)}</span></div><div class="summary-row"><span>Ongkir</span><span>${shippingText(q)||money(q.shippingCost)}</span></div><div class="summary-row total"><span>Total</span><span>${q.total==null?'Menunggu konfirmasi admin':money(q.total)}</span></div>${q.shippingCost==null?'<p class="notice">Admin akan mengonfirmasi tarif. Anda perlu menyetujui total final sebelum membayar atau pesanan dikirim.</p>':''}${q.extraFreeShippingPcs?`<p class="meta">Tambah ${q.extraFreeShippingPcs} pcs produk peserta untuk batas jumlah promo; syarat rute dan metode tetap diperiksa.</p>`:''}`;}
function authHTML(){return `<section class="panel narrow"><h1>Selamat datang</h1><p>Masuk untuk checkout dan melihat pesanan Anda.</p><div class="auth-switch"><button data-auth="login" class="selected">Masuk</button><button data-auth="register">Daftar</button></div><form id="auth-form"><label class="field">Email<input name="email" type="email" required autocomplete="email"></label><label class="field">Password<input name="password" type="password" minlength="8" required autocomplete="current-password"></label><button class="primary">Masuk</button></form><button id="reset-password" class="subtle">Lupa password</button></section>`;}
function bindAuth(){let register=false;document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{register=b.dataset.auth==='register';document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('selected',x===b));$('#auth-form button').textContent=register?'Buat akun':'Masuk';$('#auth-form input[name=password]').autocomplete=register?'new-password':'current-password';});$('#auth-form').onsubmit=e=>{e.preventDefault();const f=formValues(e.currentTarget);busy(e.submitter,()=>login(f.email,f.password,register));};$('#reset-password').onclick=e=>busy(e.currentTarget,async()=>{const c=await connect(),email=$('#auth-form input[name=email]').value;if(!email)throw Error('Isi email terlebih dahulu.');await c.auth.sendPasswordResetEmail(c.a,email);message('Jika email terdaftar, tautan pemulihan akan dikirim.');});}
async function account(){if(!requireLogin())return;const r=await api('myAccount');S.account=r;show(`<div class="order-head"><h1>Akun saya</h1><button id="logout">Keluar</button></div><p>${esc(S.user.email)}</p><section class="panel"><form id="profile-form"><div class="form-grid"><label class="field">Nama akun<input name="profileName" required value="${esc(r.profile?.name||'')}"></label><label class="field">WhatsApp akun<input name="profilePhone" value="${esc(r.profile?.phone||'')}"></label></div><h2>Alamat baru</h2>${addressFields()}<button class="primary">Simpan profil & tambah alamat</button></form></section><section class="panel"><h2>Alamat tersimpan</h2>${(r.profile?.addresses||[]).map((a,i)=>`<div class="summary-row"><span><strong>${esc(a.name)}</strong><br>${esc(a.text)}<br>${esc(a.phone)}</span><button data-delete-address="${i}">Hapus</button></div>`).join('')||'<p>Belum ada alamat tersimpan.</p>'}</section>`);bindLocation();$('#logout').onclick=()=>busy($('#logout'),()=>logout());$('#profile-form').onsubmit=e=>{e.preventDefault();const f=formValues(e.currentTarget);busy(e.submitter,async()=>{await api('profile',{name:f.profileName,phone:f.profilePhone,addresses:[...(r.profile?.addresses||[]),parsedAddress(f)]});message('Alamat tersimpan.');await account();});};document.querySelectorAll('[data-delete-address]').forEach(b=>b.onclick=()=>busy(b,async()=>{await api('profile',{...r.profile,addresses:r.profile.addresses.filter((a,i)=>i!==Number(b.dataset.deleteAddress))});await account();}));}
async function reseller(){if(!requireLogin())return;const r=await api('myAccount');S.account=r;show(`<h1>Reseller Kubah Nabawi</h1><p><a class="button" href="reseller.html?v=kebijakan-20260913-r9">Resi & pembayaran reseller</a></p><section class="panel narrow"><h2>Status: ${esc(label(r.reseller?.status))}</h2><p>${esc(r.reseller?.note||'Harga reseller tersedia setelah pengajuan disetujui toko dan minimum pembelian terpenuhi.')}</p>${!r.reseller||r.reseller.status==='ditolak'?`<form id="reseller-form">${[['name','Nama lengkap'],['phone','WhatsApp'],['storeName','Nama toko'],['address','Alamat'],['channel','Kanal penjualan / tautan toko']].map(([name,text])=>`<label class="field">${text}<input name="${name}" required maxlength="500"></label>`).join('')}<button class="primary">Kirim pengajuan</button></form>`:''}</section>`);$('#reseller-form')?.addEventListener('submit',e=>{e.preventDefault();busy(e.submitter,async()=>{await api('reseller',formValues(e.currentTarget));message('Pengajuan dikirim.');await reseller();});});}
const packageIcon='<svg class="empty-package" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 14 18-9 18 9v21l-18 9L6 35V14Zm0 0 18 9 18-9M24 23v21M15 10l18 9v9"/></svg>';
const orderTabs=[['all','Semua'],['menunggu_konfirmasi_admin','Menunggu Konfirmasi'],['menunggu_pembayaran','Menunggu Pembayaran'],['perlu_verifikasi','Perlu Verifikasi'],['diproses','Diproses'],['dikirim','Dikirim'],['selesai','Selesai'],['dibatalkan','Dibatalkan']];
function orderPhoto(i){const p=S.products.find(p=>p.id===i.productId),v=p?.variants.find(v=>v.id===i.variantId);return safeURL(i.image||v?.image||photo(p||{}));}
const trackingText=o=>o.shippingMethod==='pickup'?'Ambil sendiri':o.trackingNumber||'Menunggu Resi';
async function orders(){if(!requireLogin())return;const v=pageVersion,rows=await api('myOrders');if(v!==pageVersion)return;rows.sort((a,b)=>timestamp(b.createdAt)-timestamp(a.createdAt));
 const visible=rows.filter(o=>S.orderTab==='all'||o.status===S.orderTab);
 show('<div class="order-head"><h1>Pesanan Saya</h1><button id="refresh-orders">Segarkan</button></div><nav class="order-tabs" aria-label="Status pesanan">'+orderTabs.map(([id,title])=>'<button data-order-tab="'+id+'" class="'+(id===S.orderTab?'selected':'')+'">'+title+' ('+(id==='all'?rows.length:rows.filter(o=>o.status===id).length)+')</button>').join('')+'</nav>'+
 visible.map(o=>'<article class="panel"><div class="order-head"><strong>'+(o.requestPending?'Pengajuan ':'Invoice ')+esc(o.invoiceNo||o.requestNumber||o.id)+'</strong><span class="badge">'+esc(label(o.status))+'</span></div><p>'+date(o.createdAt)+' · '+o.items.length+' varian</p>'+o.items.map(i=>'<div class="order-products">'+(orderPhoto(i)?'<img src="'+esc(orderPhoto(i))+'" alt="'+esc(i.productName)+'" loading="lazy">':'')+'<span>'+esc(i.productName)+'<br><small>'+esc(i.variant)+' · '+i.qty+' unit'+(i.pcs?' / '+i.pcs+' pcs':'')+'</small></span></div>').join('')+'<p>Pengiriman: '+esc(shippingLabels[o.shippingMethod]||o.shippingMethod)+'<br>Nomor resi: <strong>'+esc(trackingText(o))+'</strong></p><div class="order-head"><span>Total <strong>'+(o.total==null?'Menunggu konfirmasi admin':money(o.total))+'</strong><br>Pembayaran: '+esc(label(o.paymentStatus))+'</span><div class="actions"><a class="button primary" href="#pesanan/'+o.id+'">Lihat pesanan →</a><button data-reorder="'+o.id+'">Beli Lagi</button></div></div></article>').join('')+
 (!visible.length?empty('Belum ada pesanan',rows.length?'Belum ada pesanan pada status ini.':'Pesanan yang Anda buat akan tampil di sini.',packageIcon+'<p><a class="button primary" href="#katalog">Mulai Belanja</a></p>'):''));
 $('#refresh-orders').onclick=e=>busy(e.currentTarget,orders);document.querySelectorAll('[data-order-tab]').forEach(b=>b.onclick=()=>{S.orderTab=b.dataset.orderTab;orders().catch(e=>message(e.message,true));});document.querySelectorAll('[data-reorder]').forEach(b=>b.onclick=()=>busy(b,()=>reorder(rows.find(o=>o.id===b.dataset.reorder))));
}
async function reorder(o){await loadCatalog();S.resellerPrices=await api('resellerPrices');const r=reorderCart(o,S.products,S.cart,S.mode,S.settings,S.resellerPrices);S.cart=r.cart;invalidateCheckout();save();location.hash='keranjang';message((r.notes.length?r.notes.join(' '):'Barang yang tersedia ditambahkan dengan harga terbaru.')+' Periksa keranjang; belum ada pesanan atau tagihan baru.',!!r.notes.length);}
async function orderDetail(oid){if(!requireLogin())return;const v=pageVersion,o=await api('getOrder',{orderId:oid});if(v!==pageVersion)return;if(o.id!==oid){location.hash='pesanan/'+o.id;return;}
  const unpaid=o.paidAmount===0&&o.totalAccepted&&o.shippingState==='confirmed'&&o.status!=='dibatalkan';
  show(`<div class="order-head"><div><a href="#pesanan">← Pesanan Saya</a><h1>${o.requestPending?'Pengajuan ':'Invoice '}${esc(o.invoiceNo||o.requestNumber||o.id)}</h1></div><button id="refresh-order">Segarkan status</button></div><div class="two-col"><div><section class="panel"><span class="badge">${esc(label(o.status))}</span><h2>${esc(o.totalAccepted&&o.detailStatus==='Menunggu persetujuan total'?'Menunggu pembayaran / konfirmasi tunai':o.detailStatus)}</h2><p>Pembayaran: <strong>${esc(label(o.paymentStatus))}</strong>${o.paymentMethod?.startsWith('cash_')?' · '+esc(label(o.cashStatus)):''}</p>${o.expiresAt?`<p class="meta">Batas konfirmasi / pembayaran: ${date(o.expiresAt)}</p>`:''}<p>${esc(o.customerName)} · ${esc(o.phone)}<br>${esc(o.address)}</p><p>${esc(shippingLabels[o.shippingMethod])}${o.slot?'<br>'+date(o.slot.startAt)+' – '+date(o.slot.endAt):''}</p><p>Kurir / layanan: ${esc(o.courier||'Menunggu penetapan admin')}<br>Nomor resi: <strong>${esc(trackingText(o))}</strong></p>${o.cancelReason||o.failureReason?`<p class="notice">${esc(o.cancelReason||o.failureReason)}</p>`:''}<ol class="timeline">${(o.statusHistory||[]).map(h=>`<li>${esc(label(h.status))}${h.note?' · '+esc(h.note):''}<small>${date(h.at)}</small></li>`).join('')}</ol></section>
  ${o.shippingState==='confirmed'&&!o.totalAccepted&&o.status!=='dibatalkan'?`<section class="panel"><h2>Setujui total final</h2><p>Ongkir: ${money(o.shippingCost)} · Total: ${money(o.total)}</p><button id="accept-total" class="primary">Setuju total ${money(o.total)}</button></section>`:''}
  ${o.salesChannel==='reseller'&&o.paymentMethod==='transfer'?'<section class="panel"><h2>Dokumen dan pembayaran reseller</h2><p>Unggah bukti dan lihat sisa tagihan di halaman Reseller. Admin memeriksa dana sebelum menyetujui pembayaran.</p><a class="button" href="reseller.html?v=kebijakan-20260913-r9#pembayaran">Buka pembayaran reseller</a></section>':''}
  ${unpaid&&o.paymentMethod==='transfer'&&o.salesChannel!=='reseller'?`<section class="panel"><h2>Transfer & bukti pembayaran</h2>${(S.settings.banks||[]).map(b=>`<p><strong>${esc(b.bank)} ${esc(b.number)}</strong><br>a.n. ${esc(b.name)}</p>`).join('')}<p class="notice">Unggah bukti privat belum aktif. Kirim foto bukti secara manual ke admin melalui tombol Bantuan WhatsApp, lalu catat referensi di sini. Jangan masukkan nomor kartu atau password.</p><form id="proof-form"><label class="field">Nominal transfer<input name="amount" type="number" min="1" value="${o.total}" required></label><label class="field">Referensi / catatan transfer<input name="reference" maxlength="300" required></label><button class="primary">Saya sudah transfer — minta pemeriksaan admin</button></form><p class="meta">Pemberitahuan ini tidak membuat pesanan lunas. Admin harus memeriksa dana masuk.</p></section>`:''}
  ${unpaid&&o.paymentMethod==='gateway'?'<button id="gateway" class="primary">Buka pembayaran gateway</button>':''}
  <section class="panel"><h2>Retur & komplain</h2><p><a href="informasi.html?v=kebijakan-20260913-r9#retur" target="_blank" rel="noopener">Kebijakan Retur, Penukaran, dan Pengembalian Dana</a></p>${(o.claimRequests||[]).map(r=>`<p class="notice">Pengajuan ${esc(r.payload.reason)}: ${esc(r.status)} ${esc(r.reviewNote||'')}${evidenceButtons(r.payload.evidence)}</p>`).join('')}<p class="meta">${esc(APPROVED_POLICY_SUMMARY)}</p>${(o.claims||[]).map(r=>`<article class="panel"><strong>${esc(RETURN_STAGES[caseStage(r)]||label(r.status))} · ${esc(r.reason)}</strong><p>${esc(r.description)}</p><p>${esc(r.resolutionNote||'')}</p><p>${esc(r.returnInstructions||'')}</p>${(r.stageHistory||[]).map(h=>`<p>${esc(RETURN_STAGES[h.stage]||h.stage)} · ${esc(h.note)}</p>`).join('')}${r.refundAmount?`<p>Refund ${money(r.refundAmount)} · ${esc(r.refundStatus)}</p>`:''}${r.trackingNumber?`<p>Referensi penggantian: ${esc(r.trackingNumber)}</p>`:''}${evidenceButtons(r.evidence)}${(r.evidenceRevisions||[]).map(v=>`<p>Revisi ${v.revision} · ${esc(v.note)}</p>${evidenceButtons(v.evidence)}`).join('')}${(r.messages||[]).map(m=>`<p><strong>${esc(m.by)}</strong>: ${esc(m.text)} <small>${date(m.at)}</small></p>`).join('')}<form data-reply="${r.id}" class="inline-form"><label class="field">Tanggapan<input name="text" required maxlength="3000"></label><button>Kirim</button></form></article>`).join('')||((o.claimRequests||[]).length?'':'<p>Belum ada pengajuan.</p>')}
  ${['dikirim','selesai'].includes(o.status)?`<details><summary>Ajukan Retur/Komplain</summary><form id="claim-form"><label class="field">Barang<select name="item">${o.items.map((i,n)=>`<option value="${n}">${esc(i.productName+' / '+i.variant)}</option>`).join('')}</select></label><label class="field">Jumlah unit bermasalah<input name="qty" type="number" min="1" step="1" value="1" required></label><label class="field">Alasan<select name="reason">${RETURN_REASONS.map(r=>`<option>${r}</option>`).join('')}</select></label><label class="field">Penjelasan<textarea name="description" maxlength="3000" required></textarea></label><div id="claim-upload"></div><button class="primary">Ajukan</button></form></details>`:''}</section>
  ${o.status==='selesai'?`<section class="panel"><h2>Ulas produk yang dibeli</h2><form id="review-form"><label class="field">Produk<select name="productId">${[...new Map(o.items.map(i=>[i.productId,i])).values()].map(i=>`<option value="${i.productId}">${esc(i.productName)}</option>`).join('')}</select></label><label class="field">Nilai<select name="rating">${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label><label class="field">Ulasan<textarea name="text" required maxlength="2000"></textarea></label><button>Kirim ulasan</button></form></section>`:''}</div><aside><section class="panel"><h2>Rincian pesanan</h2>${quoteHTML(o)}<button id="reorder">Beli Lagi</button>${['menunggu_pembayaran','perlu_verifikasi'].includes(o.status)?'<form id="cancel-form"><label class="field">Alasan pembatalan<input name="reason" required maxlength="500"></label><button>Ajukan pembatalan</button></form>':''}${o.refundStatus?`<p>Refund pembatalan: ${esc(o.refundStatus)} · ${money(o.refundedAmount)}</p>`:''}</section></aside></div>`);
  const reload=()=>orderDetail(oid);$('#refresh-order').onclick=e=>busy(e.currentTarget,reload);$('#reorder').onclick=e=>busy(e.currentTarget,()=>reorder(o));
  $('#accept-total')?.addEventListener('click',e=>busy(e.currentTarget,async()=>{await api('acceptTotal',{orderId:oid,total:o.total,quoteVersion:o.quoteVersion});await reload();}));
  $('#proof-form')?.addEventListener('submit',e=>{e.preventDefault();const values=formValues(e.currentTarget);busy(e.submitter,async()=>{await api('proof',{orderId:oid,amount:Number(values.amount),reference:values.reference});message('Pemberitahuan transfer tersimpan. Dana belum diverifikasi.');await reload();});});
  $('#gateway')?.addEventListener('click',e=>busy(e.currentTarget,async()=>{const r=await api('gatewaySession',{orderId:oid});location.assign(r.redirectUrl);}));
  $('#cancel-form')?.addEventListener('submit',e=>{e.preventDefault();const reason=formValues(e.currentTarget).reason;busy(e.submitter,async()=>{await api('cancel',{orderId:oid,reason});message('Permintaan pembatalan tersimpan. Admin akan memeriksa dan melepaskan stok bila disetujui.');await reload();});});
  mountBuyerRevisions($('#content'),o);
  const claimForm=$('#claim-form'),claimUpload=claimForm?mountClaimUpload($('#claim-upload'),o):null;
  if(claimForm){const qty=claimForm.elements.qty;const quantity=()=>{const i=o.items[Number(claimForm.elements.namedItem('item').value)];qty.max=i.qty-(o.claimedQuantities?.[i.productId+'_'+i.variantId]||0);};claimForm.elements.namedItem('item').onchange=quantity;quantity();}
  claimForm?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,f=formValues(form);busy(e.submitter,async()=>{const evidence=await claimUpload.files(Number(f.item)),i=o.items[Number(f.item)],key=form.dataset.key||crypto.randomUUID();form.dataset.key=key;const result=await api('claim',{orderId:oid,key,items:[{productId:i.productId,variantId:i.variantId,qty:Number(f.qty)}],reason:f.reason,description:f.description,evidence});message('Pengajuan tersimpan: '+result.id+'. Menunggu pemeriksaan admin.');await reload();});});
  document.querySelectorAll('[data-reply]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const text=formValues(f).text;busy(e.submitter,async()=>{const key=f.dataset.key||crypto.randomUUID();f.dataset.key=key;await api('claimAction',{claimId:f.dataset.reply,operation:'reply',text,key});await reload();});});
  document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>busy(b,()=>viewEvidence(b.dataset.evidence)));
  $('#review-form')?.addEventListener('submit',e=>{e.preventDefault();const f=formValues(e.currentTarget);busy(e.submitter,async()=>{await api('review',{orderId:oid,...f,rating:Number(f.rating)});message('Ulasan tersimpan.');});});
}
async function route(){pageVersion++;$('#detail').close();const [page='katalog',oid]=location.hash.slice(1).split('/');try{
 if(page==='kerjasama'){const version=pageVersion,c=await connect();await renderSupplierPartnership({store:manualStore(c),c,user:S.user,isCurrent:()=>version===pageVersion});return;}
  if(page==='katalog'||page==='wishlist'){if(page==='katalog'){const category=oid?decodeURIComponent(oid):'';S.category=CATEGORIES.includes(category)?category:'';}catalog(page==='wishlist');}else if(page==='keranjang')cart();else if(page==='checkout')await checkout();else if(page==='akun')await account();else if(page==='reseller')await reseller();else if(page==='pesanan')oid?await orderDetail(oid):await orders();else catalog();
}catch(e){show(empty('Halaman belum dapat dimuat',e.message,'<button id="retry">Coba lagi</button>'));$('#retry').onclick=route;message(e.message,true);}}
window.addEventListener('storage',e=>{if(e.key==='kn-cart'){S.cart=read('kn-cart',[]);S.quote=null;$('#cart-count').textContent=qtyCount();if(['#keranjang','#checkout'].includes(location.hash))route();}});
$('#menu-toggle').onclick=()=>{const menu=$('#shop-menu');menu.hidden=!menu.hidden;$('#menu-toggle').setAttribute('aria-expanded',String(!menu.hidden));};
$('#shop-menu').querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{$('#shop-menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#shop-menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');}});
$('#search-form').onsubmit=e=>{e.preventDefault();S.query=$('#search').value;if(location.hash==='#katalog')catalog();else location.hash='katalog';};
document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===S.mode);b.onclick=()=>{S.mode=b.dataset.mode;invalidateCheckout();save();document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));route();};});
$('#detail .dialog-close').onclick=()=>$('#detail').close();window.addEventListener('hashchange',route);window.addEventListener('offline',()=>message('Koneksi terputus. Keranjang tetap disimpan.',true));
save();
async function boot(){try{await loadCatalog();const c=await connect();c.auth.onAuthStateChanged(c.a,async u=>{S.user=u;message('');S.resellerPrices=[];$('#account-label').textContent=u?'Akun Saya':'Masuk / Daftar';$('#account-button').setAttribute('aria-label',u?'Akun Saya':'Masuk / Daftar');if(u){try{S.resellerPrices=await api('resellerPrices');}catch{}}await route();});}catch(e){show(empty('Toko belum dapat terhubung','Periksa koneksi Anda, lalu coba kembali.','<button id="boot-retry">Coba lagi</button>'));$('#boot-retry').onclick=boot;message(e.message,true);}}
// Poll only the list; never overwrite a checkout, claim draft, or evidence upload.
setInterval(()=>{if(location.hash==='#pesanan'&&S.user&&navigator.onLine)orders().catch(e=>message(e.message,true));},30000);
boot();
