import {check,id,str,num,hash,publicProduct} from './manual-domain.js?v=admin-lengkap-20260909-r2';
import {day,skuId} from './planning-domain.js?v=admin-lengkap-20260909-r2';
export const supplierDocumentId=(sid,kind,number)=>kind+'-'+hash([sid,String(number).trim().toUpperCase()]).slice(0,32);
export function supplierService(store,{stamp=()=>new Date().toISOString()}={}){
 const admin=c=>check(c?.uid&&c.role==='admin','Akses Supplier hanya untuk admin berwenang.','permission-denied');
 const positive=v=>num(Number(v),1),text=(v,n=200)=>str(String(v??''),n,true);
 const amount=v=>num(Number(v));
 async function retry(fn){try{return await store.run(fn);}catch(e){if(!String(e.code).includes('permission-denied'))throw e;return store.run(fn);}}
 function file(f,sid,did,kind){check(f&&f.size>0&&f.size<=2097152&&/^[a-f0-9]{64}$/.test(f.sha256),'Unggah dokumen privat maksimal 2 MB terlebih dahulu.');const ext={'application/pdf':'pdf','image/jpeg':'jpg','image/png':'png'}[f.mime];check(ext&&f.objectName===`supplier/${sid}/${did}/${kind}/${f.sha256}.${ext}`,'Identitas dokumen tidak sesuai Supplier.');return {objectName:f.objectName,sha256:f.sha256,mime:f.mime,size:f.size};}
 async function supplier(tx,sid){const s=await tx.get('suppliers/'+id(sid));check(s?.active,'Supplier tidak tersedia atau nonaktif.');return s;}
 const audit=(tx,key,c,type,data)=>tx.set('supplierEvents/'+key,{type,...data,actor:c.uid,at:stamp()});
 const balance=b=>{b.remaining=b.amount-b.verifiedPaid-b.credits;check(b.remaining>=0,'Alokasi melebihi sisa tagihan.');b.status=b.remaining===0?'lunas':b.verifiedPaid+b.credits>0?'sebagian':'belum_dibayar';return b;};
 function journal(tx,key,c,type,value,desc,sid,related){tx.set('transactions/'+key,{type,amount:value,category:type==='keluar'?'Pembayaran Supplier':'Pengembalian Supplier',description:desc,supplierId:sid,supplierEventId:related.id,supplierPaymentId:related.id.replace(/^(pay-|reverse-)/,''),managed:true,verifiedBy:c.uid,createdAt:stamp(),date:related.date||stamp()});}
 async function saveSupplier(c,d){admin(c);const sid=d.id?id(d.id):'S-'+skuId(d.code),code=text(d.code,50).toUpperCase();return retry(async tx=>{const old=await tx.get('suppliers/'+sid),lock=await tx.get('supplierCodes/'+skuId(code));check(!lock||lock.supplierId===sid,'Kode Supplier sudah digunakan.');check((old?.revision||0)===(d.expectedRevision||0),'Supplier berubah. Muat ulang.');const s={code,name:text(d.name,150),pic:text(d.pic||d.name,150),phone:str(d.phone||'',30),email:str(d.email||'',150),address:str(d.address||'',1000),category:str(d.category||'',100),paymentTerms:num(Number(d.paymentTerms||0),0,365),active:d.active===true,revision:(old?.revision||0)+1,createdAt:old?.createdAt||stamp(),updatedAt:stamp(),updatedBy:c.uid};tx.set('suppliers/'+sid,s);tx.set('supplierCodes/'+skuId(code),{supplierId:sid,code});audit(tx,'supplier-'+sid+'-'+s.revision,c,'supplier',{supplierId:sid,before:old||null,after:s});return {id:sid};});}
 async function submitReceipt(c,d){admin(c);const sid=id(d.supplierId),did=supplierDocumentId(sid,'receipt',d.number),submissionHash=hash({supplierId:sid,number:String(d.number).trim().toUpperCase(),date:d.date,poRef:d.poRef||'',lines:d.lines,file:d.file});return retry(async tx=>{const s=await supplier(tx,sid),old=await tx.get('supplierReceipts/'+did);if(old?.submissionHash===submissionHash&&old.status!=='correction')return {id:did,reused:true};check(!old||old.status==='correction','Nomor surat jalan sudah tersimpan; buka dokumen tersebut.');check(Array.isArray(d.lines)&&d.lines.length>0&&d.lines.length<=20,'Isi 1–20 baris barang.');check(new Set(d.lines.map(x=>x.productId)).size<=6,'Maksimal 6 produk per surat jalan. Pisahkan surat jalan bila lebih.');
  const lines=[];for(const l of d.lines){const p=await tx.get('products/'+id(l.productId)),v=p?.variants?.find(v=>v.id===l.variantId);check(v,'Produk/varian tidak tersedia.');const expected=positive(l.expected),received=amount(l.received),damaged=amount(l.damaged);check(damaged<=received,'Jumlah rusak melebihi jumlah diterima.');lines.push({productId:l.productId,variantId:v.id,productName:p.name,sku:v.sku||p.sku||'',expected,received,damaged,good:received-damaged,shortage:Math.max(0,expected-received),unitPrice:positive(l.unitPrice),packPcs:positive(l.packPcs)});}
  check(new Set(lines.map(l=>l.productId+'/'+l.variantId)).size===lines.length,'Gabungkan baris varian yang sama.');const revision=(old?.revision||0)+1,record={submissionHash,supplierId:sid,supplierName:s.name,number:text(d.number),date:day(d.date),poRef:str(d.poRef||'',200),lines,file:file(d.file,sid,did,'receipt'),status:'pending',revision,createdAt:old?.createdAt||stamp(),updatedAt:stamp(),createdBy:c.uid};tx.set('supplierReceipts/'+did,record);audit(tx,did+'-r'+revision,c,'receipt_revision',{supplierId:sid,documentId:did,before:old||null,document:record});return {id:did};});}
 async function reviewReceipt(c,d){admin(c);return retry(async tx=>{const rid=id(d.id),r=await tx.get('supplierReceipts/'+rid),eid='receive-'+rid,event=await tx.get('supplierEvents/'+eid);if(event&&d.approve)return {id:rid,reused:true};check(r?.status==='pending'&&r.revision===d.revision,'Versi surat jalan berubah atau sudah diperiksa.');const reason=text(d.reason,1000);
  if(!d.approve){tx.update('supplierReceipts/'+rid,{status:'correction',reviewReason:reason,reviewedBy:c.uid,reviewedAt:stamp()});audit(tx,rid+'-review-'+r.revision,c,'receipt_correction',{supplierId:r.supplierId,documentId:rid,reason});return {id:rid};}
  check(d.goodsChecked===true,'Periksa barang fisik terlebih dahulu.');const products=new Map();for(const l of r.lines)if(!products.has(l.productId)){const p=await tx.get('products/'+l.productId);check(p,'Produk hilang.');products.set(l.productId,p);}
  for(const l of r.lines){const v=products.get(l.productId).variants.find(v=>v.id===l.variantId);check(v,'Varian hilang.');const pack=products.get(l.productId).website?.packPcs||1;l.stockUnits=l.good*l.packPcs/pack;check(Number.isSafeInteger(l.stockUnits),'Kemasan pembelian tidak menghasilkan unit stok utuh. Periksa konversi pcs.');v.stock=amount(v.stock)+l.stockUnits;num(v.stock);}
  for(const [pid,p] of products){p.totalStock=p.variants.reduce((s,v)=>s+v.stock,0);p.revision=(p.revision||0)+1;tx.set('products/'+pid,p);const pub=publicProduct(p,pid);if(pub)tx.set('catalog/'+pid,pub);else tx.delete('catalog/'+pid);}
  for(const [n,l] of r.lines.entries())tx.set('supplierPriceHistory/'+rid+'-'+n,{supplierId:r.supplierId,supplierName:r.supplierName,receiptId:rid,documentNo:r.number,date:r.date,...l,pricePerPcs:l.unitPrice/l.packPcs,at:stamp(),actor:c.uid});
  tx.update('supplierReceipts/'+rid,{status:'verified',lines:r.lines,inspectionNote:reason,reviewedBy:c.uid,reviewedAt:stamp()});audit(tx,eid,c,'receipt_verified',{supplierId:r.supplierId,documentId:rid,lines:r.lines,reason});return {id:rid};});}
 async function submitInvoice(c,d){admin(c);const sid=id(d.supplierId),did=supplierDocumentId(sid,'invoice',d.number),submissionHash=hash({supplierId:sid,number:String(d.number).trim().toUpperCase(),date:d.date,dueDate:d.dueDate,amount:Number(d.amount),receiptIds:d.receiptIds||[],poRef:d.poRef||'',file:d.file});return retry(async tx=>{const s=await supplier(tx,sid),old=await tx.get('supplierInvoices/'+did);if(old?.submissionHash===submissionHash&&old.status!=='correction')return {id:did,reused:true};check(!old||old.status==='correction','Nomor nota sudah ada; gunakan dokumen yang tersimpan.');const receipts=[...new Set(d.receiptIds||[])];check(receipts.length<=10,'Maksimal 10 surat jalan.');for(const rid of receipts){const r=await tx.get('supplierReceipts/'+id(rid));check(r?.supplierId===sid&&r.status==='verified','Surat jalan harus milik Supplier dan sudah diperiksa.');}
  const total=positive(d.amount),date=day(d.date),dueDate=day(d.dueDate);check(dueDate>=date,'Jatuh tempo sebelum tanggal nota.');const revision=(old?.revision||0)+1,record={submissionHash,supplierId:sid,supplierName:s.name,number:text(d.number),date,dueDate,poRef:str(d.poRef||'',200),receiptIds:receipts,amount:total,verifiedPaid:0,credits:0,remaining:total,status:'pending',file:file(d.file,sid,did,'invoice'),revision,createdAt:old?.createdAt||stamp(),createdBy:c.uid};tx.set('supplierInvoices/'+did,record);audit(tx,did+'-r'+revision,c,'invoice_revision',{supplierId:sid,documentId:did,before:old||null,document:record});return {id:did};});}
 async function reviewInvoice(c,d){admin(c);return retry(async tx=>{const iid=id(d.id),b=await tx.get('supplierInvoices/'+iid);check(b&&b.status==='pending'&&b.revision===d.revision,'Nota sudah diperiksa atau berubah.');const reason=text(d.reason,1000);tx.update('supplierInvoices/'+iid,{status:d.approve?'belum_dibayar':'correction',reviewReason:reason,reviewedBy:c.uid,reviewedAt:stamp()});audit(tx,iid+'-review-'+b.revision,c,'invoice_review',{supplierId:b.supplierId,documentId:iid,approved:!!d.approve,reason});return {id:iid};});}
 async function submitPayment(c,d){admin(c);const sid=id(d.supplierId),bankRef=text(d.reference,200),did=supplierDocumentId(sid,'payment',bankRef),submissionHash=hash({supplierId:sid,reference:bankRef.toUpperCase(),date:d.date,amount:Number(d.amount),kind:d.kind,method:d.method,allocations:d.allocations,file:d.file});return retry(async tx=>{const s=await supplier(tx,sid),old=await tx.get('supplierPayments/'+did);if(old?.submissionHash===submissionHash&&old.status!=='correction')return {id:did,reused:true};check(!old||old.status==='correction','Referensi pembayaran sudah digunakan. Buka catatan yang ada.');check(['DP','Cicilan','Pelunasan'].includes(d.kind),'Jenis pembayaran tidak valid.');check(Array.isArray(d.allocations)&&d.allocations.length>0&&d.allocations.length<=8,'Alokasikan pembayaran ke 1–8 tagihan.');const allocations=[];for(const a of d.allocations){const b=await tx.get('supplierInvoices/'+id(a.invoiceId));check(b?.supplierId===sid&&['belum_dibayar','sebagian'].includes(b.status),'Tagihan belum disetujui atau tidak memiliki saldo.');const value=positive(a.amount);check(value<=b.remaining,'Alokasi melebihi sisa tagihan.');allocations.push({invoiceId:a.invoiceId,invoiceNo:b.number,amount:value});}check(new Set(allocations.map(a=>a.invoiceId)).size===allocations.length,'Tagihan dialokasikan dua kali.');const value=positive(d.amount);check(allocations.reduce((s,a)=>s+a.amount,0)===value,'Jumlah alokasi harus sama dengan nominal pembayaran.');const revision=(old?.revision||0)+1,record={submissionHash,supplierId:sid,supplierName:s.name,date:day(d.date),amount:value,kind:d.kind,method:text(d.method,80),reference:bankRef,allocations,file:file(d.file,sid,did,'payment'),status:'pending',revision,createdBy:c.uid,createdAt:old?.createdAt||stamp()};tx.set('supplierPayments/'+did,record);audit(tx,did+'-r'+revision,c,'payment_revision',{supplierId:sid,documentId:did,before:old||null,document:record});return {id:did};});}
 async function reviewPayment(c,d){admin(c);return retry(async tx=>{const pid=id(d.id),p=await tx.get('supplierPayments/'+pid),eid='pay-'+pid,done=await tx.get('supplierEvents/'+eid);if(done&&d.approve)return {id:pid,reused:true};check(p?.status==='pending'&&p.revision===d.revision,'Pembayaran sudah ditinjau atau revisinya berubah.');const reason=text(d.reason,1000);
  if(!d.approve){tx.update('supplierPayments/'+pid,{status:'correction',reviewReason:reason,reviewedBy:c.uid,reviewedAt:stamp()});audit(tx,pid+'-review-'+p.revision,c,'payment_correction',{supplierId:p.supplierId,documentId:pid,reason});return {id:pid};}
  check(d.fundsChecked===true,'Periksa dana keluar pada rekening/kas terlebih dahulu.');const invoices=[];for(const a of p.allocations){const b=await tx.get('supplierInvoices/'+a.invoiceId);check(b?.supplierId===p.supplierId&&['belum_dibayar','sebagian'].includes(b.status)&&a.amount<=b.remaining,'Saldo tagihan berubah; perbaiki alokasi.');invoices.push([a.invoiceId,balance({...b,verifiedPaid:b.verifiedPaid+a.amount})]);}
  for(const [iid,b] of invoices)tx.set('supplierInvoices/'+iid,b);tx.update('supplierPayments/'+pid,{status:'verified',reviewReason:reason,reviewedBy:c.uid,reviewedAt:stamp()});audit(tx,eid,c,'payment_verified',{supplierId:p.supplierId,documentId:pid,amount:p.amount,allocations:p.allocations,date:p.date,reason});journal(tx,'supplier_'+pid,c,'keluar',p.amount,'Pembayaran '+p.supplierName+' · '+p.reference,p.supplierId,{id:eid,date:p.date});return {id:pid};});}
 async function cancelPayment(c,d){admin(c);return retry(async tx=>{const pid=id(d.id),p=await tx.get('supplierPayments/'+pid),eid='reverse-'+pid,old=await tx.get('supplierEvents/'+eid);if(old)return {id:pid,reused:true};check(p?.status==='verified'&&d.fundsReturned===true,'Pembatalan pembayaran terverifikasi memerlukan konfirmasi dana telah kembali.');const reason=text(d.reason,1000),reference=text(d.reference);const invoices=[];for(const a of p.allocations){const b=await tx.get('supplierInvoices/'+a.invoiceId);check(b&&b.verifiedPaid>=a.amount,'Saldo pembayaran tidak konsisten.');invoices.push([a.invoiceId,balance({...b,verifiedPaid:b.verifiedPaid-a.amount})]);}for(const [iid,b] of invoices)tx.set('supplierInvoices/'+iid,b);tx.update('supplierPayments/'+pid,{status:'dibatalkan',cancelReason:reason,returnReference:reference,cancelledBy:c.uid,cancelledAt:stamp()});audit(tx,eid,c,'payment_reversed',{supplierId:p.supplierId,documentId:pid,amount:p.amount,reason,reference});journal(tx,'supplier_reverse_'+pid,c,'masuk',p.amount,'Pengembalian pembayaran '+p.reference,p.supplierId,{id:eid,date:day(d.date)});return {id:pid};});}
 async function credit(c,d){admin(c);return retry(async tx=>{const iid=id(d.invoiceId),b=await tx.get('supplierInvoices/'+iid),reference=text(d.reference),eid='credit-'+hash([iid,reference]),old=await tx.get('supplierEvents/'+eid);if(old)return {reused:true};check(b&&['belum_dibayar','sebagian'].includes(b.status)&&d.confirmed===true,'Kredit retur harus diperiksa admin.');const value=positive(d.amount);check(value<=b.remaining,'Kredit melebihi sisa tagihan.');tx.set('supplierInvoices/'+iid,balance({...b,credits:b.credits+value}));audit(tx,eid,c,'return_credit',{supplierId:b.supplierId,documentId:iid,amount:value,reference,reason:text(d.reason,1000),date:day(d.date)});return {id:eid};});}
 async function cancelInvoice(c,d){admin(c);return retry(async tx=>{const iid=id(d.id),b=await tx.get('supplierInvoices/'+iid);check(b&&b.verifiedPaid===0&&b.credits===0&&b.status!=='dibatalkan','Batalkan/rekonsiliasi pembayaran dan kredit terlebih dahulu.');const reason=text(d.reason,1000);tx.update('supplierInvoices/'+iid,{status:'dibatalkan',cancelReason:reason,cancelledAt:stamp(),cancelledBy:c.uid});audit(tx,'cancel-'+iid,c,'invoice_cancelled',{supplierId:b.supplierId,documentId:iid,reason});return {id:iid};});}
 async function evaluate(c,d){admin(c);const sid=id(d.supplierId);return retry(async tx=>{const s=await supplier(tx,sid),period=text(d.period,7);check(/^\d{4}-(0[1-9]|1[0-2])$/.test(period),'Periode evaluasi YYYY-MM.');const eid=sid+'-'+period,old=await tx.get('supplierEvaluations/'+eid);check((old?.revision||0)===(d.expectedRevision||0),'Evaluasi berubah.');const scores={};for(const k of ['quality','delivery','completeness','response'])scores[k]=d.scores[k]===''||d.scores[k]==null?null:num(Number(d.scores[k]),1,5);const scored=Object.values(scores).filter(v=>v!==null);check(scored.length,'Isi minimal satu aspek yang benar-benar dinilai.');if(d.receiptId){const receipt=await tx.get('supplierReceipts/'+id(d.receiptId));check(receipt?.supplierId===sid&&receipt.status==='verified','Pilih penerimaan nyata Supplier ini.');}const r={supplierId:sid,supplierName:s.name,period,scores,scoredCount:scored.length,average:scored.reduce((a,b)=>a+b,0)/scored.length,notes:text(d.notes,2000),receiptId:d.receiptId||null,actor:c.uid,at:stamp(),revision:(old?.revision||0)+1};tx.set('supplierEvaluations/'+eid,r);audit(tx,'evaluation-'+eid+'-'+r.revision,c,'evaluation',{supplierId:sid,before:old||null,evaluation:r});return {id:eid};});}
 return {saveSupplier,submitReceipt,reviewReceipt,submitInvoice,reviewInvoice,submitPayment,reviewPayment,cancelPayment,cancelInvoice,credit,evaluate};
}
