import {$,esc,money,date,input,area,select,checkbox,tabs,table,form,bindForm,busy,message,download,filtered} from './planning-ui.js?v=admin-lengkap-20260909-r2';
import {supplierService,supplierDocumentId} from './supplier-service.js?v=admin-lengkap-20260909-r2';
import {storageConfiguration,prepareDocument,documentStorage} from './document-storage.js?v=admin-lengkap-20260909-r2';
import {wibDay,dueState,csv} from './planning-domain.js?v=admin-lengkap-20260909-r2';
import {check} from './manual-domain.js?v=admin-lengkap-20260909-r2';
const TABS=[['ringkasan','Ringkasan'],['data','Data Supplier'],['penerimaan','Surat Jalan & Penerimaan'],['tagihan','Tagihan & Nota'],['pembayaran','Pembayaran']];
const REPORT_LABELS={code:'Kode',name:'Nama Supplier',pic:'PIC',phone:'Telepon',email:'Email',address:'Alamat',category:'Kategori',paymentTerms:'Termin (hari)',active:'Aktif',productName:'Produk',sku:'SKU',receiptId:'ID surat jalan',documentNo:'No. dokumen',quality:'Kualitas',delivery:'Ketepatan kirim',completeness:'Kelengkapan jumlah',response:'Respons komplain',scoredCount:'Aspek dinilai',average:'Rata-rata',notes:'Catatan',actor:'Penilai',number:'No. dokumen',poRef:'Referensi PO',status:'Status',shortage:'Kurang (unit)',damaged:'Rusak (unit)',documentId:'ID dokumen',reference:'Referensi',amount:'Nominal (Rp)',verifiedPaid:'Terbayar (Rp)',credits:'Kredit (Rp)',remaining:'Sisa (Rp)',dueDate:'Jatuh tempo',allocations:'Alokasi tagihan',total:'Nilai barang layak (Rp)'};
const EVENT_LABELS={receipt_revision:'Revisi surat jalan',receipt_verified:'Barang diterima',receipt_correction:'Perbaikan surat jalan',invoice_revision:'Revisi nota',invoice_review:'Pemeriksaan nota',payment_revision:'Revisi pembayaran',payment_verified:'Pembayaran diverifikasi',payment_correction:'Perbaikan bukti pembayaran',payment_reversed:'Pengembalian dana',invoice_cancelled:'Nota dibatalkan',return_credit:'Kredit retur',evaluation:'Evaluasi',supplier:'Data Supplier'};
const LABELS={pending:'Menunggu pemeriksaan',correction:'Perlu perbaikan',verified:'Terverifikasi',belum_dibayar:'Belum dibayar',sebagian:'Dibayar sebagian',lunas:'Lunas',dibatalkan:'Dibatalkan'};
let filters={query:'',supplierId:'',status:'',from:'',to:''},report='invoices';
const status=s=>`<span class="badge">${esc(LABELS[s]||s)}</span>`;
export async function renderSuppliers(U){
 const collections={suppliers:'suppliers',receipts:'supplierReceipts',invoices:'supplierInvoices',payments:'supplierPayments',prices:'supplierPriceHistory',evaluations:'supplierEvaluations',events:'supplierEvents',products:'products',alertSettings:'supplierSettings'};
 const entries=await Promise.all(Object.entries(collections).map(async([k,path])=>[k,await U.store.list(path)]));if(!U.isCurrent())return;const D=Object.fromEntries(entries),S=supplierService(U.store),storage=documentStorage(U.c),tab=TABS.some(([k])=>k===U.tab)?U.tab:'ringkasan';
 const supplierOptions=[['','Pilih Supplier'],...D.suppliers.map(s=>[s.id,s.name+(s.active?'':' · nonaktif')])];
 $('#content').innerHTML=`<div class="page-head"><div><h1>Supplier</h1><p>Barang masuk, tagihan, dan pembayaran pemasok.</p></div><div class="actions"><button id="supplier-refresh">Segarkan</button><button id="document-health">Periksa koneksi dokumen</button></div></div>${tabs('suppliers',TABS,tab)}<p class="notice">${esc(storageConfiguration().message)}</p><div id="supplier-body"></div>`;$('#supplier-refresh').onclick=e=>busy(e.currentTarget,U.render);
 const body=$('#supplier-body');$('#document-health').disabled=window.KUBAH_EMULATOR===true;$('#document-health').title=window.KUBAH_EMULATOR?'Pratinjau memakai penyimpanan uji; koneksi cloud diperiksa di website asli.':'Periksa izin admin tanpa membuat transaksi atau mengunggah berkas.';$('#document-health').onclick=e=>busy(e.currentTarget,async()=>{await storage.checkAdminAccess();message('Koneksi Firebase–Supabase dan izin dokumen admin berhasil diverifikasi.');});
 if(U.oid&&['penerimaan','tagihan','pembayaran'].includes(tab)){const key={penerimaan:'receipts',tagihan:'invoices',pembayaran:'payments'}[tab],record=D[key].find(r=>r.id===U.oid);check(record,'Dokumen tidak tersedia.');await documentDetail(record,tab);return;}
 if(tab==='data'){renderData();return;}
 if(tab==='ringkasan'){renderSummary();return;}
 const kind={penerimaan:'receipts',tagihan:'invoices',pembayaran:'payments'}[tab];body.innerHTML=filterMarkup()+`<section id="records" class="panel"></section><div id="document-form"></div>`;bindFilters(()=>paint());paint();createDocumentForm(tab);
 function filterMarkup(){return `<div class="filters">${select('supplierId','Supplier',[['','Semua Supplier'],...supplierOptions.slice(1)],filters.supplierId)}${input('query','Cari nama / nomor',filters.query,'search')}${select('status','Status',[['','Semua status'],...Object.entries(LABELS),['aktif','Aktif'],['nonaktif','Nonaktif']],filters.status)}${input('from','Dari tanggal',filters.from,'date')}${input('to','Sampai tanggal',filters.to,'date')}</div>`;}
 function bindFilters(paint){document.querySelectorAll('.filters input,.filters select').forEach(el=>el.oninput=()=>{filters[el.name]=el.value;paint();});}
 function docTable(rows,target){return table(['Supplier','Nomor dokumen','Tanggal','Nominal / barang','Status','Aksi'],rows.map(r=>[esc(D.suppliers.find(s=>s.id===r.supplierId)?.name||r.supplierName),esc(r.number||r.reference),esc(r.date),r.amount?money(r.amount)+(r.remaining!=null?'<br><small>Sisa '+money(r.remaining)+'</small>':''):(r.lines||[]).reduce((s,l)=>s+l.good,0)+' unit layak diterima',status(r.status),`<a class="button" href="#suppliers/${target}/${esc(r.id)}">Periksa</a>`]));}
 function paint(){const rows=filtered(D[kind],filters);$('#records').innerHTML='<p>'+rows.length+' dokumen</p>'+docTable(rows,tab)+'<button id="export-current">Ekspor hasil filter CSV</button>';$('#export-current').onclick=()=>exportReport(kind,rows);}
 function renderData(){body.innerHTML=filterMarkup()+'<section id="supplier-table" class="panel"></section><div id="supplier-edit"></div>';
  const paint=()=>{const rows=filtered(D.suppliers.map(s=>({...s,status:s.active?'aktif':'nonaktif'})),{...filters,status:filters.status==='aktif'||filters.status==='nonaktif'?filters.status:''});$('#supplier-table').innerHTML=table(['Kode / nama','Kontak','Kategori','Termin','Status','Aksi'],rows.map(s=>[esc(s.code)+'<br><strong>'+esc(s.name)+'</strong>',esc(s.pic)+'<br>'+esc(s.phone)+'<br>'+esc(s.email),esc(s.category),s.paymentTerms+' hari',s.active?'Aktif':'Nonaktif',`<button data-supplier="${esc(s.id)}">Ubah / evaluasi</button>`]))+'<button id="export-current">Ekspor Supplier</button>';$('#export-current').onclick=()=>exportReport('suppliers',rows);document.querySelectorAll('[data-supplier]').forEach(b=>b.onclick=()=>edit(D.suppliers.find(s=>s.id===b.dataset.supplier)));};const statusFilter=$('[name=status]');statusFilter.innerHTML='<option value="">Semua status</option><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option>';statusFilter.value=['aktif','nonaktif'].includes(filters.status)?filters.status:'';bindFilters(paint);paint();edit();
  function edit(s={}){$('#supplier-edit').innerHTML=form('supplier-edit-form','<h2 class="full">'+(s.id?'Ubah Supplier':'Tambah Supplier')+'</h2>'+input('code','Kode Supplier',s.code||'','text','required')+input('name','Nama usaha / Supplier',s.name||'','text','required')+input('pic','Nama PIC',s.pic||'','text','required')+input('phone','Telepon / WhatsApp',s.phone||'','tel')+input('email','Email',s.email||'','email')+input('category','Kategori barang',s.category||'')+input('paymentTerms','Termin pembayaran (hari)',s.paymentTerms||0,'number','min="0" max="365"')+area('address','Alamat',s.address||'')+checkbox('active','Supplier aktif',s.active??true))+(s.id?evaluationForm(s):'');bindForm('supplier-edit-form',async(d,f)=>{await S.saveSupplier(U.ctx,{...d,id:s.id,expectedRevision:s.revision||0,active:f.elements.active.checked});await U.render();message('Data Supplier tersimpan. Nama pada dokumen lama tetap tercatat dalam riwayat.');});if(s.id)bindEvaluation(s);}
 }
 function renderSummary(){const balances=D.invoices.filter(b=>!['pending','correction','dibatalkan'].includes(b.status)),today=wibDay();let days=D.alertSettings.find(x=>x.id==='alerts')?.thresholds||[7,3,0];
  body.innerHTML=`<div class="kpis"><article class="panel">Supplier aktif<strong>${D.suppliers.filter(s=>s.active).length}</strong></article><article class="panel">Sisa tagihan<strong>${money(balances.reduce((s,b)=>s+b.remaining,0))}</strong></article><article class="panel">Pembayaran terverifikasi<strong>${money(D.payments.filter(p=>p.status==='verified').reduce((s,p)=>s+p.amount,0))}</strong></article><article class="panel">Dokumen perlu diperiksa<strong>${[...D.receipts,...D.invoices,...D.payments].filter(d=>d.status==='pending').length}</strong></article></div><section class="panel"><h2>Jatuh tempo · ${esc(today)} WIB</h2><p class="muted">Diperiksa saat halaman dibuka atau disegarkan. Tidak ada pengiriman notifikasi otomatis di luar aplikasi.</p>${form('alerts',input('thresholds','Pengingat H- (pisahkan koma)',days.join(','),'text','required'),'Atur pengingat')}<div id="due-list"></div></section>${filterMarkup()}<section class="panel"><h2>Laporan Supplier</h2>${select('report','Jenis laporan',[['invoices','Tagihan & saldo'],['payments','Pembayaran'],['receipts','Penerimaan / pembelian'],['prices','Riwayat harga beli'],['evaluations','Evaluasi Supplier'],['credits','Kredit retur yang disetujui'],['suppliers','Data Supplier']],report)}<p class="muted">Baris dan total ekspor mengikuti filter di layar. Nominal tagihan tidak dijumlahkan ulang melalui baris cicilan.</p><div id="report-table"></div><button id="export-report">Ekspor laporan CSV</button></section><section class="panel"><h2>Pengembangan pendukung Supplier</h2><ul><li>Purchase Order dengan persetujuan dan ETA.</li><li>Retur barang serta penggantian/kredit.</li><li>Pencocokan PO–surat jalan–nota.</li><li>Arsip dokumen lintas periode.</li><li>Formulir kerja sama Supplier dengan tinjauan manual.</li></ul><p>Ide ini tetap disimpan dalam planning terpisah dari desain katalog.</p></section>`;
  const due=()=>{$('#due-list').innerHTML=table(['Supplier / nota','Jatuh tempo','Sisa','Pengingat','Aksi'],balances.map(b=>({...b,due:dueState(b,today,days)})).filter(b=>b.due?.alert).sort((a,b)=>a.due.days-b.due.days).map(b=>[esc(b.supplierName)+'<br>'+esc(b.number),esc(b.dueDate),money(b.remaining),esc(b.due.label),`<a href="#suppliers/tagihan/${esc(b.id)}">Buka tagihan</a>`]));};due();bindForm('alerts',async d=>{const values=d.thresholds.split(',').map(Number);check(values.length&&values.every(n=>Number.isInteger(n)&&n>=0&&n<=60),'Isi angka 0–60, dipisahkan koma.');days=[...new Set(values)];await U.store.set('supplierSettings/alerts',{thresholds:days,updatedBy:U.ctx.uid,updatedAt:new Date().toISOString()});due();message('Pengingat Supplier tersimpan untuk admin.');});
  const paintReport=()=>{const rows=reportRows(report);$('#report-table').innerHTML=reportTable(report,rows);$('#export-report').onclick=()=>exportReport(report,rows);};$('[name=report]').onchange=e=>{report=e.target.value;paintReport();};bindFilters(paintReport);paintReport();
 }
 function reportRows(type){const source=type==='credits'?D.events.filter(e=>e.type==='return_credit'):D[type];return filtered(source||[],filters);}
 function rawReportColumns(type){const common=[{key:'supplierName',label:'Supplier',value:r=>D.suppliers.find(s=>s.id===(r.supplierId||r.id))?.name||r.supplierName||r.name},{key:'id',label:'ID dokumen'},{key:'date',label:'Tanggal',value:r=>r.date||r.period||''}];if(type==='suppliers')return [{key:'code'},{key:'name'},{key:'pic'},{key:'phone'},{key:'email'},{key:'address'},{key:'category'},{key:'paymentTerms'},{key:'active'}];if(type==='prices')return [...common,{key:'productName'},{key:'sku'},{key:'receiptId'},{key:'documentNo'},{key:'good',label:'Unit diterima'},{key:'packPcs',label:'Pcs per unit'},{key:'unitPrice',label:'Harga per unit'},{key:'pricePerPcs',label:'Harga per pcs'},{key:'previousPrice',label:'Harga sebelumnya / pcs',value:r=>previousPrice(r)??''},{key:'delta',label:'Perubahan / pcs',value:r=>previousPrice(r)==null?'':r.pricePerPcs-previousPrice(r)}];if(type==='evaluations')return [...common,{key:'receiptId'},{key:'quality',value:r=>r.scores.quality??''},{key:'delivery',value:r=>r.scores.delivery??''},{key:'completeness',value:r=>r.scores.completeness??''},{key:'response',value:r=>r.scores.response??''},{key:'scoredCount'},{key:'average'},{key:'notes'},{key:'actor'}];if(type==='receipts')return [...common,{key:'number'},{key:'poRef'},{key:'status'},{key:'goods',label:'Barang / unit / harga',value:r=>r.lines.map(l=>`${l.productName} ${l.sku}: ${l.good} unit x ${l.packPcs} pcs; Rp${l.unitPrice}/unit`).join(' | ')},{key:'total',label:'Nilai barang layak',value:r=>r.lines.reduce((s,l)=>s+l.good*l.unitPrice,0)},{key:'shortage',value:r=>r.lines.reduce((s,l)=>s+l.shortage,0)},{key:'damaged',value:r=>r.lines.reduce((s,l)=>s+l.damaged,0)}];if(type==='credits')return [...common,{key:'documentId'},{key:'reference'},{key:'amount'},{key:'reason'}];return [...common,{key:'number',value:r=>r.number||r.reference},{key:'amount'},{key:'verifiedPaid'},{key:'credits'},{key:'remaining'},{key:'dueDate'},{key:'status'},{key:'allocations',value:r=>r.allocations?.map(a=>a.invoiceNo+': '+a.amount).join(' | ')||''}];}
 function reportColumns(type){return rawReportColumns(type).map(c=>({...c,label:c.label||REPORT_LABELS[c.key]||c.key}));}
 function reportTotals(type,rows){const totals={};if(type==='receipts')totals.total=rows.reduce((s,r)=>s+r.lines.reduce((n,l)=>n+l.good*l.unitPrice,0),0);if(['invoices','payments','credits'].includes(type)){for(const k of ['amount',...(type==='invoices'?['verifiedPaid','credits','remaining']:[])])totals[k]=rows.reduce((s,r)=>s+Number(r[k]||0),0);}return totals;}
 function previousPrice(r){return D.prices.filter(x=>x.id!==r.id&&x.productId===r.productId&&x.variantId===r.variantId&&x.supplierId===r.supplierId&&(x.date<r.date||x.date===r.date&&x.at<r.at)).sort((a,b)=>b.date.localeCompare(a.date)||String(b.at).localeCompare(String(a.at)))[0]?.pricePerPcs??null;}
 function reportTable(type,rows){const cols=reportColumns(type);return '<p>'+rows.length+' catatan · periode '+esc(filters.from||'awal')+' s.d. '+esc(filters.to||'akhir')+'</p>'+table(cols.map(c=>c.label||c.key),rows.map(r=>cols.map(c=>esc(c.value?c.value(r):c.key==='status'?(LABELS[r.status]||r.status):r[c.key]))))+'<p>'+Object.entries(reportTotals(type,rows)).map(([k,v])=>esc(REPORT_LABELS[k])+': '+money(v)).join(' · ')+'</p><p class="muted">Total nominal mencakup dokumen pada hasil filter. Pilih status untuk membatasi laporan; ringkasan hutang hanya menghitung tagihan yang sudah disetujui dan belum dibatalkan.</p>';}
 function exportReport(type,rows){const cols=reportColumns(type),at=new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'});const exported=rows.map(r=>({...r,reportPeriod:(filters.from||'awal')+' s.d. '+(filters.to||'akhir'),exportedAt:at+' WIB'}));download('Supplier-'+type+'-'+wibDay()+'.csv',csv([...exported,...(Object.keys(reportTotals(type,rows)).length?[{id:'TOTAL',supplierName:'TOTAL HASIL FILTER',...reportTotals(type,rows)}]:[])],[...cols.map(c=>({...c,value:c.value?r=>r.id==='TOTAL'?r[c.key]:c.value(r):undefined})),{key:'reportPeriod',label:'Periode laporan'},{key:'exportedAt',label:'Diekspor pada'}]));}
 function uploadMarkup(){return '<div class="full">'+input('document','Dokumen PDF / JPG / PNG, hasil maksimal 2 MB','','file','accept="application/pdf,image/jpeg,image/png" required')+'<p class="muted">Foto dikompres. Periksa tulisan dan barcode pada pratinjau sebelum menyimpan.</p><div id="document-preview"></div>'+checkbox('readable','Tulisan dan barcode pada dokumen terbaca jelas')+'<progress id="document-progress" max="100" value="0"></progress><p id="document-status" role="status"></p></div>';}
 function bindUpload(f){let prepared=null,url=null;f.elements.document.onchange=async()=>{try{prepared=await prepareDocument(f.elements.document.files[0]);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(prepared.blob);$('#document-preview').innerHTML=prepared.mime==='application/pdf'?`<iframe class="doc-preview" src="${url}" title="Pratinjau dokumen"></iframe>`:`<img class="doc-preview" src="${url}" alt="Pratinjau dokumen">`;f.elements.readable.checked=false;$('#document-status').textContent=Math.ceil(prepared.size/1024)+' KB · siap ditinjau';}catch(e){prepared=null;message(e.message,true);}};return async(sid,did,kind)=>{check(prepared&&f.elements.readable.checked,'Pilih dokumen dan konfirmasikan keterbacaannya.');return storage.uploadSupplier(prepared,{supplierId:sid,documentId:did,kind,onProgress:(n,text)=>{$('#document-progress').value=n;$('#document-status').textContent=text+' '+n+'%';}});};}
 function createDocumentForm(which,old={}){const k={penerimaan:'receipt',tagihan:'invoice',pembayaran:'payment'}[which];
  let html='<h2 class="full">'+(old.id?'Kirim revisi':'Tambah '+(k==='receipt'?'surat jalan':k==='invoice'?'nota Supplier':'pembayaran'))+'</h2>'+select('supplierId','Supplier',supplierOptions,old.supplierId||filters.supplierId)+input('number',k==='payment'?'Referensi mutasi bank / kas':'Nomor '+(k==='receipt'?'surat jalan':'nota'),old.number||old.reference||'','text','required maxlength="200"')+input('date','Tanggal',old.date||wibDay(),'date','required');
  if(k==='receipt')html+=input('poRef','Referensi PO (jika ada)',old.poRef||'')+'<div class="full" id="receipt-lines"></div><button id="add-goods" type="button">Tambah barang</button>';
  if(k==='invoice')html+=input('poRef','Referensi PO (jika ada)',old.poRef||'')+input('dueDate','Tanggal jatuh tempo',old.dueDate||wibDay(),'date','required')+input('amount','Jumlah tagihan (Rp)',old.amount||'','number','min="1" required')+'<div id="receipt-links" class="full"></div>';
  if(k==='payment')html+=select('kind','Jenis pembayaran',['DP','Cicilan','Pelunasan'],old.kind||'Cicilan')+select('method','Metode',['Transfer bank','Tunai'],old.method||'Transfer bank')+input('amount','Nominal dibayarkan (Rp)',old.amount||'','number','min="1" required')+'<div id="allocations" class="full"></div>';
  $('#document-form').innerHTML=form('supplier-document',html+uploadMarkup(),'Unggah & simpan untuk diperiksa');const f=$('#supplier-document'),upload=bindUpload(f);if(old.id){f.elements.supplierId.disabled=true;f.elements.number.readOnly=true;}
  const productOptions=D.products.flatMap(p=>p.variants.map(v=>[p.id+'/'+v.id,p.name+' · '+v.sku+' '+(v.color||'')+' '+(v.size||'')]));
  function addGoods(l={}){const div=document.createElement('div');div.className='variant-row form-grid';div.innerHTML=select('product','Produk / varian',productOptions,l.productId?l.productId+'/'+l.variantId:'')+input('expected','Jumlah pada surat jalan (unit)',l.expected||1,'number','min="1" required')+input('received','Jumlah fisik diterima (unit)',l.received??1,'number','min="0" required')+input('damaged','Rusak / tidak layak (unit)',l.damaged||0,'number','min="0" required')+input('unitPrice','Harga beli per unit (Rp)',l.unitPrice||'','number','min="1" required')+input('packPcs','Pcs per unit pembelian',l.packPcs||1,'number','min="1" required')+'<button type="button" class="remove-goods">Hapus baris</button>';div.querySelector('.remove-goods').onclick=()=>div.remove();$('#receipt-lines').append(div);}
  function links(){const sid=f.elements.supplierId.value;if(k==='invoice')$('#receipt-links').innerHTML='<h3>Surat jalan yang sudah diverifikasi</h3>'+D.receipts.filter(r=>r.supplierId===sid&&r.status==='verified').map(r=>checkbox('receipt-'+r.id,r.number+' · '+r.date,old.receiptIds?.includes(r.id))).join('');if(k==='payment')$('#allocations').innerHTML='<h3>Alokasi ke tagihan</h3><p>Jumlah alokasi harus sama dengan nominal pembayaran. Maksimal 8 tagihan.</p>'+D.invoices.filter(b=>b.supplierId===sid&&['belum_dibayar','sebagian'].includes(b.status)).map(b=>input('allocation-'+b.id,b.number+' · sisa '+money(b.remaining),old.allocations?.find(a=>a.invoiceId===b.id)?.amount||'','number','min="0" max="'+b.remaining+'"')).join('');}
  f.elements.supplierId.onchange=links;links();if(k==='receipt'){for(const l of old.lines||[{}])addGoods(l);$('#add-goods').onclick=()=>addGoods();}
  bindForm('supplier-document',async d=>{const sid=f.elements.supplierId.value,number=f.elements.number.value;check(sid,'Pilih Supplier.');const did=supplierDocumentId(sid,k,number),file=await upload(sid,did,k),data={...d,supplierId:sid,number,reference:number,file};
   if(k==='receipt'){data.lines=[...document.querySelectorAll('#receipt-lines .variant-row')].map(row=>{const get=n=>row.querySelector('[name='+n+']').value,[productId,variantId]=get('product').split('/');return {productId,variantId,expected:Number(get('expected')),received:Number(get('received')),damaged:Number(get('damaged')),unitPrice:Number(get('unitPrice')),packPcs:Number(get('packPcs'))};});await S.submitReceipt(U.ctx,data);}
   if(k==='invoice'){data.amount=Number(d.amount);data.receiptIds=D.receipts.filter(r=>f.elements['receipt-'+r.id]?.checked).map(r=>r.id);await S.submitInvoice(U.ctx,data);}
   if(k==='payment'){data.amount=Number(d.amount);data.allocations=D.invoices.map(b=>({invoiceId:b.id,amount:Number(f.elements['allocation-'+b.id]?.value||0)})).filter(a=>a.amount>0);await S.submitPayment(U.ctx,data);}
   location.hash='suppliers/'+which+'/'+did;if(old.id)await U.render();message('Dokumen tersimpan untuk pemeriksaan. Stok dan pembayaran belum berubah.');});
 }
 async function documentDetail(r,which){const name=D.suppliers.find(s=>s.id===r.supplierId)?.name||r.supplierName,related=D.events.filter(e=>e.documentId===r.id).sort((a,b)=>String(a.at).localeCompare(String(b.at)));
  body.innerHTML=`<a href="#suppliers/${which}">← Kembali ke daftar</a><section class="panel"><div class="page-head"><h2>${esc(r.number||r.reference)} · ${esc(name)}</h2>${status(r.status)}</div><p>Supplier saat pencatatan: ${esc(r.supplierName)}<br>Tanggal ${esc(r.date)} · Revisi ${r.revision}</p><p>${esc(r.reviewReason||r.inspectionNote||r.cancelReason||'')}</p><div class="actions"><button id="view-document">Lihat dokumen</button><button id="download-document">Unduh</button><button id="print-document">Cetak</button></div><div id="private-document"></div>${r.amount?'<p>Nominal '+money(r.amount)+(r.remaining!=null?' · pembayaran terverifikasi '+money(r.verifiedPaid)+' · kredit '+money(r.credits)+' · sisa '+money(r.remaining):'')+'</p>':''}${r.lines?table(['Barang / SKU','Surat jalan','Diterima','Rusak','Layak masuk stok','Kurang','Harga beli / unit'],r.lines.map(l=>[esc(l.productName)+'<br>'+esc(l.sku),l.expected,l.received,l.damaged,l.stockUnits??'Menunggu pemeriksaan',l.shortage,money(l.unitPrice)])):''}${r.allocations?table(['Tagihan','Alokasi'],r.allocations.map(a=>[esc(a.invoiceNo),money(a.amount)])):''}${r.receiptIds?'<p>Surat jalan: '+r.receiptIds.map(id=>`<a href="#suppliers/penerimaan/${esc(id)}">${esc(D.receipts.find(x=>x.id===id)?.number||id)}</a>`).join(', ')+'</p>':''}</section><div id="review-form"></div><div id="document-form"></div><section class="panel"><h2>Riwayat pemeriksaan & revisi</h2>${table(['Waktu','Aksi','Pelaksana','Alasan / revisi'],related.map(e=>[date(e.at),esc(EVENT_LABELS[e.type]||e.type),esc(e.actor),esc(e.reason||e.document?.revision||'')]))}<div id="old-files"></div></section>`;
  let blob=null;const read=async()=>blob=await storage.read(r.file);$('#view-document').onclick=e=>busy(e.currentTarget,async()=>{const url=URL.createObjectURL(await read());$('#private-document').innerHTML=r.file.mime==='application/pdf'?`<iframe class="doc-preview" title="Dokumen privat" src="${url}"></iframe>`:`<img class="doc-preview" alt="Dokumen privat" src="${url}">`;});$('#download-document').onclick=e=>busy(e.currentTarget,async()=>download((r.number||r.reference).replace(/[^a-z0-9-]/gi,'_')+'.'+r.file.objectName.split('.').pop(),await read()));$('#print-document').onclick=e=>{const child=window.open('about:blank','_blank');busy(e.currentTarget,async()=>{const url=URL.createObjectURL(await read());if(!child)throw Error('Izinkan tab dokumen untuk mencetak.');child.location.href=url;child.onload=()=>{child.focus();child.print();};message('Dokumen dibuka. Gunakan Ctrl+P bila dialog cetak tidak muncul.');});};
  const revisionFiles=related.filter(e=>e.document?.file);$('#old-files').innerHTML=revisionFiles.map((e,i)=>`<button data-old="${i}">Unduh revisi ${e.document.revision}</button>`).join(' ');document.querySelectorAll('[data-old]').forEach(b=>b.onclick=()=>busy(b,async()=>{const e=revisionFiles[Number(b.dataset.old)];download('Revisi-'+e.document.revision+'.'+e.document.file.objectName.split('.').pop(),await storage.read(e.document.file));}));
  if(r.status==='correction'){createDocumentForm(which,r);return;}
  if(r.status==='pending'){
   $('#review-form').innerHTML=form('review',select('decision','Keputusan',[['correction','Minta perbaikan'],['approve','Setujui setelah diperiksa']])+area('reason','Hasil pemeriksaan / alasan perbaikan')+checkbox('checked',which==='penerimaan'?'Saya memeriksa barang fisik, jumlah, dan kondisinya':which==='pembayaran'?'Saya memeriksa dana keluar pada rekening / kas':'Saya memeriksa nota dan kesesuaiannya dengan barang'),'Simpan pemeriksaan');bindForm('review',async(d,f)=>{check(d.reason.trim(),'Isi alasan/hasil pemeriksaan.');const approve=d.decision==='approve';if(approve){check(f.elements.checked.checked,'Konfirmasikan pemeriksaan terlebih dahulu.');await read();}const method={penerimaan:'reviewReceipt',tagihan:'reviewInvoice',pembayaran:'reviewPayment'}[which];await S[method](U.ctx,{id:r.id,revision:r.revision,approve,reason:d.reason,goodsChecked:f.elements.checked.checked,fundsChecked:f.elements.checked.checked});await U.render();message(approve?'Pemeriksaan tersimpan.':'Permintaan perbaikan tersimpan; dokumen lama tetap ada.');});
  }
  if(which==='tagihan'&&['belum_dibayar','sebagian'].includes(r.status)){
   $('#review-form').innerHTML+=form('credit','<h2 class="full">Kredit retur yang disetujui</h2><p class="full muted">Catat kredit hanya jika ada nota kredit/retur yang benar-benar disetujui. Ini mengurangi tagihan, tanpa otomatis mengubah stok atau kas.</p>'+input('reference','Referensi nota kredit / retur','','text','required')+input('amount','Nominal kredit (Rp)','','number','min="1" required')+input('date','Tanggal kredit',wibDay(),'date','required')+area('reason','Alasan dan hasil pemeriksaan')+checkbox('confirmed','Kredit telah disetujui Supplier dan diperiksa admin'),'Catat kredit');bindForm('credit',async(d,f)=>{await S.credit(U.ctx,{...d,invoiceId:r.id,amount:Number(d.amount),confirmed:f.elements.confirmed.checked});await U.render();message('Kredit tercatat.');});
   if(!r.verifiedPaid&&!r.credits){$('#review-form').insertAdjacentHTML('beforeend',form('cancel-invoice',input('reason','Alasan pembatalan nota','','text','required'),'Batalkan nota'));bindForm('cancel-invoice',async d=>{await S.cancelInvoice(U.ctx,{id:r.id,...d});await U.render();});}
  }
  if(which==='pembayaran'&&r.status==='verified'){$('#review-form').innerHTML=form('reverse','<h2 class="full">Pembatalan setelah dana dikembalikan</h2>'+input('reference','Referensi dana kembali','','text','required')+input('date','Tanggal dana kembali',wibDay(),'date','required')+area('reason','Alasan pembatalan / koreksi')+checkbox('fundsReturned','Dana benar-benar telah kembali dan saya memeriksanya'),'Catat pembatalan & jurnal pengembalian');bindForm('reverse',async(d,f)=>{await S.cancelPayment(U.ctx,{...d,id:r.id,fundsReturned:f.elements.fundsReturned.checked});await U.render();message('Pembatalan dicatat dengan jurnal pengembalian. Jurnal pembayaran lama tetap utuh.');});}
 }
 function evaluationForm(s){const scores=[['quality','Kualitas barang'],['delivery','Ketepatan pengiriman'],['completeness','Kelengkapan jumlah'],['response','Respons terhadap komplain']];return '<section class="panel"><h2>Evaluasi Supplier</h2>'+table(['Periode','Rata-rata','Aspek dinilai','Catatan'],D.evaluations.filter(e=>e.supplierId===s.id).map(e=>[esc(e.period),e.average.toFixed(2)+' / 5',e.scoredCount,esc(e.notes)]))+(D.evaluations.some(e=>e.supplierId===s.id)?'':'<p>Belum dinilai.</p>')+'</section>'+form('evaluation',input('period','Periode',wibDay().slice(0,7),'month','required')+select('receiptId','Referensi penerimaan (opsional)',[['','Tanpa referensi'],...D.receipts.filter(r=>r.supplierId===s.id&&r.status==='verified').map(r=>[r.id,r.number+' · '+r.date])])+scores.map(([k,l])=>select(k,l,[['','Tidak dinilai'],[1,'1'],[2,'2'],[3,'3'],[4,'4'],[5,'5']])).join('')+area('notes','Catatan faktual penilaian'),'Simpan evaluasi');}
 function bindEvaluation(s){bindForm('evaluation',async d=>{const old=D.evaluations.find(e=>e.supplierId===s.id&&e.period===d.period);await S.evaluate(U.ctx,{supplierId:s.id,period:d.period,receiptId:d.receiptId,scores:{quality:d.quality,delivery:d.delivery,completeness:d.completeness,response:d.response},notes:d.notes,expectedRevision:old?.revision||0});await U.render();message('Evaluasi tersimpan. Supplier tidak dinonaktifkan otomatis.');});}
}
