import {esc,money} from './planning-ui.js?v=audit-20260920-r17';
import {check} from './manual-domain.js?v=products-20260917-r16';
import {applyVariantBulk,undoVariantBulk,variantNumber,variantValue,setVariantValue} from './variant-draft.js?v=product-save-20260923-r19';
import {prepareProductPhoto,productPhotos} from './product-photos.js?v=audit-20260920-r17';
import {combinationPlan,addCombinations} from './variant-combinations.js?v=product-save-20260923-r19';

export function mountVariantTable(host,{variants,parent={},c,onChange=()=>{},canEdit=true}){
 let rows=structuredClone(variants),selected=new Set(),undo=[],edited=new Set(),preparing=0,locked=false;
 const photos=new Map(),urls=new Map();
 const number=(k,v)=>v==null?'':['retail','wholesale','hpp'].includes(k)&&/^\d+$/.test(String(v))?Number(v).toLocaleString('id-ID'):v;
 const control=(row,k,label,{optional=false,placeholder='',money=false}={})=>`<label class="variant-cell"><span class="sr-only">${esc(label+' '+(row.color||row.sku||row.id))}</span>${money?'<span class="variant-rp">Rp</span>':''}<input data-field="${k}" aria-label="${esc(label+' '+(row.color||row.sku||row.id))}" value="${esc(number(k,variantValue(row,k)))}" ${['stock','retail','wholesale','hpp','weight'].includes(k)?'inputmode="numeric"':''} placeholder="${esc(placeholder)}" ${optional?'':'required'} ${canEdit?'':'disabled'}></label>`;
 host.innerHTML=`<div class="variant-heading"><h2>Varian & Stok</h2><span data-dirty class="variant-dirty" role="status">Belum ada perubahan varian</span></div><p class="muted">Stok dalam satuan jual (<span data-unit></span>). Harga dan berat kosong mengikuti induk. HPP hanya untuk admin.</p><div class="variant-bulk"><label class="field">Target<select data-target aria-label="Target pengaturan massal"><option value="all">Semua Varian</option><option value="selected">Varian Terpilih</option></select></label><label class="field">Qty / Stok<input data-bulk="stock" aria-label="Qty massal" inputmode="numeric" placeholder="Tidak diubah"></label><label class="field">Harga Eceran (Rp)<input data-bulk="retail" aria-label="Eceran massal" inputmode="numeric" placeholder="Tidak diubah"></label><label class="field">Harga Grosir (Rp)<input data-bulk="wholesale" aria-label="Grosir massal" inputmode="numeric" placeholder="Tidak diubah"></label><button type="button" data-apply class="primary" disabled>Terapkan</button><div class="variant-bulk-note"><span data-target-count></span> · Hanya kolom terisi diubah. Qty menetapkan stok akhir.</div></div><div class="variant-draft-actions"><span>Terapkan hanya mengisi draf. Gunakan Simpan Produk untuk menyimpan.</span><button type="button" data-undo disabled>Batalkan penerapan terakhir</button></div><p data-status role="status" class="variant-status" hidden></p><div class="variant-table-scroll" tabindex="0" role="region" aria-label="Tabel varian, geser horizontal untuk kolom lainnya"><table class="variant-table"><thead><tr><th><input type="checkbox" data-all aria-label="Pilih semua varian"></th><th>Foto & Warna/Nama Varian</th><th>Ukuran</th><th>Stok/Qty</th><th>Harga Eceran</th><th>Harga Grosir</th><th>HPP</th><th>Berat (gram)</th><th>SKU</th></tr></thead><tbody></tbody></table></div><div class="variant-bottom"><button type="button" data-add>+ Tambah varian</button><small>Harga per satuan jual. Minimum grosir mengikuti pengaturan produk.</small></div>`;
 const q=s=>host.querySelector(s),status=(text,error=false)=>{q('[data-status]').hidden=!text;q('[data-status]').textContent=text;q('[data-status]').classList.toggle('error',error);};
 const generator=document.createElement('details');generator.className='variant-generator';generator.innerHTML='<summary>Buat kombinasi warna × ukuran</summary><p>Tambahkan kombinasi yang belum ada. ID, foto, stok dan harga varian lama tetap. Pisahkan pilihan dengan koma atau baris baru.</p><div class="variant-generator-fields"><label class="field">Warna<textarea data-colors aria-label="Warna untuk kombinasi" placeholder="Merah, Biru"></textarea></label><label class="field">Ukuran<textarea data-sizes aria-label="Ukuran untuk kombinasi" placeholder="S, M, L"></textarea></label></div><button type="button" data-preview-combinations>Pratinjau kombinasi</button><div data-combination-preview role="status"></div><button type="button" data-add-combinations hidden>Tambahkan kombinasi ke draf</button>';
 host.querySelector('.variant-bulk').before(generator);let planned=null;
 q('[data-preview-combinations]').disabled=!canEdit;
 q('[data-preview-combinations]').onclick=()=>{try{planned=combinationPlan(rows,q('[data-colors]').value,q('[data-sizes]').value);q('[data-combination-preview]').textContent=planned.add.length+' kombinasi baru: '+planned.add.map(x=>x.color+' / '+x.size).join(', ')+'. '+planned.kept+' kombinasi sudah ada, tetap dipertahankan. Isi stok sebelum menyimpan; harga/berat kosong mengikuti induk.';q('[data-add-combinations]').hidden=!planned.add.length;}catch(error){planned=null;q('[data-add-combinations]').hidden=true;status(error.message,true);}};
 q('[data-add-combinations]').onclick=()=>{if(!planned||locked||!canEdit)return;try{const before=rows.length;rows=addCombinations(rows,planned,document.querySelector('#product-edit [name=sku]')?.value||parent.sku);planned=null;q('[data-add-combinations]').hidden=true;q('[data-combination-preview]').textContent=(rows.length-before)+' kombinasi ditambahkan sebagai draf. Isi Qty/Stok; 0 berarti stok habis.';paint();dirty();}catch(error){status(error.message,true);}};
 for(const el of generator.querySelectorAll('textarea'))el.oninput=()=>{planned=null;q('[data-add-combinations]').hidden=true;q('[data-combination-preview]').textContent='Pilihan berubah. Buat pratinjau kembali.';};
 function dirty(){q('[data-dirty]').textContent='Perubahan belum disimpan';q('[data-dirty]').classList.add('changed');onChange();}
 function sync(){if(locked)host.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);const count=q('[data-target]').value==='all'?rows.length:rows.filter(v=>selected.has(v.id)).length;q('[data-target-count]').textContent=count+' varian akan menerima perubahan';q('[data-apply]').disabled=locked||!canEdit||!count||![...host.querySelectorAll('[data-bulk]')].some(i=>i.value.trim());q('[data-undo]').disabled=locked||!undo.length;q('[data-all]').checked=rows.length>0&&rows.every(v=>selected.has(v.id));q('[data-all]').indeterminate=selected.size>0&&!q('[data-all]').checked;q('[data-add]').disabled=locked||!canEdit||rows.length>=100;}
 function paint(){q('tbody').innerHTML=rows.map(v=>{const src=urls.get(v.id)||v.image||'',name=v.color||v.sku||v.id;return `<tr data-variant-id="${esc(v.id)}"><td><input type="checkbox" data-select aria-label="${esc('Pilih '+name)}" ${selected.has(v.id)?'checked':''}></td><td><div class="variant-identity"><div class="variant-photo">${src?`<img src="${esc(src)}" alt="${esc('Foto '+name)}">`:'<span>Foto</span>'}<label class="variant-upload">${src?'Ganti':'Upload'}<input data-photo type="file" accept="image/jpeg,image/png" aria-label="${esc('Upload foto '+name)}" ${canEdit?'':'disabled'}></label></div><div>${control(v,'color','Warna/Nama',{optional:true})}<small data-photo-state>${photos.has(v.id)?'Foto dipilih · belum disimpan':'JPG/PNG · hasil maks. 2 MB'}</small><details><summary>Foto dari tautan (opsional)</summary><label>URL HTTPS<input data-field="image" aria-label="${esc('URL foto '+name)}" value="${esc(v.image||'')}" type="url"></label></details></div></div></td><td>${control(v,'size','Ukuran',{optional:true})}</td><td>${control(v,'stock','Stok')}</td><td>${control(v,'retail','Harga Eceran',{optional:true,placeholder:parent.website?.retail?number('retail',parent.website.retail):'Induk',money:true})}</td><td>${control(v,'wholesale','Harga Grosir',{optional:true,placeholder:parent.website?.tiers?.[0]?.price?number('wholesale',parent.website.tiers[0].price):'Induk',money:true})}</td><td>${control(v,'hpp','HPP',{optional:true,placeholder:parent.hpp!=null?number('hpp',parent.hpp):'Belum diisi',money:true})}</td><td>${control(v,'weight','Berat',{optional:true,placeholder:String(parent.weight??'Induk')})}</td><td>${control(v,'sku','SKU')}</td></tr>`;}).join('');sync();}
 q('[data-unit]').textContent=(parent.saleUnit||'unit')+'; '+(parent.website?.packPcs?parent.website.packPcs+' pcs per unit':'isi pcs diatur di atas');
 host.addEventListener('input',e=>{if(e.target.type==='checkbox'||e.target.type==='file')return;if(e.target.matches('[data-field]')){const row=rows.find(v=>v.id===e.target.closest('[data-variant-id]').dataset.variantId),k=e.target.dataset.field;setVariantValue(row,k,e.target.value);edited.add(row.id+'/'+k);if(k==='image'){photos.delete(row.id);if(urls.has(row.id))URL.revokeObjectURL(urls.get(row.id));urls.delete(row.id);}dirty();}sync();});
 host.addEventListener('change',async e=>{const el=e.target;
  if(el.matches('[data-all]')){selected=new Set(el.checked?rows.map(v=>v.id):[]);host.querySelectorAll('[data-select]').forEach(x=>x.checked=el.checked);sync();}
  if(el.matches('[data-select]')){const id=el.closest('[data-variant-id]').dataset.variantId;el.checked?selected.add(id):selected.delete(id);sync();}
  if(el.matches('[data-target]'))sync();
  if(el.matches('[data-photo]')&&el.files?.[0]){const row=rows.find(v=>v.id===el.closest('[data-variant-id]').dataset.variantId),file=el.files[0];preparing++;el.disabled=true;status('Menyiapkan pratinjau foto…');try{const photo=await prepareProductPhoto(file);photos.set(row.id,photo);if(urls.has(row.id))URL.revokeObjectURL(urls.get(row.id));urls.set(row.id,URL.createObjectURL(photo.blob));dirty();status('Foto dipilih. Upload dan penyimpanan produk dilakukan saat Simpan Produk.');paint();}catch(error){status(error.message,true);}finally{preparing--;el.disabled=false;}}
 });
 host.addEventListener('focusout',e=>{const k=e.target.dataset.field||e.target.dataset.bulk;if(['retail','wholesale','hpp'].includes(k)&&e.target.value.trim())try{e.target.value=variantNumber(e.target.value,k).toLocaleString('id-ID');}catch{/* Keep invalid text available for correction. */}});
 q('[data-apply]').onclick=()=>{try{const values=Object.fromEntries([...host.querySelectorAll('[data-bulk]')].map(el=>[el.dataset.bulk,el.value]));const result=applyVariantBulk(rows,values,q('[data-target]').value,selected);rows=result.rows;undo=result.undo;edited.clear();paint();dirty();status('Draf diterapkan ke '+result.count+' varian. Belum tersimpan ke database.');}catch(error){status(error.message,true);}};
 q('[data-undo]').onclick=()=>{const result=undoVariantBulk(rows,undo,edited);rows=result.rows;undo=[];edited.clear();paint();dirty();status(result.restored+' nilai dari penerapan terakhir dibatalkan. Edit per baris lainnya dipertahankan.');};
 q('[data-add]').onclick=()=>{check(rows.length<100,'Maksimal 100 varian.');rows.push({id:'V-'+crypto.randomUUID(),stock:0,sku:'',color:'',size:''});paint();dirty();};
 paint();
 return {
  read(){return rows.map(v=>{const out={...v,sku:String(v.sku||'').trim(),color:String(v.color||'').trim(),size:String(v.size||'').trim(),image:v.image||'',stock:variantNumber(v.stock,'stock'),hpp:variantNumber(v.hpp,'hpp',{optional:true}),weight:variantNumber(v.weight,'weight',{optional:true}),pricing:{...v.pricing,retail:variantNumber(v.pricing?.retail,'retail',{optional:true}),wholesale:variantNumber(v.pricing?.wholesale,'wholesale',{optional:true})}};check(!out.image||/^https:\/\//.test(out.image),'Foto harus berupa URL HTTPS.');return out;});},
  async upload(productId){check(!preparing,'Tunggu pratinjau foto selesai.');for(const [variantId,photo] of photos){const url=await productPhotos(c).upload(photo,{productId,variantId,onProgress:n=>status('Upload foto '+n+'% — perubahan produk belum disimpan.')});rows.find(v=>v.id===variantId).image=url;photos.delete(variantId);onChange();}paint();},
  snapshot(){return structuredClone(rows);},
  queuedPhotos(){return [...photos.keys()];},
  replace(value){rows=structuredClone(value);selected=new Set([...selected].filter(id=>rows.some(v=>v.id===id)));undo=[];edited.clear();paint();},
  markSaved(){q('[data-dirty]').textContent='Varian tersimpan';q('[data-dirty]').classList.remove('changed');},
  pending(){return preparing>0;},
  updateParent(value){q('[data-unit]').textContent=(value.saleUnit||'unit')+'; '+(value.packPcs>0?value.packPcs+' pcs per unit':'isi pcs belum ditetapkan');for(const [field,placeholder] of Object.entries({retail:value.retail,wholesale:value.wholesale,weight:value.weight}))for(const el of host.querySelectorAll('[data-field="'+field+'"]'))el.placeholder=placeholder==null||placeholder===''?'Induk':String(number(field,placeholder));},
  setLocked(value){locked=value;host.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=value||!canEdit);sync();},
  reviewStock(latest){for(const row of rows){const v=latest.variants.find(x=>x.id===row.id);if(v){row.stock=v.stock;row.reserved=v.reserved||0;}}undo=undo.filter(e=>e.field!=='stock');paint();dirty();status('Stok terbaru sudah dimuat. Periksa angka, lalu isi kembali stok akhir yang memang ingin diganti. Harga dan edit lain tetap.');},
  dispose(){for(const url of urls.values())URL.revokeObjectURL(url);}
 };
}
