import {esc,money} from './planning-ui.js?v=picker-20260923-r21';
import {check} from './manual-domain.js?v=picker-20260923-r21';
import {applyVariantBulk,undoVariantBulk,variantNumber,variantValue,setVariantValue} from './variant-draft.js?v=picker-20260923-r21';
import {prepareProductPhoto,productPhotos} from './product-photos.js?v=picker-20260923-r21';
import {deriveOptions,reconcileOptions,optionGroups,groupPhotoTargets} from './variant-options.js?v=picker-20260923-r21';

export function mountVariantTable(host,{variants,parent={},c,onChange=()=>{},canEdit=true}){
 let rows=structuredClone(variants),selected=new Set(),undo=[],edited=new Set(),preparing=0,locked=false;
 const photos=new Map(),urls=new Map(),originalIds=new Set(parent.id||parent.revision?variants.map(v=>v.id):[]);let options=deriveOptions(rows,parent.variationOptions),pendingOptions=null;const activeRows=()=>rows.filter(v=>!v.optionArchived);const emptyNewRow=v=>!originalIds.has(v.id)&&!v.image&&(v.stock===''||v.stock===0&&!v.sku&&!v.color&&!v.size)&&v.hpp==null&&v.weight==null&&!v.pricing?.retail&&!v.pricing?.wholesale;
 const number=(k,v)=>v==null?'':['retail','wholesale','hpp'].includes(k)&&/^\d+$/.test(String(v))?Number(v).toLocaleString('id-ID'):v;
 const control=(row,k,label,{optional=false,placeholder='',money=false}={})=>`<label class="variant-cell"><span class="sr-only">${esc(label+' '+([row.color,row.size].filter(Boolean).join(' / ')||row.sku||row.id))}</span>${money?'<span class="variant-rp">Rp</span>':''}<input data-field="${k}" aria-label="${esc(label+' '+([row.color,row.size].filter(Boolean).join(' / ')||row.sku||row.id))}" value="${esc(number(k,variantValue(row,k)))}" ${['stock','retail','wholesale','hpp','weight'].includes(k)?'inputmode="numeric"':''} placeholder="${esc(placeholder)}" ${optional?'':'required'} ${canEdit?'':'disabled'}></label>`;
 host.innerHTML=`<div class="variant-heading"><h2>Varian & Stok</h2><span data-dirty class="variant-dirty" role="status">Belum ada perubahan varian</span></div><p class="muted">Stok dalam satuan jual (<span data-unit></span>). Harga dan berat kosong mengikuti induk. HPP hanya untuk admin.</p><div class="variant-bulk"><label class="field">Target<select data-target aria-label="Target pengaturan massal"><option value="all">Semua Varian</option><option value="selected">Varian Terpilih</option></select></label><label class="field">Qty / Stok<input data-bulk="stock" aria-label="Qty massal" inputmode="numeric" placeholder="Tidak diubah"></label><label class="field">Harga Eceran (Rp)<input data-bulk="retail" aria-label="Eceran massal" inputmode="numeric" placeholder="Tidak diubah"></label><label class="field">Harga Grosir (Rp)<input data-bulk="wholesale" aria-label="Grosir massal" inputmode="numeric" placeholder="Tidak diubah"></label><button type="button" data-apply class="primary" disabled>Terapkan</button><div class="variant-bulk-note"><span data-target-count></span> · Hanya kolom terisi diubah. Qty menetapkan stok akhir.</div></div><div class="variant-draft-actions"><span>Terapkan hanya mengisi draf. Gunakan Simpan Produk untuk menyimpan.</span><button type="button" data-undo disabled>Batalkan penerapan terakhir</button></div><p data-status role="status" class="variant-status" hidden></p><div class="variant-table-scroll" tabindex="0" role="region" aria-label="Tabel varian, geser horizontal untuk kolom lainnya"><table class="variant-table"><thead><tr><th><input type="checkbox" data-all aria-label="Pilih semua varian"></th><th>Foto & Warna/Nama Varian</th><th>Ukuran</th><th>Stok/Qty</th><th>Harga Eceran</th><th>Harga Grosir</th><th>HPP</th><th>Berat (gram)</th><th>SKU</th></tr></thead><tbody></tbody></table></div><div class="variant-bottom"><button type="button" data-add>+ Tambah varian</button><small>Harga per satuan jual. Minimum grosir mengikuti pengaturan produk.</small></div>`;
 const q=s=>host.querySelector(s),status=(text,error=false)=>{q('[data-status]').hidden=!text;q('[data-status]').textContent=text;q('[data-status]').classList.toggle('error',error);};
 const settings=document.createElement('section');settings.className='variant-options';settings.setAttribute('aria-label','Pengaturan variasi');q('.variant-bulk').before(settings);
 function paintOptions(){settings.innerHTML='<div class="variant-options-title"><h3>Pengaturan variasi</h3><span>Nama opsi berlaku untuk seluruh kombinasi. Perubahan masih berupa draf.</span></div><div class="variant-option-axes">'+['color','size'].map((axis,i)=>{const a=options[axis];return `<fieldset data-axis="${axis}"><legend>Variasi ${i+1}</legend><div class="variant-axis-head"><label class="field">Nama kelompok<input data-axis-name value="${esc(a.name)}" aria-label="Nama Variasi ${i+1}" maxlength="50"></label><label class="variant-axis-toggle"><input type="checkbox" data-axis-enabled ${a.enabled?'checked':''}> Gunakan</label></div>${a.enabled?`<div class="variant-option-list">${a.options.filter(o=>!o.archived).map(o=>`<div class="variant-option" data-option-id="${esc(o.id)}"><input data-option-label value="${esc(o.label)}" aria-label="${esc('Opsi '+a.name+' '+o.label)}" maxlength="100"><div class="variant-option-actions"><button type="button" data-move="-1" aria-label="${esc('Naikkan '+o.label)}">↑</button><button type="button" data-move="1" aria-label="${esc('Turunkan '+o.label)}">↓</button><button type="button" data-remove-option aria-label="${esc('Hapus opsi '+o.label)}">×</button></div></div>`).join('')}</div><div class="variant-option-add"><input data-new-option aria-label="${esc('Opsi baru '+a.name)}" placeholder="Tambah opsi" maxlength="100"><button type="button" data-add-option>+ Tambah</button></div>`:'<p class="muted">Kelompok tidak digunakan.</p>'}${a.options.some(o=>o.archived)?`<details class="variant-archived-options"><summary>Opsi diarsipkan</summary>${a.options.filter(o=>o.archived).map(o=>`<button type="button" data-restore-option="${esc(o.id)}">Pulihkan ${esc(o.label)}</button>`).join('')}</details>`:''}</fieldset>`;}).join('')+'</div><div data-option-confirm hidden role="alert"></div><p class="muted" data-combination-count></p>';sync();}
 function changeOptions(next,preserveInput=false){const before=rows;rows=reconcileOptions(rows,options,next,document.querySelector('#product-edit [name=sku]')?.value||parent.sku).filter(v=>!v.optionArchived||!emptyNewRow(v));options=next;pendingOptions=null;selected=new Set([...selected].filter(id=>rows.some(v=>v.id===id&&!v.optionArchived)));if(!preserveInput)paintOptions();paint();dirty();const added=rows.filter(v=>!before.some(x=>x.id===v.id)).length;status(added?added+' kombinasi baru ditambahkan. Isi Qty/Stok; 0 sah. Nilai varian lama tetap.':'Opsi diperbarui dalam draf. ID dan data kombinasi tetap.');}
 function propose(next){const nextRows=reconcileOptions(rows,options,next,parent.sku),affected=nextRows.filter(v=>v.optionArchived&&!emptyNewRow(v)&&!rows.find(x=>x.id===v.id)?.optionArchived);if(!affected.length)return changeOptions(next);pendingOptions=next;const box=q('[data-option-confirm]');box.hidden=false;box.innerHTML='<strong>'+affected.length+' kombinasi akan diarsipkan</strong><p>Kombinasi tidak ditawarkan untuk pembelian baru. ID, stok, harga, foto dan referensi pesanan lama tetap disimpan. Tidak ada stok yang dipindahkan.</p><ul>'+affected.map(v=>'<li>'+esc([v.color,v.size].filter(Boolean).join(' / ')+' — '+v.sku+' · stok '+v.stock)+'</li>').join('')+'</ul><button type="button" data-cancel-options>Batal</button> <button type="button" data-confirm-options>Arsipkan kombinasi dalam draf</button>';}
 settings.addEventListener('input',e=>{if(locked||!canEdit||!e.target.matches('[data-axis-name],[data-option-label]'))return;const axis=e.target.closest('[data-axis]').dataset.axis,next=structuredClone(options);try{if(e.target.matches('[data-axis-name]'))next[axis].name=e.target.value;else next[axis].options.find(o=>o.id===e.target.closest('[data-option-id]').dataset.optionId).label=e.target.value.trim();changeOptions(next,true);}catch(error){status(error.message,true);}});
 settings.addEventListener('change',e=>{if(locked||!canEdit||!e.target.matches('[data-axis-enabled]'))return;const axis=e.target.closest('[data-axis]').dataset.axis,next=structuredClone(options);next[axis].enabled=e.target.checked;try{propose(next);}catch(error){status(error.message,true);}});
 settings.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||locked||!canEdit)return;try{if(button.hasAttribute('data-cancel-options')){pendingOptions=null;paintOptions();return;}if(button.hasAttribute('data-confirm-options'))return changeOptions(pendingOptions);const axis=button.closest('[data-axis]')?.dataset.axis;if(!axis)return;const next=structuredClone(options),a=next[axis],option=button.closest('[data-option-id]'),oid=option?.dataset.optionId;
 if(button.hasAttribute('data-add-option')){const input=button.closest('fieldset').querySelector('[data-new-option]'),label=input.value.trim();check(label,'Isi nama opsi baru.');const archived=a.options.find(o=>o.archived&&o.label.toLocaleLowerCase('id-ID')===label.toLocaleLowerCase('id-ID'));if(archived)archived.archived=false;else a.options.push({id:axis[0]+'-'+crypto.randomUUID(),label});}
 if(button.hasAttribute('data-remove-option'))a.options.find(o=>o.id===oid).archived=true;
 if(button.hasAttribute('data-restore-option'))a.options.find(o=>o.id===button.dataset.restoreOption).archived=false;
 if(button.hasAttribute('data-move')){const i=a.options.findIndex(o=>o.id===oid),j=i+Number(button.dataset.move);if(j<0||j>=a.options.length)return;[a.options[i],a.options[j]]=[a.options[j],a.options[i]];}
 propose(next);}catch(error){status(error.message,true);}});
 function targetIds(){const target=q('[data-target]').value;if(target==='all')return new Set(activeRows().map(v=>v.id));if(target==='selected')return selected;return new Set((optionGroups(rows,options).find(g=>'group:'+g.id===target)?.rows||[]).map(v=>v.id));}
 function dirty(){q('[data-dirty]').textContent='Perubahan belum disimpan';q('[data-dirty]').classList.add('changed');onChange();}
 function sync(){if(locked||!canEdit)host.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);const active=activeRows(),count=active.filter(v=>targetIds().has(v.id)).length;q('[data-target-count]').textContent=count+' varian akan menerima perubahan';q('[data-apply]').disabled=locked||!canEdit||!count||![...host.querySelectorAll('[data-bulk]')].some(i=>i.value.trim());q('[data-undo]').disabled=locked||!canEdit||!undo.length;q('[data-all]').checked=active.length>0&&active.every(v=>selected.has(v.id));q('[data-all]').indeterminate=selected.size>0&&!q('[data-all]').checked;q('[data-add]').hidden=true;const summary=q('[data-combination-count]');if(summary)summary.textContent=optionGroups(rows,options).length+' kelompok · '+active.length+' kombinasi aktif'+(rows.length>active.length?' · '+(rows.length-active.length)+' kombinasi diarsipkan':'');}
 function photoMarkup(src,name,attribute){return `<div class="variant-photo">${src?`<img src="${esc(src)}" alt="${esc('Foto '+name)}">`:'<span>Foto</span>'}<label class="variant-upload">${src?'Ganti foto':'Upload foto'}<input ${attribute} type="file" accept="image/jpeg,image/png" aria-label="${esc('Upload foto '+name)}" ${canEdit?'':'disabled'}></label></div>`;}
 function paint(){const groups=optionGroups(rows,options),target=q('[data-target]').value;q('[data-target]').innerHTML='<option value="all">Semua Varian</option><option value="selected">Varian Terpilih</option>'+groups.map(g=>`<option value="group:${esc(g.id)}">${esc(options.color.name+': '+g.label)}</option>`).join('');q('[data-target]').value=[...q('[data-target]').options].some(o=>o.value===target)?target:'all';
 q('tbody').innerHTML=groups.map(g=>g.rows.map((v,i)=>{const name=[v.color,v.size].filter(Boolean).join(' / ')||v.sku||'Standar',src=urls.get(v.id)||v.image||'',queuedGroup=photos.get('group:'+g.id),groupSrc=(queuedGroup?urls.get(queuedGroup.targets.find(id=>!rows.find(r=>r.id===id)?.imageOverride)):null)||g.image,custom=v.imageOverride===true||!!v.image&&v.image!==g.image;return `<tr data-variant-id="${esc(v.id)}" ${i===0?'class="variant-group-start"':''}><td><input type="checkbox" data-select aria-label="${esc('Pilih '+name)}" ${selected.has(v.id)?'checked':''}></td>${i===0?`<td rowspan="${g.rows.length}" class="variant-group-cell" data-group-id="${esc(g.id)}"><div class="variant-group-identity"><strong>${esc(g.label)}</strong>${photoMarkup(groupSrc,g.label,'data-group-photo')}<small>${g.rows.length} kombinasi · JPG/PNG maks. 2 MB</small><small>Foto khusus kombinasi tetap dipertahankan.</small></div></td>`:''}<td><strong class="variant-size-label">${esc(v.size||'—')}</strong><details class="variant-specific-photo"><summary>${custom?'Foto khusus ✓':'Foto khusus'}</summary>${photoMarkup(src,name,'data-photo')}<label>URL HTTPS<input data-field="image" aria-label="${esc('URL foto '+name)}" value="${esc(v.image||'')}" type="url"></label><button type="button" data-use-group>Ikuti foto kelompok</button></details></td><td>${control(v,'stock','Stok')}</td><td>${control(v,'retail','Harga Eceran',{optional:true,placeholder:parent.website?.retail?number('retail',parent.website.retail):'Induk',money:true})}</td><td>${control(v,'wholesale','Harga Grosir',{optional:true,placeholder:parent.website?.tiers?.[0]?.price?number('wholesale',parent.website.tiers[0].price):'Induk',money:true})}</td><td>${control(v,'hpp','HPP',{optional:true,placeholder:parent.hpp!=null?number('hpp',parent.hpp):'Belum diisi',money:true})}</td><td>${control(v,'weight','Berat',{optional:true,placeholder:String(parent.weight??'Induk')})}</td><td>${control(v,'sku','SKU')}</td></tr>`;}).join('')).join('');
 let archive=q('[data-archive-rows]');if(!archive){archive=document.createElement('details');archive.dataset.archiveRows='';archive.className='variant-archive';q('.variant-table-scroll').after(archive);}const hidden=rows.filter(v=>v.optionArchived);archive.hidden=!hidden.length;archive.innerHTML='<summary>'+hidden.length+' kombinasi diarsipkan — data tetap tersimpan</summary><ul>'+hidden.map(v=>'<li>'+esc([v.color,v.size].join(' / ')+' — '+v.sku+' · stok '+v.stock)+'</li>').join('')+'</ul><p>Pulihkan opsi di Pengaturan variasi untuk menggunakan kombinasi dan ID yang sama.</p>';sync();}
 q('[data-unit]').textContent=(parent.saleUnit||'unit')+'; '+(parent.website?.packPcs?parent.website.packPcs+' pcs per unit':'isi pcs diatur di atas');
 host.addEventListener('input',e=>{if(e.target.type==='checkbox'||e.target.type==='file')return;if(e.target.matches('[data-field]')){const row=rows.find(v=>v.id===e.target.closest('[data-variant-id]').dataset.variantId),k=e.target.dataset.field;setVariantValue(row,k,e.target.value);edited.add(row.id+'/'+k);if(k==='image'){row.imageOverride=true;photos.delete(row.id);if(urls.has(row.id))URL.revokeObjectURL(urls.get(row.id));urls.delete(row.id);}dirty();}sync();});
 host.addEventListener('change',async e=>{const el=e.target;
  if(el.matches('[data-all]')){selected=new Set(el.checked?activeRows().map(v=>v.id):[]);host.querySelectorAll('[data-select]').forEach(x=>x.checked=el.checked);sync();}
  if(el.matches('[data-select]')){const id=el.closest('[data-variant-id]').dataset.variantId;el.checked?selected.add(id):selected.delete(id);sync();}
  if(el.matches('[data-target]'))sync();
  if(el.matches('[data-photo],[data-group-photo]')&&el.files?.[0]){const group=el.hasAttribute('data-group-photo')?optionGroups(rows,options).find(g=>g.id===el.closest('[data-group-id]').dataset.groupId):null,row=rows.find(v=>v.id===el.closest('[data-variant-id]').dataset.variantId),targets=group?groupPhotoTargets(group):[row.id],queueId=group?'group:'+group.id:row.id;preparing++;status('Menyiapkan pratinjau foto…');try{check(targets.length,'Semua kombinasi memiliki foto khusus. Gunakan Ikuti foto kelompok pada kombinasi yang diperlukan.');const photo=await prepareProductPhoto(el.files[0]);photos.set(queueId,{photo,targets,groupId:group?.id});for(const id of targets){if(urls.has(id))URL.revokeObjectURL(urls.get(id));urls.set(id,URL.createObjectURL(photo.blob));}if(!group)row.imageOverride=true;dirty();status('Foto dipilih. Upload dan penyimpanan dilakukan saat Simpan Produk.');paint();}catch(error){status(error.message,true);}finally{preparing--;}}

 });
 host.addEventListener('focusout',e=>{const k=e.target.dataset.field||e.target.dataset.bulk;if(['retail','wholesale','hpp'].includes(k)&&e.target.value.trim())try{e.target.value=variantNumber(e.target.value,k).toLocaleString('id-ID');}catch{/* Keep invalid text available for correction. */}});
 q('[data-apply]').onclick=()=>{try{const values=Object.fromEntries([...host.querySelectorAll('[data-bulk]')].map(el=>[el.dataset.bulk,el.value]));const result=applyVariantBulk(rows,values,'selected',targetIds());rows=result.rows;undo=result.undo;edited.clear();paint();dirty();status('Draf diterapkan ke '+result.count+' varian. Belum tersimpan ke database.');}catch(error){status(error.message,true);}};
 q('[data-undo]').onclick=()=>{const result=undoVariantBulk(rows,undo,edited);rows=result.rows;undo=[];edited.clear();paint();dirty();status(result.restored+' nilai dari penerapan terakhir dibatalkan. Edit per baris lainnya dipertahankan.');};
 host.addEventListener('click',e=>{if(!e.target.matches('[data-use-group]')||locked||!canEdit)return;const row=rows.find(v=>v.id===e.target.closest('[data-variant-id]').dataset.variantId),group=optionGroups(rows,options).find(g=>g.rows.some(v=>v.id===row.id));row.image=group.image;row.imageOverride=false;photos.delete(row.id);urls.delete(row.id);const queued=photos.get('group:'+group.id);if(queued&&!queued.targets.includes(row.id)){queued.targets.push(row.id);urls.set(row.id,URL.createObjectURL(queued.photo.blob));}paint();dirty();});
 paintOptions();paint();

 return {
  read(){check(!pendingOptions,'Tinjau atau batalkan pengarsipan opsi sebelum menyimpan.');for(const axis of ['color','size']){const box=settings.querySelector('[data-axis='+axis+']');check(box.querySelector('[data-axis-name]').value===options[axis].name,'Perbaiki nama kelompok sebelum menyimpan.');for(const input of box.querySelectorAll('[data-option-label]'))check(input.value.trim()===options[axis].options.find(o=>o.id===input.closest('[data-option-id]').dataset.optionId).label,'Perbaiki nama opsi sebelum menyimpan.');}return rows.map(v=>{const out={...v,sku:String(v.sku||'').trim(),color:String(v.color||'').trim(),size:String(v.size||'').trim(),image:v.image||'',stock:variantNumber(v.stock,'stock'),hpp:variantNumber(v.hpp,'hpp',{optional:true}),weight:variantNumber(v.weight,'weight',{optional:true}),pricing:{...v.pricing,retail:variantNumber(v.pricing?.retail,'retail',{optional:true}),wholesale:variantNumber(v.pricing?.wholesale,'wholesale',{optional:true})}};check(!out.image||/^https:\/\//.test(out.image),'Foto harus berupa URL HTTPS.');return out;});},
  async upload(productId){check(!preparing,'Tunggu pratinjau foto selesai.');for(const [queueId,entry] of photos){const targets=entry.targets.filter(id=>rows.some(v=>v.id===id)&&!(entry.groupId!==undefined&&rows.find(v=>v.id===id).imageOverride));if(!targets.length){photos.delete(queueId);continue;}const url=await productPhotos(c).upload(entry.photo,{productId,variantId:targets[0],onProgress:n=>status('Upload foto '+n+'% — perubahan belum disimpan.')});for(const id of targets){rows.find(v=>v.id===id).image=url;if(urls.has(id))URL.revokeObjectURL(urls.get(id));urls.delete(id);}if(entry.groupId!==undefined){const option=options.color.options.find(o=>o.id===entry.groupId);if(option)option.image=url;}photos.delete(queueId);onChange();}paint();},
  readOptions(){return structuredClone(options);},
  snapshot(){return structuredClone(rows);},
  queuedPhotos(){return [...photos.keys()];},
  replace(value,config){rows=structuredClone(value);options=deriveOptions(rows,config);paintOptions();selected=new Set([...selected].filter(id=>rows.some(v=>v.id===id)));undo=[];edited.clear();paint();},
  markSaved(){q('[data-dirty]').textContent='Varian tersimpan';q('[data-dirty]').classList.remove('changed');status('');for(const el of host.querySelectorAll('[data-bulk]'))el.value='';for(const row of rows)originalIds.add(row.id);sync();},
  pending(){return preparing>0;},
  updateParent(value){q('[data-unit]').textContent=(value.saleUnit||'unit')+'; '+(value.packPcs>0?value.packPcs+' pcs per unit':'isi pcs belum ditetapkan');for(const [field,placeholder] of Object.entries({retail:value.retail,wholesale:value.wholesale,weight:value.weight}))for(const el of host.querySelectorAll('[data-field="'+field+'"]'))el.placeholder=placeholder==null||placeholder===''?'Induk':String(number(field,placeholder));},
  setLocked(value){locked=value;host.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=value||!canEdit);sync();},
  reviewStock(latest){for(const row of rows){const v=latest.variants.find(x=>x.id===row.id);if(v){row.stock=v.stock;row.reserved=v.reserved||0;}}undo=undo.filter(e=>e.field!=='stock');paint();dirty();status('Stok terbaru sudah dimuat. Periksa angka, lalu isi kembali stok akhir yang memang ingin diganti. Harga dan edit lain tetap.');},
  dispose(){for(const url of urls.values())URL.revokeObjectURL(url);}
 };
}
